### ISSUE TITLE
Não inicia sessão, usando no MyZap

### ISSUE THREAD

**Issue by tessarolli** [wppconnect-team/wppconnect#1000]
## Description

Quando tento inicar uma nova sessão tenho sempre uma resposta similar no console do linux

| | / / __ / __ / / ____ ____ ___ ____/ /
| | /| / / // / // / / / __ / __ / __ / _ / / /
| |/ |/ / ___/ / // // / / / / / / / / // /
|/|// // _/_// /// //_/_/__/
info: [123456:browser] Initializing browser...
info: [123456:client] Initializing...
info: [123456:client] WhatsApp WEB version: undefined
info: [123456:client] WhatsApp WEB version: undefined
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:session] Session Unpaired
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: undefined
info: [123456:client] WhatsApp WEB version: undefined
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: 2.2126.14
info: [123456:client] WhatsApp WEB version: undefined
info: [123456:client] WhatsApp WEB version: undefined

O que devo verificar? 

Acredito que deva ser algum problema de configuração

**Comment by edgardmessias** [comment]
Boa noite, primeiramente você não preencheu nada do que está sendo usado ao abrir uma issue.

E em segundo, recomendo verificar juntamente com o MyZap para que possam te ajudar corretamente.

Caso precise, abra uma nova ISSUE e preencha tudo detalhado para que possamos ajudar.

**Comment by SheikSystem** [comment]
voce conseguiu resolver esse problema? estou com o mesmo problema..
