### ISSUE TITLE
Erro ao enviar Botões

### ISSUE THREAD

**Issue by alexandreclayton** [wppconnect-team/wppconnect#1004]
## Description

Até ontem 06/04/2022 eu estava conseguindo enviar os botões, porem hoje não.

Alguém está passando por esse mesmo problema?

## Environment

- **WPPConnect version(s): ^1.12.8
- **WA-JS version(s): 1.2.5
- **Browser: Google Chrome 100.0.4896.75
- **OS: ubuntu 18.04
- **Node version:  v16.14.2
- **WhatsApp version: 2.2204.13
- **MultiDevice (BETA): no

**Comment by edgardmessias** [comment]
Infelizmente o WhatsApp está mudando as APIs do whatsapp web, na qual está dificultando enviar esses botões no MultiDevice, ou seja, estão migrando todos e travando alguns recursos.

**Comment by edgardmessias** [comment]
Tente agora com a nova release. Teste com a opção useTemplateButtons: true ou false. Os botões é para estar funcionando no beta do business.

https://github.com/wppconnect-team/wppconnect/releases/tag/v1.13.0
