### ISSUE TITLE
dont use passed whatsapp-web version script

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1028]
## Description

I try change whatsapp web version for try some variants to resolve #1027 

I pass config param old whatsappVersion into wppconnect.create() like here https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/creating-client.html#passing-options-on-create 

but when in start callback I call  client.getWAVersion() -> receive latest version of whatsapp web

pass 2.2212.8, receive 2.2214.9

## Environment

- **WPPConnect version(s):** 1.12.8
- **WA-JS version(s):** 1.2.5
- **Browser:** Chrome 99
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2212.8
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Try to update to latest release of all (lib, wa-js and wa-version)

https://github.com/wppconnect-team/wppconnect/releases/tag/v1.13.0

**Comment by antirek** [comment]
Work well, great thanks ))
