### ISSUE TITLE
Receiving message in onMessage after calling dispose

### ISSUE THREAD

**Issue by SyedSaifAli** [wppconnect-team/wppconnect#103]
```
const wppconnect = require('../../dist');

wppconnect
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  a = client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Wppconnect 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
  setTimeout(()=>{
    a.then(b=> b.dispose());
  },10000);
}

```

I used the example code given in the repo and added setTimeout to dispose.

According to the above code.
after 10 seconds, the listener should stop listening to new messages.
But I was still getting the new messages.

**Comment by edgardmessias** [comment]
Thanks @SyedSaifAli , I could identify what was the problem, so I will fix it

**Comment by SyedSaifAli** [comment]
> Thanks @SyedSaifAli , I could identify what was the problem, so I will fix it

Thank you :) Please let me know once you fix it :)

**Comment by edgardmessias** [comment]
@SyedSaifAli , could you test the nightly version?

How to install: https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/installation.html

**Comment by edgardmessias** [comment]
@SyedSaifAli , I make a little change about the return of `onMessage` to return the direct object instead of a promise

**Comment by SyedSaifAli** [comment]
> @SyedSaifAli , I make a little change about the return of `onMessage` to return the direct object instead of a promise

Is this on the nightly version?

**Comment by edgardmessias** [comment]
> > @SyedSaifAli , I make a little change about the return of `onMessage` to return the direct object instead of a promise
> 
> Is this on the nightly version?

Yes

**Comment by SyedSaifAli** [comment]
> > > @SyedSaifAli , I make a little change about the return of `onMessage` to return the direct object instead of a promise
> > 
> > 
> > Is this on the nightly version?
> 
> Yes

Okay.

**Comment by SyedSaifAli** [comment]
@edgardmessias It's working now :D
In this [link](https://github.com/wppconnect-team/wppconnect/commit/0682c06122dc534789cea5721a515e4bdd96e4de)
I can see that you have moved the `listener on and listener off` to another common function.
But how does moving to a common function solved this problem? 😅

**Comment by edgardmessias** [comment]
To dispose an event on Event emitter, both argument must in off method must be the same of "on".
The maid problem was the on function wrapped the call in an arrow function, as a consequence, it is not the same function in "off"

**Comment by SyedSaifAli** [comment]
Great 💐
