### ISSUE TITLE
Após reiniciar o WPP Connect, ele não detecta a sessão e pede para ler o QRCode novamente

### ISSUE THREAD

**Issue by rcovery** [wppconnect-team/wppconnect#1033]
## Description

Após vincular o WhatsApp e reiniciar o WPP Connect, ele não detecta a sessão e pede para ler o QRCode novamente, e além disso, este novo QRCode do bug não é enviado para a URL do Webhook, então não é possível ler na aplicação

## Environment

- **WPPConnect version(s):** 1.13.0
- **WA-JS version(s):** 2.0.0
- **Browser:** Chrome Latest
- **OS:** Ubuntu 20.04
- **Node version:** Node 16.3.0
- **WhatsApp version:** 2.2214.9
- **MultiDevice:** yes

## Steps to Reproduce

1. Vinculei meu WhatsApp
2. Parei o WPP Connect e iniciei novamente
3. Precisei escanear o QRCode novamente

## Log Output

![image](https://user-images.githubusercontent.com/33844142/165164556-76618e2e-21e7-4ab1-9d36-09e2970a3df7.png)

**Comment by domalak** [comment]
Hi. I solved this issue today by adding this option to `create` method:
```
puppeteerOptions: {
  userDataDir: './tokens/mySessionName',
},
```

**Comment by rcovery** [comment]
Hi! I added this option and it's working now, thx for the help!
