### ISSUE TITLE
Erro ao enviar Vídeos 

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#104]
Estou usando a função **sendFile** para enviar VÍDEOS no formato MP4.

No LOCALHOST funciona perfeitamente. Porém, no VPS não funciona. Retorna este erro abaixo:

![WhatsApp Image 2021-04-06 at 15 09 06](https://user-images.githubusercontent.com/35501007/113760169-4c363000-96ec-11eb-9aef-205ce694da5a.jpeg)

Abaixo segue o print da função CREATE

![Screenshot_10](https://user-images.githubusercontent.com/35501007/113760808-0fb70400-96ed-11eb-8884-ac15a21be723.jpg)

**Comment by edgardmessias** [comment]
Isso ocorre por causa de estar utilizando Chromium em vez de Chrome. Se alterar para Chrome (Instalando no linux primeiro), resolve esse problema.

Vou deixar a issue aberta para melhorar a documentação e adicionar warnings sobre esse problema

**Comment by mvac1991** [comment]
> Isso ocorre por causa de estar utilizando Chromium em vez de Chrome. Se alterar para Chrome (Instalando no linux primeiro), resolve esse problema.
> 
> Vou deixar a issue aberta para melhorar a documentação e adicionar warnings sobre esse problema

Show, resolveu meu problema. Muito obrigado

**Comment by edgardmessias** [comment]
A fim de resolver essa issue de uma vez, estou centralizando para tentar implementar alguma solução na V2 desse projeto

**Comment by roysG** [comment]
Any update?
