### ISSUE TITLE
sendMessage with buttons don't send message

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1043]
## Description

strange behavior: send message with buttons and it like incoming on sender whatsapp and no incoming on 'to' whatsapp

`````
sendText('7913XXXX01@c.us', 'text', {
   useTemplateButtons: true,
   buttons: [
     {id: 'id1', text: 'text1'}
   ],
});

`````
in logs I see two incoming messages with type 'chat'
in first 
`````
to: '7913XXXX01@c.us',
from: '7913XXXX02@c.us' //it's sender whatsapp
`````
in second 
`````
to: '7913XXXX02@c.us',  //to sender?? %)
from: '7913XXXX01@c.us'
`````

from and to was changed

without buttons all works well

## Environment

- **WPPConnect version(s):** 1.13.0
- **WA-JS version(s):** 2.0.0 and 2.1.0
- **Browser:** Chrome 99
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2214.9
- **MultiDevice (BETA):** no

**Comment by antirek** [comment]
additional experience

if use for sending beta whatsapp - it's works. But with nuances ))

on target device message with buttons is visible - it is good.   but in sender whatsapp app sent message is visible in chat with self. this is bug of whatsapp? or side-effect of messages with buttons?

**Comment by edgardmessias** [comment]
@antirek , it is a side-effect of messages with buttons, maybe a bug in the Whatsapp APP.

About sending, it only works with Business with MultiDevice enabled

**Comment by antirek** [comment]
ok, @edgardmessias thanks. 
I see that more and more whatsapp apps by default are multidevice-enabled.
