### ISSUE TITLE
Desconexão com o aparelho conectado

### ISSUE THREAD

**Issue by Mafealno** [wppconnect-team/wppconnect#1044]
Fiz a subida do bot no heroku e faço a conexão com o whatsapp que deverá responder as mensagens. Após algum tempo, o aparelho para de responder as mensagens pois foi desconectado do bot. Acredito que essa desconexão ocorra por conta de inatividade.

Já implementei o tokenStore para recuperação do token e phoneWatchdog para forcar a verificação da conexão e desta forma não desconectar mais porém nada funcionou. 

Existe alguma outra maneira de forçar a conexão do aparelho?

Desde já agradeço.

**Comment by edgardmessias** [comment]
Você precisa definir o userDataDir para persistir, por causa do multidevice, mudou umas coisas relacionadas a autenticação

https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/creating-client.html#multidevice-beta

**Comment by Mafealno** [comment]
Então, o problema ainda persiste. Quando o servidor está rodando no Heroku, o aparelho é desconectado automaticamente e não reconecta, existe algo que possa fazer ou implementar para não desconectar ou se desconectar, já ser reconectado?
