### ISSUE TITLE
onAnyMesssage lost message

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#105]
sometimes  receive message will miss with function onAnyMesssage

**Comment by edgardmessias** [comment]
@Lucipher , could you provide some steps to reprodute it?

**Comment by Lucipher** [comment]
I am using onAnyMesssage to get message  as below
![image](https://user-images.githubusercontent.com/1323545/113955313-11e4a400-984e-11eb-8a47-eb3d950e1cc8.png)

**Comment by edgardmessias** [comment]
@Lucipher , could you confirm to me if it happen when there are some disconnection between WhatsApp web and the Phone?

**Comment by Lucipher** [comment]
@edgardmessias  I found the problem, onAnyMessage return message id not correct
![image](https://user-images.githubusercontent.com/1323545/116959568-833e3800-acd0-11eb-9c4b-7010367c16c2.png)
![image](https://user-images.githubusercontent.com/1323545/116959602-9ea94300-acd0-11eb-90e1-8a6b9ebcddf3.png)

on the same timestamp 1620059147 and return the same  message id

**Comment by Lucipher** [comment]
Sometimes will get message type "ciphertext"

**Comment by Lucipher** [comment]
It's usually on first message from non contact list dialog or from status@broadcast will get the  message type of  ciphertext

**Comment by daniloricalmeida** [comment]
sent media messages do not receive mediaData in onAnyMessages
...
mediaData: {
    type: 'ptt',
    mediaKeyTimestamp: 1625149833,
    mediaStage: 'REMOTE_UPLOADING',
    size: 4591,
    animationDuration: 0,
    animatedAsNewMsg: false,
    duration: '1',
    _swStreamingSupported: false,
    _listeningToSwSupport: false,
    isVcardOverMmsDocument: false
  }
...
