### ISSUE TITLE
sendListMessage não envia a mensagem

### ISSUE THREAD

**Issue by allanlisboa** [wppconnect-team/wppconnect#1054]
Ao tentar enviar uma mensagem com o **sendListMessage** a mensagem simplesmente não é enviada e não recebo nenhum log de erro. 

Estou utilizando o whatsapp business com o multi device ativo.

<img width="460" alt="Captura de Tela 2022-05-01 às 11 33 54" src="https://user-images.githubusercontent.com/37181884/166150621-c692c0d5-8ac8-4275-a368-907a6fc681f1.png">

**Comment by edgardmessias** [comment]
Isso foi resolvido a algumas versões atrás do WPPConnect
