### ISSUE TITLE
Mensagem chega sem conteúdo (Type "CIPHERTEXT")

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#1065]
## Description

Ao receber mensagens as vezes ela fica com status "Aguardando mensagem. Abra seu aparelho".. Como na imagem abaixo:

![WhatsApp Image 2022-05-08 at 05 27 13](https://user-images.githubusercontent.com/35501007/167288532-95f4e072-8e1f-41a3-9632-9725559540da.jpeg)

Quando isso acontece, não chega o "conteúdo" da mensagem, e isso está bugando minhas automações e dos meus clientes, veja o que aparece no terminal:

![WhatsApp Image 2022-05-08 at 05 27 49](https://user-images.githubusercontent.com/35501007/167288559-7311aa68-b52e-4662-b71a-d89498a820aa.jpeg)

## Environment

- **Wppconnect version(s):** [2.2214.9]
- **WA-JS version(s):** [2.0.2]
- **Browser:** [Google Chrome]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14.15.4]
- **WhatsApp App version:** [2.22.9.78]
- **OS mobile:** [Android Versão 5.1.1]
- **Tipo de WhatsApp (MD):** Normal (sem ser Business)

## Steps to Reproduce

1. Emparelhe o QR Code com a LIB e deixe uma conexão ativa nela;
2. Crie uma nova conexão (sem desconectar a da LIB) e emparelhe o QR Code com o WhatsApp Web e deixe uma guia do chrome aberta;
3. Crie um novo Whatsapp (usei um número virtual do bot do Telegram);
4. Abra o novo Whatsapp no celular (não conecte ele no Whatsapp) e envie uma mensagem para o BOT que está na lib e no waweb;
5. Veja no console.log do evento onAnyMessage que chega como "CIPHERTEXT"

**Comment by GiancarloJSantos** [comment]
Pelo meu entendimento, infelizmente não é algo que possa ser corrigido pela API. 

Ela está simplesmente lendo o que chegou no navegador (WhatsApp Web). Como não chegou nada, o conteúdo da mensagem está em branco.

A mesma situação ocorre nas outras APIs de WhatsApp (OpenWA, por exemplo).

Como sou desenvolvedor de chatbot, passei pelo mesmo problema que tu passaste.

Geralmente é uma mensagem inicial recebida de uma conta de WhatsApp Business. No aparelho físico aparece uma mensagem dizendo que não é contato e pode ser spam e dá as opões de bloquear/adicionar contato.

Nesse caso, o que eu fiz foi detectar essa situação e devolver uma mensagem padrão de resposta ("Olá!).

Isso faz com que o WhatsApp entenda e a API passe a aceitar/receber as outras mensagens normalmente.

Sei que é frustrante e espero que o caminho que sugeri possa de alguma maneira te dar uma luz.

Abraços.
