### ISSUE TITLE
image preview server

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1079]
@edgardmessias

I see that new feature https://github.com/wppconnect-team/wa-js/commit/638a0a8e89046182882dc53be0eb94dd2ef3a6e1 

questions:
Can I use own image preview server? Must I use own image preview server (because why installed servers must work for me)) )? 
Maybe do it optional config for using own image preview server? 

I check repo https://github.com/wppconnect-team/wa-js-api-server and I can deploy, and add my own domain for using in my wppconnect instances

**Comment by edgardmessias** [comment]
Hi @antirek 
Yes, I launched this feature with shared servers, to be easy for everyone.

I have plan to create an option in the future to allow the server list customization. The only requirement is to server an HTTP**S** environment.

**Comment by antirek** [comment]
ok, cool!  ))
of course, shared servers maybe used by default and custom server - optional 
https is not a problem with letsencrypt

**Comment by edgardmessias** [comment]
Resolved at https://github.com/wppconnect-team/wppconnect/commit/4479f9baf56c2a924de8b20515c4215039603753
