### ISSUE TITLE
Não está pegando dados de todos os grupos

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect#1089]
## Estou utilizando o endpoint all-groups do wppconnect-server e ele não está trazendo todos os grupos. Tirei a dúvida nos grupos de suporte e o problema está na lib, por esse motivo estou abrindo a issue aqui.
Quando os dados de um grupo não é retornado é necessário ter uma ação de entrada ou saída de um membro dentro do grupo do Whatsapp. Após essa ação se chamar novamente o endpoint os dados do grupo é retornado. 

## Environment

- **WPPConnect version(s):** 2.2214.12
- **WA-JS version(s):** 2.2.1
- **Browser:** Google Chrome 93.0.4577.63
- **OS:** Ubuntu 20.02
- **Node version:** 14.18.2
- **WhatsApp version:** WhatsApp Business 2.22.10.73
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Logar instância
2. Chamar endpoind de leitura de todos os grupos
3. Alguns grupos da instância não serão retornados (em alguns casos, não acontece com todas instâncias) 

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Olá @murilomontalvao , assim que for possível eu vou validar isso aqui, acredito que na wa-js eu já tenha resolvido, mas vou testar aqui
