### ISSUE TITLE
Implementar Envios de GIFF (como no mobile)

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#112]
Hoje no WhatsApp Web quando vc tenta enviar um GIFF ele envia como IMAGEM ESTÁTICA.

Só é possível enviar GIFF no celular, direto do App do WhatsApp.

Minha sugestão seria implementar uma função que envie GIFF no WPPConnect sem enviar como imagem estática.

**Comment by edgardmessias** [comment]
Para enviar como um GIF, o WhatsApp envia o GIF como um vídeo MP4 com uma marcação `isGif: true`.

**Comment by edgardmessias** [comment]
Released at v1.3.5
