### ISSUE TITLE
mobile logout token will not be auto deleted

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#113]
mobile logout token will not be auto deleted
status OPENING 
wppconnect version : 1.2.4

**Comment by Lucipher** [comment]
I  use  client.logout()  to logout , is there any other function to do it ?

**Comment by Lucipher** [comment]
useChrome: true  can resolve this issue

**Comment by edgardmessias** [comment]
@Lucipher , could you make a test with nightly release?

How to install: https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/installation.html

**Comment by edgardmessias** [comment]
Released https://github.com/wppconnect-team/wppconnect/releases/tag/v1.3.0

**Comment by Lucipher** [comment]
@edgardmessias  the issue happen agan
