### ISSUE TITLE
Function getAllChatsWithMessages, return [] in template_button_reply

### ISSUE THREAD

**Issue by wenioferraz** [wppconnect-team/wppconnect#1132]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** 1.13.1"
- **WA-JS version(s):** 2.2.2
- **Browser:** Chrome 2.2216.8
- **OS:** Ubuntu 22.04
- **Node version:** 14.18.2
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

Quando executo a função wpp.getAllChatsWithMessages(true) e a mesma tem o type "template_button_reply", ela retorna array vazio

[]

## Log Output
chats []

## Your Code

const chats = await client.getAllChatsWithMessages(true);

        console.log(chats)

**Comment by edgardmessias** [comment]
Fiz os testes e não consegui reproduzir
