### ISSUE TITLE
Método deleteMessage, não apaga na MD.

### ISSUE THREAD

**Issue by megustalol** [wppconnect-team/wppconnect#1151]
## Description
A função deleteMessage não está apagando a mensagem enviada na MD, na versão que usa a conexão do celular como a principal apaga normalmente. (Uso atraves de comando respodendo a mensagem que eu queria apagar), como falei antes, não pega apenas na versão MD.
await client.deleteMessage(message.from, message.quotedMsgId, false).then((result)

## Environment

- **WPPConnect version(s):** 1.13.3
- **WA-JS version(s):** 2.4.1
- **Browser:** Chrome
- **OS:** Windows server 2012
- **Node version:** Node 16.14.0
- **WhatsApp version:** 2.2214.12
- **MultiDevice (BETA):** yes

**Comment by syifarahmat** [comment]
This is the same with my case: 
![image](https://user-images.githubusercontent.com/11779955/171425444-4546b10d-aaff-40f3-a2b8-dc645cb80b4e.png)

**Comment by edgardmessias** [comment]
https://github.com/wppconnect-team/wppconnect/releases/tag/v1.14.0
