### ISSUE TITLE
Qualidade terrível da imagem capturada do retorno em base64

### ISSUE THREAD

**Issue by Kyle0color** [wppconnect-team/wppconnect#1154]
## Description

Descrevi um problema ao tentar enviar um sticker usando o retorno da imagem base64 contida no message.quotedMsg.body.
Porém deu erro, então criei um issue separado anteriormente.
Entre tanto, tentei criar um arquivo usando esse Base64 contido no retorno message.quotedMsg.body e obtive êxito.
Mas ao enviar como sticker, percebi a péssima qualidade da imagem retornada, mesmo antes de eu transformar em arquivo já estava com qualidade péssima.

## Environment

WhatsApp WEB version: 2.2214.12
WA-JS version: 2.4.1

Nesta imagem pegue o retorno do message.quotedMsg.body e converti em imagem em um site, e já da para ver a péssima qualidade
![image](https://user-images.githubusercontent.com/30413199/171595642-b10529f5-d7a0-4899-9fa8-feb447e33360.png)

Mesmo assim, insisti em criar um sticker com ela, e realmente saiu com a qualidade ruim.
![image](https://user-images.githubusercontent.com/30413199/171595741-2dc1850c-35e7-4bda-9506-f6eddabb4c2b.png)

## CODE

```
require("fs").writeFile("imagem.png", message.quotedMsg.body, 'base64', async function (err) {

    await client.sendImageAsSticker(message.from, `./imagem.png`).then((result) => {
        console.log('Result: ', result); //return object success
    }).catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
    });
    return
});
```

**Comment by jtapeg** [comment]
Você não esta passando pela função de download da imagem completa eu acho, o base64 que vem junto com o json da imagem é assim mesmo, da uma olhada aqui https://wppconnect-team.github.io/wppconnect/classes/Whatsapp.html#downloadMedia

**Comment by Kyle0color** [comment]
Não vai, ja tentei isso tbm, tentei de tudo.

**Comment by edgardmessias** [comment]
@Kyle0color , o conteúdo que vem no body realmente é uma qualidade mais baixa, é da própria arquitetura do WhatsApp.

Para mensagens do tipo mídia, ou seja, que é arquivos, é necessário fazer download do conteúdo, com a função downloadMedia.

Verifique para mim por gentileza está sendo possível fazer download do sticker a partir do id da mensagem, no seu caso, o ID da mensagem do `message.quotedMsg`

**Comment by edgardmessias** [comment]
@Kyle0color , você não está usando a imagem real, e sim apenas a thumbnail que fica no body, você deve usar o downloadMedia para obter a imagem real
