### ISSUE TITLE
sendFileFromBase64 dont send files over 9Mb

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1164]
## Description

whatsapp can send video files to 16Mbytes

but when I send video file (mime video/quicktime) size 9Mb, 12Mb in code
const response = await client.sendFileFromBase64(chatId, base64String, filename, caption);

function  sendFileFromBase64  don't return any result

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** 1.14.0
- **WA-JS version(s):** 2.6.0
- **Browser:** Chrome 101
- **OS:** Ubuntu 20.04
- **Node version:** Node 16.14.2
- **WhatsApp version:** 2.2220.8
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
@antirek , could you provide some video for test? I tried to reproduce here, but without success

**Comment by antirek** [comment]
@edgardmessias 

I try send file 62a1b054197729c954451972.mp4 
before convert - 29.97 fps - send failed
after convert - 25 fps - send ok

source file https://dropmefiles.com/uNtQj 


more info about file:
sergey@sergey-pc:~//tmp$ ffmpeg -i 62a1b054197729c954451972.mp4 
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '62a1b054197729c954451972.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: isommp41mp42
    creation_time   : 2022-05-03T11:43:51.000000Z
  Duration: 00:01:02.73, start: 0.000000, bitrate: 1169 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 480x848, 1101 kb/s, SAR 1:1 DAR 30:53, 29.97 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2022-05-03T11:43:51.000000Z
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2022-05-03T11:43:51.000000Z
      handler_name    : Core Media Audio
At least one output file must be specified
sergey@sergey-pc:~//tmp$ ffmpeg -i 62a1b054197729c954451972
62a1b054197729c954451972.mp4                        62a1b054197729c954451972 (video-converter.com).mp4  
sergey@sergey-pc:~//tmp$ ffmpeg -i 62a1b054197729c954451972\ \(video-converter.com\).mp4 
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '62a1b054197729c954451972 (video-converter.com).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:01:02.80, start: 0.000000, bitrate: 1170 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 480x848 [SAR 1:1 DAR 30:53], 1099 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
At least one output file must be specified

**Comment by antirek** [comment]
command for convert
> ffmpeg -i input.mp4 -vcodec h264 -crf 25 -acodec aac -r 25 -b:a 64k output.mp4

**Comment by antirek** [comment]
And when I send for example https://filesamples.com/samples/video/mp4/sample_960x540.mp4 sample video with 39.97fps - also send ok ))) Mystery

**Comment by wenioferraz** [comment]
Mime type video/x-m4v, não é permitido também no whats

**Comment by antirek** [comment]
ok, now it is error InvalidMediaFileType ))

I don't understand how you detect that it video/x-m4v?  @wenioferraz if you detect it via ffmpeg please write options or command

I can convert files before sending to whatsapp, yeah

**Comment by antirek** [comment]
> mimetype 62a1b054197729c954451972.mp4 

returns  62a1b054197729c954451972.mp4: video/mp4

>  ffmpeg -h muxer=mp4 62a1b054197729c954451972.mp4 

also returns 
````Muxer mp4 [MP4 (MPEG-4 Part 14)]:
    Common extensions: mp4.
    Mime type: video/mp4.
    Default video codec: h264.
    Default audio codec: aac.
`````

**Comment by edgardmessias** [comment]
@antirek , I tried the file with WhatsApp desktop and it was send as document file instead of video.

Instead of ffmpeg command, run ffprobe to get file info: `ffprobe -hide_banner -i file.mp4`

**Comment by antirek** [comment]
@edgardmessias
ffprobe get output like here https://github.com/wppconnect-team/wppconnect/issues/1164#issuecomment-1154665021 without header

I saw difference here in my files
for 62a1b054197729c954451972.mp4
Metadata:   major_brand     : mp42

and for  62a1b054197729c954451972\ \(video-converter.com\).mp4 
Metadata:   major_brand     : isom

Ok, thanks for code with InvalidMediaFileType 

Via my wppconnect  instances users don't send so many files with incompatible video )) 
If I meet error for sending file - I try convert it and send again
