### ISSUE TITLE
Erro (no aparelho) ao enviar PDF com Botões: "Whatsapp parou de funcionar"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#1167]
## Description

Quando eu envio uma mensagem com PDF + Botões, o envio acontece normalmente. Porém, ao tentar abrir o Whatsapp no aparelho, tanto do remetente quanto do destinatário, aparece uma mensagem de erro dizendo que "o aplicativo Whatsapp parou de funcionar".

Após enviar ou receber uma mensagem com PDF + Botões, só é possível abrir o Whatsapp no aparelho depois de desativar o acesso a internet e excluir as mensagens. Eu fiz uma demonstração em vídeo explicando com detalhes o problema:

https://youtu.be/06UsC5RVBWQ

## Environment

- **WPPConnect version(s):** 1.14.1
- **WA-JS version(s):** 2.6.0
- **Browser:** Chrome XX
- **OS:** Windows 10
- **Node version:** Node 14.15.4
- **WhatsApp version:** 2.2220.8
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Envie uma mensagem com método "sendFile" passando como parâmetros o URL de um documento em PDF + Botões;
2. Tente abrir o Whatsapp no aparelho do remetente ou do destinatário;
3. Para conseguir abrir no aparelho, desligue o acesso à internet e exclua a mensagem com botões;
4. Ative novamente o acesso a internet e tente abrir novamente o Whatsapp.

## Your Code

```
 json = await client.sendFile(to_whatsapp, url_midia, {
        useTemplateButtons: true,
        createChat: true,
        title: body,
        buttons: [
            {
                url: url1,
                text: botao_url1
            },
          ],
          footer: footer
    });
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/35501007/173079994-364cc492-832e-4b19-b1c9-65596145ed64.png)

**Comment by icleitoncosta** [comment]
Devido a mudanças no whatsapp não será mais possível o envio de botões
