### ISSUE TITLE
downloadMedia method return code: 'media_not_found'

### ISSUE THREAD

**Issue by downdawn** [wppconnect-team/wppconnect#1192]
## Environment

- **WPPConnect version(s):^1.14.4
- **WA-JS version(s):2.7.3
- **Browser:** Chrome 101
- **OS:** Windows 10
- **Node version:v16.15.1
- **WhatsApp version:2.2220.8
- **MultiDevice (BETA):yes

'downloadMedia' doesn't work.

return code: 'media_not_found'

![image](https://user-images.githubusercontent.com/41266749/174991441-54d217bd-e884-4a3c-b340-ad9d3cd506be.png)

type is unknown, is it updated?

**Comment by edgardmessias** [comment]
This is not a bug, for some reason, the file is not more available to download.
