### ISSUE TITLE
On incoming call peerJid with :

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1206]
## Description

On incoming call I began receive peerJid with ":" sometimes

usually I receive peerJid without :, like chatId XXXXXXXXXXX@c.us 

I dont know is it bug or new behavior because multidevice and jid is id of multidevice client

`````
incoming call {
   call: {
     id: '7E3BE58C9A9D2A9450491C98A9E0AAE7',
     peerJid: 'XXXXXXXXXXX:1@c.us',
     offerTime: 1656511630,
     isVideo: false,
     isGroup: false,
     canHandleLocally: false,
     outgoing: false,
     webClientShouldHandle: false,
     participants: []
   }
}

`````
## Environment

- **WPPConnect version(s):** 1.14.4
- **WA-JS version(s):** 2.8.0
- **Browser:** Chrome 102
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2220.8
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
@antirek , when you receive a peerJid with ":", it's mean a WhatsApp Desktop call, each device connected has a number, only the phone does not have the id

**Comment by antirek** [comment]
ok, it's mean normal behavior
