### ISSUE TITLE
SendButtons don't exist

### ISSUE THREAD

**Issue by shirser121** [wppconnect-team/wppconnect#1207]
I try to send buttons, but it's look like messageTamplate don't exist, so Store.builders not work at all.

**Comment by shirser121** [comment]
"Cannot read properties of null (reading 'TemplateMessage')"

**Comment by antirek** [comment]
what are versions used? wppconnect, wa-js, whatsapp-web? your info isn't enough

**Comment by edgardmessias** [comment]
See [sendText](https://wppconnect.io/wppconnect/classes/Whatsapp.html#sendText)
