### ISSUE TITLE
Falha ao escanear o QRcode base64

### ISSUE THREAD

**Issue by allanlisboa** [wppconnect-team/wppconnect#1222]
Estou obtendo falhas ao tentar escanear o Qrcode gerado em base64. Pelo terminal consigo escanear normalmente.

![WhatsApp Image 2022-07-16 at 18 09 32](https://user-images.githubusercontent.com/37181884/179372009-1bbbcaf2-fab7-49f3-bd22-f615afb238b7.jpeg)

**Comment by AlanMartines** [comment]
Estou conseguindo escanear novamente o Qrcode gerado via base64.

Qual é a versão que vc está usando do WhatsApp web?
