### ISSUE TITLE
VPS Ubunto Server error: failed to launch the browser process puppeteer

### ISSUE THREAD

**Issue by RapidMesck** [wppconnect-team/wppconnect#1225]
Eu estou tentando iniciar um app utiliando WPPConnect em uma VPS Ubunto Server porem quando inicio a aplicacao retorna no console este erro: 

error: failed to launch the browser process puppeteer

tentei usar metados que vi porem o erro persiste

Metado que tentei:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    executablePath: '/usr/bin/chromium-browser',
});
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

**Comment by AlanMartines** [comment]
Instala o Google Chrome e seta o parâmetro useChrome como true.
