### ISSUE TITLE
WPP is not defined

### ISSUE THREAD

**Issue by Khaldoun-Baz** [wppconnect-team/wppconnect#1233]
Hello
when I m building WAPI and get from 'dst' folder and injected on the browser I' m getting the below error
```
Uncaught ReferenceError: WPP is not defined
    at _loop (<anonymous>:7419:7)
    at ./wapi.js (<anonymous>:7428:65)
    at __webpack_require__ (<anonymous>:8530:42)
    at <anonymous>:8583:37
    at <anonymous>:8585:12
```
Anyone can help on that ?

**Comment by edgardmessias** [comment]
Hi, could you explain better? You must inject @wppconnect/wa-js before wapi

**Comment by Khaldoun-Baz** [comment]
Yes that it... 
solved thanks

**Comment by masterweb1125** [comment]
HI, nice to meet you.

пн, 25 июл. 2022 г. в 20:36, Khaldoun Baz ***@***.***>:

**Comment by masterweb1125** [comment]
Do you have skype?


пн, 25 июл. 2022 г. в 20:49, master web ***@***.***>:
