### ISSUE TITLE
sendLocation() is not working

### ISSUE THREAD

**Issue by hardik323** [wppconnect-team/wppconnect#1237]
I am using following code to send location, but it is not working.
  await client.sendLocation('91xxxxxxxxxx@c.us', {lat: '37.090240', lng:'-95.712891'})

**Comment by hardik323** [comment]
Even I am sending address, will also not work.

**Comment by etc-tiago** [comment]
More details about the problem.
Response:

```json
{
  "ack": 1,
  "id": "true_0000000000@c.us_xxxxxxxxxxxxxxxxxxxx",
  "sendMsgResult": "OK"
}
```

On headless:false

<img width="341" alt="Captura de Tela 2022-07-29 às 18 26 48" src="https://user-images.githubusercontent.com/33164463/181845283-b500491a-fc54-444c-936b-07c83258dee1.png">

**Comment by etc-tiago** [comment]
In my investigation, WhatsApp web no longer shows the location send button... could this be the reason for the problem?

**Comment by edgardmessias** [comment]
I fixed it at wa-js, so, wait for wa-js update

**Comment by edgardmessias** [comment]
Please, update the wa-js to [2.9.0](https://github.com/wppconnect-team/wa-js/releases/tag/v2.9.0)

Command: `npm install @wppconnect/wa-js@latest`
