### ISSUE TITLE
List Menu não funciona para usuários que estão na versão Beta do WhatsApp

### ISSUE THREAD

**Issue by Kyle0color** [wppconnect-team/wppconnect#1242]
Versão Beta 2.22.17.6 não funciona List Menu

Cliente solicita a mensagem, Bot envia, Mas não aparece para o cliente a mensagem que possuem um List Menu.

Enquanto isso, orientei os mesmos, para sairem da versão Beta, indo na playstore, saindo dela e reinstalando, que ai sim recebem normal.

![image](https://user-images.githubusercontent.com/30413199/182047839-ef9c3017-e543-43a8-b1cb-a3318b6823be.png)

**Comment by icleitoncosta** [comment]
Opa, poderia fazer um teste nas últimas versões beta?

**Comment by Kyle0color** [comment]
Este problema, retornou, o "Bot" usando a Lib "wppconnect" para enviar um listmenu. Embora olhando pelo zap do bot, ele enviou com sucesso, o destinatário diz que não recebeu.
Fica meio que invisivel para o destinatário as mensagens que contem o ListMenu.

A solução da ultima vez que houve isso em Dev 15 2022, foi alterar a vesão do WhatsApp web no Create.

Teriam algo a sugerir meus consagrados? <3

**Comment by icleitoncosta** [comment]
> Este problema, retornou, o "Bot" usando a Lib "wppconnect" para enviar um listmenu. Embora olhando pelo zap do bot, ele enviou com sucesso, o destinatário diz que não recebeu.
> 
> Fica meio que invisivel para o destinatário as mensagens que contem o ListMenu.
> 
> 
> 
> A solução da ultima vez que houve isso em Dev 15 2022, foi alterar a vesão do WhatsApp web no Create.
> 
> 
> 
> Teriam algo a sugerir meus consagrados? <3

Opa, infelizmente nas últimas versões o WhatsApp tem alterado a forma como envia o modelo dessas mensagens, futuramente irão parar em todos os dispositivos, e não há uma solução.

**Comment by Kyle0color** [comment]
> > Este problema, retornou, o "Bot" usando a Lib "wppconnect" para enviar um listmenu. Embora olhando pelo zap do bot, ele enviou com sucesso, o destinatário diz que não recebeu.
> > Fica meio que invisivel para o destinatário as mensagens que contem o ListMenu.
> > A solução da ultima vez que houve isso em Dev 15 2022, foi alterar a vesão do WhatsApp web no Create.
> > Teriam algo a sugerir meus consagrados? <3
> 
> Opa, infelizmente nas últimas versões o WhatsApp tem alterado a forma como envia o modelo dessas mensagens, futuramente irão parar em todos os dispositivos, e não há uma solução.

Entendi amigo, então independente da Lib, todas vão passar por isso, e mais nenhuma terá a opção de enviar ListMenu correto?

**Comment by edgardmessias** [comment]
Infelizmente a Meta bloqueou esse recurso, não permitindo mais o envio.
