### ISSUE TITLE
Button responden

### ISSUE THREAD

**Issue by cantiir2** [wppconnect-team/wppconnect#1243]
## Description

[ how to get setting button response like baileys ? I tried it didn't work ]

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
@cantiir2 , what you tried? Could you fill the enviroment section?

**Comment by masterweb1125** [comment]
Hi

пн, 1 авг. 2022 г. в 20:04, Edgard Lorraine Messias <
***@***.***>:

**Comment by cantiir2** [comment]
> @cantiir2 , what you tried? Could you fill the enviroment section?

 I tried the button to respond, can't, can you give me a solution? I tried on baileys it works if we click the button the bot will answer it
