### ISSUE TITLE
START SERVER IN LINUX

### ISSUE THREAD

**Issue by LuizVeloso10** [wppconnect-team/wppconnect#1247]
nfo: [sessionName:browser] Using browser folder '/home/gesfood/public_html/bot-test/tokens/sessionName'
info: [sessionName:browser] Initializing browser...
error: [sessionName:browser] Error no open browser
error: [sessionName:browser] Failed to launch the browser process!

Alguém poderia me ajudar com essa questão, estou tentando subir em um server linux

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://wppconnect.io/wppconnect/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by fredEbho** [comment]
I have the same issue, please help!

**Comment by edgardmessias** [comment]
Please, install the Chrome browser in the linux before starting the server
