### ISSUE TITLE
Send button message not delivering

### ISSUE THREAD

**Issue by fredEbho** [wppconnect-team/wppconnect#1249]
await client.sendMessageOptions(msg.from, 'teste', {
          title: 'CALÇA JEN FEMININA',
          footer: 'Escolha uma opção abaixo',
          isDynamicReplyButtonsMsg: true,
          dynamicReplyButtons: [
            {
              buttonId: 'idSim',
              buttonText: {
                displayText: 'SIM',
              },
              type: 1,
            },
            {
              buttonId: 'idNao',
              buttonText: {
                displayText: 'NÃO',
              },
<img width="418" alt="Screenshot 2022-08-03 at 19 19 03" src="https://user-images.githubusercontent.com/35952541/182680484-8bcabc3d-02db-4f77-909e-fb8f42ddc7ee.png">

              type: 1,
            },
          ],
        });

Send button is not delivering. WhatsApp version - 2.2228.4

**Comment by edgardmessias** [comment]
This way doesn't work anymore, please look the example at [sendText](https://wppconnect.io/wppconnect/classes/Whatsapp.html#sendText)

**Comment by masterweb1125** [comment]
Hi


чт, 4 авг. 2022 г. в 03:44, Edgard Lorraine Messias <
***@***.***>:

**Comment by masterweb1125** [comment]
Are you there?


чт, 4 авг. 2022 г. в 03:49, master web ***@***.***>:

**Comment by masterweb1125** [comment]
I need sending interactive message in wppconnect.


чт, 4 авг. 2022 г. в 03:49, master web ***@***.***>:

**Comment by fredEbho** [comment]
> This way doesn't work anymore, please look the example at [sendText](https://wppconnect.io/wppconnect/classes/Whatsapp.html#sendText)

Thanks, @edgardmessias! But there is another issue when I send it the way you pointed me to via sendText, the chat with that contact crashes WhatsApp.
