### ISSUE TITLE
Status Not been sent After the 1st One

### ISSUE THREAD

**Issue by fredEbho** [wppconnect-team/wppconnect#1257]
Great work so far man, this is by far the best & most feature-rich WhatsApp Javascript package out there!

I have a small issue though, after sending any(text, image, video) status the first time to a phone number, for the next 20-30 minutes, you can't send another status to that number. Please help, it's urgent.

<img width="718" alt="Screenshot 2022-08-06 at 09 14 17" src="https://user-images.githubusercontent.com/35952541/183240777-e252baa3-c126-41c9-9c67-1ac3e1f77fc2.png">

Above is the number of statuses I uploaded, below is the number of status that actually got published.
![WhatsApp Image 2022-08-06 at 9 16 07 AM](https://user-images.githubusercontent.com/35952541/183240862-ee469693-6903-4f88-9756-8c703d264865.jpeg)

**Comment by vphelipe** [comment]
I noticed this problem too. It is only possible to send again if you refresh the page, but then it does not load the sent Statuses anymore

**Comment by icleitoncosta** [comment]
Hello, can you test in the latest version?
