### ISSUE TITLE
WhatsApp app sendText with buttons cause crashed in mobile

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1260]
## Description

sendText with buttons is successfully sent and received.
But if user click reply button, the WhatsApp in mobile app crashed (web WhatsApp is fine to show)

## Environment

- **WPPConnect version(s):** 1.16.0
- **WA-JS version(s):** 2.10.0
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node 16.7
- **WhatsApp version:** 2.22.16.75
- **MultiDevice (BETA):** yes (DEFAULT)

## Steps to Reproduce

1. Send text with button to user
2. User click the button option

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
waClient.sendText(
	'someone_mobilenumber',
	'test message with button', {
	useTemplateButtons: true, // False for legacy
	buttons: [
     {
       id: '1',
       text: 'test1'
     },
     {
       id: '2',
       text: 'test2'
     }
   ],
});
```

## Additional context / Screenshot

![2022-08-07 21_51_49-WhatsApp](https://user-images.githubusercontent.com/5172626/183294123-84d000df-529e-4e9c-a214-0b095044c029.png)

**Comment by roysG** [comment]
In case you will change the "useTemplateButtons" to false, it will work.
But in case you will want to user in other options likes website and call, then you will have to change the useTemplateButtons  to true and then the app is creash in mobile.

**Comment by momokang** [comment]
> In case you will change the "useTemplateButtons" to false, it will work. But in case you will want to user in other options likes website and call, then you will have to change the useTemplateButtons to true and then the app is creash in mobile.

Hi, this is enough to solve my needs. Thanks
