### ISSUE TITLE
Qrcode not Generate

### ISSUE THREAD

**Issue by Akash-Rathore** [wppconnect-team/wppconnect#1267]
in my case multi login more then 5 user login if i am doing 6 then qrcode not generate it's show this
info:     [join_6:client] WhatsApp WEB version: 2.2230.9
info:     [join_6:client] WA-JS version: 2.10.0
info:     [join_6:client] WhatsApp WEB version: 2.2228.14
info:     [join_6:client] WA-JS version: 2.10.0

**Comment by edgardmessias** [comment]
@Akash-Rathore , could you share your code?

**Comment by Akash-Rathore** [comment]
I am using wppconnect server code only
