### ISSUE TITLE
Envio de botões parou de funcionar no Iphone

### ISSUE THREAD

**Issue by allanlisboa** [wppconnect-team/wppconnect#1268]
## Description
O envio das mensagens com utilizando os botões parou de funcionar no Iphone. Funciona bem no whatsapp web e no android! Na versão 1.15 da wpp estava funcionando até ontem, mas hoje já não envia mais mensagens com botão para Iphone.

## Environment

WPPConnect version(s): 1.16.1
WA-JS version(s): 2.10.1
Browser: Chrome XX / Chromium XX
OS: Windows X / OSX X.Y.Z
Node version: Node 16.7
WhatsApp version: 2.2220.8
MultiDevice (BETA): yes (DEFAULT)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code
client.sendText('<number>@c.us', 'WPPConnect message with buttons', {
   useTemplateButtons: true, // False for legacy
   buttons: [
     {
       url: 'https://wppconnect.io/',
       text: 'WPPConnect Site'
     },
     {
       phoneNumber: '+55 11 22334455',
       text: 'Call me'
     },
     {
       id: 'your custom id 1',
       text: 'Some text'
     },
     {
       id: 'another id 2',
       text: 'Another text'
     }
   ],
   title: 'Title text' // Optional
   footer: 'Footer text' // Optional
});
```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

VERSÃO 1.16 (A mensagem é enviada mas corrompida)

![WhatsApp Image 2022-08-10 at 09 49 59](https://user-images.githubusercontent.com/37181884/183906287-e9f62f42-0f32-42a8-8682-cc1b090c2e32.jpeg)

![Captura de Tela 2022-08-10 às 09 54 39](https://user-images.githubusercontent.com/37181884/183906383-89400c6c-7f87-4fa7-80b0-2b06c7b88c3d.png)

VERSÃO 1.15 (A mensagem não é enviada)

![photo1660135212](https://user-images.githubusercontent.com/37181884/183907337-b7cda069-7d4c-4487-8b22-b6aca58d488e.jpeg)

![Captura de Tela 2022-08-10 às 09 40 23](https://user-images.githubusercontent.com/37181884/183907402-31b489bc-9f6b-4385-b9f8-c6dfc8e6bfb0.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Atualize para a última versão do projeto e use a opção useTemplateButtons: false.

Infelizmente desse método não é possível enviar url e phoneNumber

**Comment by allanlisboa** [comment]
Fia as alterações mais ainda assim não funciona! 

![WhatsApp Image 2022-08-10 at 13 03 48](https://user-images.githubusercontent.com/37181884/183958186-6389a3fa-f82a-43de-96db-60a6b968c90c.jpeg)
.

**Comment by edgardmessias** [comment]
Poderia mostrar o código?

Está com WA-JS : 2.10.1?

**Comment by allanlisboa** [comment]
![Captura de Tela 2022-08-10 às 13 21 08](https://user-images.githubusercontent.com/37181884/183962003-17eebec7-b43b-48a7-bb80-00e0959aac22.png)

![Captura de Tela 2022-08-10 às 13 21 38](https://user-images.githubusercontent.com/37181884/183962107-9036ad98-ab26-44b6-b5c5-c551a29bb54c.png)

**Comment by allanlisboa** [comment]
Acabo de identificar que este problema ocorre apenas no Whatsapp normal do Iphone! No whatsapp business aparece os botões

**Comment by hardik323** [comment]
Alguém tem solução para isso?

**Comment by hardik323** [comment]
quero enviar url

**Comment by edgardmessias** [comment]
No momento pode desistir, pois o formato de template está chegando apenas no Android.

Vamos ter que esperar o desenrolar para ver o que fazer no iphone.

> quero enviar url

**Comment by allanlisboa** [comment]
Achei uma combinação para os botões serem enviados. 

Tem que passar estes dois options dessa forma: 

useTemplateButtons: false
createChat: true

![Captura de Tela 2022-08-28 às 11 51 05](https://user-images.githubusercontent.com/37181884/187080204-7ef127d9-394f-4d68-9cc7-1488e09052ee.png)
