### ISSUE TITLE
sendImageAsSticker with base64 failed

### ISSUE THREAD

**Issue by FerryAr** [wppconnect-team/wppconnect#1278]
## Description
SendImageAsSticker with base64 fail although the base64 is valid

## Environment

- **WPPConnect version(s):** 1.16.1
- **WA-JS version(s):** 2.10.1
- **Browser:** Chromium 104
- **OS:** Manjaro Linux x64
- **Node version:** Node 18.7.0
- **WhatsApp version:** -
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. get message with onMessage()
2. decrypt message with decryptFile()
3.  change buffer callback to base64 with Buffer.from(buffer).toString("base64")
4.  Send sticker with sendImageAsSticker()

## Your Code

```
client.onMessage(async (message) => {
    if(message.isMedia && message.caption === '.sticker') {
        await client.decryptFile(message).then(async (buffer) => {
            await client.sendImageAsSticker(message.from, Buffer.from(buffer).toString("base64");
        });
    }
}
```

**Comment by edgardmessias** [comment]
You must pass `data:image/webp;base64,` before of content
