### ISSUE TITLE
One if my session is fail to connect to whatsapp after 2 days working

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1281]
## Description

I am using pm2 in ubuntu and one of my session suddenly stop to connect after a 2 days working.
In the logs i get the last message i get:

info:
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   _       ______  ____  ______                            __
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     Checking for updates
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | serverId: callCenterCaller_3f3be61d543e45921839ad537d6b0758
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     You're up to date
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     [callCenterCaller_3f3be61d543e45921839ad537d6b0758:browser] Using browser folder './tokens/callCenterCaller_3f3be61d543e45921839ad537d6b0758'
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     [callCenterCaller_3f3be61d543e45921839ad537d6b0758:browser] Initializing browser...
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | leftSecondFromStoppedLoop 1.384
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     [callCenterCaller_3f3be61d543e45921839ad537d6b0758:client] Initializing...
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | leftSecondFromStoppedLoop 2.385
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | leftSecondFromStoppedLoop 3.385
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | leftSecondFromStoppedLoop 4.388
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | leftSecondFromStoppedLoop 5.388
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     [callCenterCaller_3f3be61d543e45921839ad537d6b0758:client] WhatsApp WEB version: 2.2220.8
83|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | info:     [callCenterCaller_3f3be61d543e45921839ad537d6b0758:client] WA-JS version: 2.10.1

  "LOADING_SCREEN 0 Connecting… " 

But it stuck forever on this state. :   "LOADING_SCREEN 0 Connecting… "

**Comment by roysG** [comment]
This is addittion errors i get:

86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | url: https://api.msgto.io/whatsapp/updatePhoneSentPost p: {"msgId":"cce3ec5bf555cb404afd11621e39d041","phone":"037220319"} object
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | Error when sending image:  Error [InvalidStateError]: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at /root/msgto/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at step (/root/msgto/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at Object.next (/root/msgto/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at fulfilled (/root/msgto/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at runMicrotasks (<anonymous>)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | JS Stack: Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at we.create (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:40156)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at he (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:21614)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at ge._trans (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32540)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at ge._idbstore (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32615)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at get (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32880)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at h.get (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:803705)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:814363
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at t.default._read (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:813372)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at t.default.get (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:814351)
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:50:99792 {
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   _e: {
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     name: 'Error',
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     message: '',
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     stack: 'Error\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at z (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:5592)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at new r (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:7120)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at Ne.rejectionMapper (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:58246)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at Ue (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:11283)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at je (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:11887)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:10558\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at De (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:10916)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at new Ne (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:10417)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at Ne.n (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:10536)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at get (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:33008)'
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   },
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   inner: {
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     name: 'InvalidStateError',
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     message: "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.",
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |     stack: "Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n" +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at we.create (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:40156)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at he (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:21614)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at ge._trans (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32540)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at ge._idbstore (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32615)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at get (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:7:32880)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at h.get (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:803705)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:814363\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at t.default._read (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:813372)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at t.default.get (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:71:814351)\n' +
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |       '    at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:50:99792'
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  |   }
86|callCenterCaller_3f3be61d543e45921839ad537d6b0758  | }

**Comment by roysG** [comment]
Any update?

**Comment by icleitoncosta** [comment]
can you reach the browser memory consumption?

**Comment by roysG** [comment]
Please tell me what is the command for doing it

**Comment by roysG** [comment]
I am using in server of 8 cpu and 16GB, so i do not think is connected to memory

**Comment by roysG** [comment]
After i get the error, the session is corrupted and i have to scan again

**Comment by icleitoncosta** [comment]
you can use htop, supervise the use of resources and when the error occurs check the peak memory that was used.

tonight I'll be trying to reproduce this error to help you, it's an error in chrome itself, I believe it's something related

**Comment by roysG** [comment]
I added these BrowserArgs:

  '--js-flags="--max-old-space-size=1024"',
                '--disable-dev-shm-usage',
                //'--proxy-server=' + newProxyUrl,
                '--no-sandbox',

                '--unlimited-storage',
                '--full-memory-crash-report',
                '--force-gpu-mem-available-mb',
                '--js-flags=--expose-gc',

                '--log-level=3',
                '--no-treekill',
                '--no-default-browser-check',
                '--disable-site-isolation-trials',
                '--no-experiments',
                '--ignore-gpu-blacklist',
                '--ignore-certificate-errors',
                '--ignore-certificate-errors-spki-list',
                '--disable-gpu',
                '--disable-extensions',
                '--disable-default-apps',
                '--enable-features=NetworkService',
                '--disable-setuid-sandbox',
                '--no-sandbox',
                '--disable-webgl',
                '--disable-infobars',
                '--window-position=0,0',
                '--ignore-certifcate-errors',
                '--ignore-certifcate-espki-list',
                '--disable-threaded-animation',
                '--disable-threaded-scrolling',
                '--disable-in-process-stack-traces',
                '--disable-histogram-customizer',
                '--disable-gl-extensions',
                '--disable-composited-antialiasing',
                '--disable-canvas-aa',
                '--disable-3d-apis',
                '--disable-accelerated-2d-canvas',
                '--disable-accelerated-jpeg-decoding',
                '--disable-accelerated-mjpeg-decode',
                '--disable-app-list-dismiss-on-blur',
                '--disable-accelerated-video-decode',
                '--disable-dev-shm-usage'

Now i do not see this error,  BUT...

Sometimes with no understand reason, i get messages like the browser try to start..

LOADING_SCREEN...0

LOADING_SCREEN...100

But it stack and nothing is happen. until i force remove the folder of the session and then needs to scan again..

**Comment by roysG** [comment]
any update?

**Comment by momokang** [comment]
I have the same issue, did you solve it?

**Comment by jgornati** [comment]
> I am making some changes in the lib, but not 100% tested
Any update or any ideas to try?
