### ISSUE TITLE
Sending button not working on ios device

### ISSUE THREAD

**Issue by hardik323** [wppconnect-team/wppconnect#1288]
I am tryting to send button with url-actions using following code, which not working in ios device:
// Simple message
client.sendText('<number>@c.us', 'A simple message');

// With buttons
client.sendText('<number>@c.us', 'WPPConnect message with buttons', {
   useTemplateButtons: true, // False for legacy
   buttons: [
     {
       url: 'https://wppconnect.io/',
       text: 'WPPConnect Site'
     },
     {
       phoneNumber: '+55 11 22334455',
       text: 'Call me'
     },
     {
       id: 'your custom id 1',
       text: 'Some text'
     },
     {
       id: 'another id 2',
       text: 'Another text'
     }
   ],
   title: 'Title text' // Optional
   footer: 'Footer text' // Optional
});

![image](https://user-images.githubusercontent.com/56799528/185015720-a35becc5-df95-45c6-a0df-032bca2b6077.png)

**Comment by vishwajit76** [comment]
Same here

**Comment by adrianokelvio** [comment]
android or ios?

The templete buttons are only working on android for now

use buttons simple is working on android and iphones


client.sendText('@c.us', 'WPPConnect message with buttons', {
buttons: [
{
id: 'your custom id 1',
text: 'Some text1'
},
{
id: 'another id 2',
text: 'Another text2'
},
{
id: 'another id 3',
text: 'Another text3'
}
],
title: 'Title text' // Optional
footer: 'Footer text' // Optional
});

**Comment by momokang** [comment]
I solved mine by set useTemplateButtons: false

**Comment by Sau64** [comment]
But useTemplateButtons: false does not work with urls buttons, right?

**Comment by momokang** [comment]
Yes, url and phone is not working

**Comment by vishwajit76** [comment]
Any update?

**Comment by hardik323** [comment]
useTemplateButtons: false 
works in android properly.
On ios, sometimes it does not send the message.

**Comment by Sau64** [comment]
There has been some advance in this matter in the following project.

https://github.com/adiwajshing/Baileys/issues/2006

**Comment by edgardmessias** [comment]
The Whatsapp made some changes to block "template buttons", that is used when `useTemplateButtons` is true.

When `useTemplateButtons` is false, "reply buttons" are used, but there are nothing to do at moment with IOS

**Comment by ilias1403** [comment]
hi anyone have issue with IOS and how to fix it?

**Comment by edgardmessias** [comment]
There are nothing to do at moment

**Comment by Sau64** [comment]
it's working again with latest ios app version

**Comment by Sau64** [comment]
Templatebuttons still not showing up with app closed or in background but does work with the app open.
