### ISSUE TITLE
Suddenly i get message, "make sure you have internet connection"

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1298]
## Description

Suddenly i get message, "make sure you have internet connection"

## Environment

- **WPPConnect version(s):** Latest
- **WA-JS version(s):** Latest
- **Browser:** Chrome 
- **OS:** Ununtu 20
- **Node version:** 16
- **MultiDevice (BETA):** yes

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Scree
![Screen Shot 2022-08-26 at 17 22 44](https://user-images.githubusercontent.com/7311802/186926080-9fb3e526-fc40-469a-bd26-40bc517f1034.png)

**Comment by momokang** [comment]
But it's not related to wpp right?

**Comment by edgardmessias** [comment]
Still happening?

Reopen with more details
