### ISSUE TITLE
Is there anyway I can run the project in dev mode? 

### ISSUE THREAD

**Issue by jugsbm** [wppconnect-team/wppconnect#1299]
Is there anyway I can run this project in dev mode? 

'npm run build' creates the build but it won't let me debug the unminified version

I would like to debug the flow and understand better as to how this library works?

Appreciate some advice.

Thanks
Jugs

**Comment by icleitoncosta** [comment]
Hello, to better understand how the project works, I suggest going straight to the main part of it, which is WppConnect-team/wa-js so you can open the browser and test the functions directly in the console.
