### ISSUE TITLE
Adicionar nova função para o grupo - adicionar descrição e bloquear para somente o administrador conseguir alterar o conteúdo

### ISSUE THREAD

**Issue by ikarofsouza** [wppconnect-team/wppconnect#131]
Olá gostaria de solicitar o recurso de Adicionar nova função para o grupo - adicionar descrição e bloquear para somente o administrador conseguir alterar o conteúdo.

Configurações do grupo -> Editar dados do grupo -> Escolha quem pode mudar o nome, imagem e a descrição desse grupo: Participantes / Admins.

------

Hello I would like to request the ability to add a new role for the group - add description and block so that only the administrator can change the content.

Group settings -> Edit group data -> Choose who can change the name, image and description of this group: Participants / Admins.

**Comment by ikarofsouza** [comment]
![Screenshot2](https://user-images.githubusercontent.com/48399495/115150772-c5754180-a061-11eb-8bd9-e1dbb7566bb1.png)
![Screenshot3](https://user-images.githubusercontent.com/48399495/115150774-c6a66e80-a061-11eb-8fff-e5aa682d35e7.jpg)
![Screenshot4](https://user-images.githubusercontent.com/48399495/115150775-c6a66e80-a061-11eb-9cf5-07a07ea811a4.jpg)
![Screenshot](https://user-images.githubusercontent.com/48399495/115150776-c73f0500-a061-11eb-8fbf-13418dd31473.png)

**Comment by edgardmessias** [comment]
Released: https://github.com/wppconnect-team/wppconnect/releases/tag/v1.3.1
