### ISSUE TITLE
Bug when send animated sticker using sendImageAsStickerGif

### ISSUE THREAD

**Issue by LoL-Human** [wppconnect-team/wppconnect#1314]
## Description

I want to send a gif as a sticker with sendImageAsStickerGif, but don't work properly

## Environment

- **WPPConnect version(s):** 2.11.0
- **WA-JS version(s):** 2.2220.8
- **Browser:** Chrome 104.0.5112.102
- **OS:** Windows 11
- **Node version:** Node 16.x
- **WhatsApp version:** 2.22.10.73
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
Nothing
```

## Your Code

```js
client.sendImageAsStickerGif(msg.from, './tests/test.gif')
```

## Additional context / Screenshot

Nothing

**Comment by edgardmessias** [comment]
This was fixed with `@wppconnect/wa-js >= v2.15.0`
