### ISSUE TITLE
getProfilePicFromServer is still getting URL signature expired profile image

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1315]
## Description

getAllChats will return expired URL signature of user profile image and try to getProfilePicFromServer is still the same

## Environment

- **WPPConnect version(s):** 1.16.1
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome 105
- **OS:** Windows 10
- **Node version:** Node 16.7.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Try to getAllChats and some old chat will have expired URL signature of user profile image
2. Try getProfilePicFromServer with chat id and still the same

## Log Output

Example
https://pps.whatsapp.net/v/t61.24694-24/297753769_138695678575262_2623292811728518275_n.jpg?ccb=11-4&oh=01_AVyQU3CvoGm1dMW3Ph6JYpKRsZsEyCwObIvXIhtezkA2Tg&oe=630F8F9D

## Your Code

```
waClient.getProfilePicFromServer(req.query.from)
		.then(function (profilePicThumbObj) {
			return profilePicThumbObj;
		});
```

## Additional context / Screenshot

URL signature expired

**Comment by icleitoncosta** [comment]
I tried to reproduce this error but was unsuccessful. Could you test on the latest version?
