### ISSUE TITLE
difference of the library with the most popularea venom, sulla.

### ISSUE THREAD

**Issue by GlauberF** [wppconnect-team/wppconnect#132]
what is the difference of the library taking into account venom, sulla.

I also tested it (https://github.com/wppconnect-team/wppconnect-server and https://github.com/wppconnect-team/wppconnect-frontend), I realized that it does not bring any recent conversations, is it possible to bring it?

**Comment by edgardmessias** [comment]
Summary: All are forks of sulla.

I made a lot of contributions to venom-bot, but after some discussions, I started a clean fork of venom-bot

You can check my contributions here: https://github.com/orkestral/venom/commits?author=edgardmessias and  https://github.com/orkestral/venom/graphs/contributors

Could you provide some steps to reproduce here the problem?

Ps.: Sim, sou do Brasil, se quiser, chame agente no grupo: https://chat.whatsapp.com/C1ChjyShl5cA7KvmtecF3L
