### ISSUE TITLE
getMessages unable to get older messages

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1320]
## Description

getMessages will only return some to little messages, even set GetMessagesParam count to 50.

## Environment

- **WPPConnect version(s):** 1.16.1
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium 105
- **OS:** Windows 10
- **Node version:** Node 16.7.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. getMessages get few messages only
2. getMessages  send in GetMessagesParam id with direction before still get empty result

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
waClient.getMessages(req.query.from, {
		id: req.query.id,
		direction: 'before',
	})
	.then(function (allMsg) {			
		res.json(output);
	});
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
This problem is caused by WhatsApp sincronization, try to wait more time before calling the function.

On Multidevice, only stored messages are fetched, instead of legacy that fetch from smartphone.

**Comment by roysG** [comment]
@edgardmessias 
So what is the solution for loading older messages?
All the others function seems to be deprecated and will stop working somewhere in the future..

**Comment by edgardmessias** [comment]
@roysG , there are no way, you only can fetch sincronized messages
