### ISSUE TITLE
getAllChats unable to get WhatsApp business chats

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1321]
## Description

getAllChats unable to get WhatsApp business chats

## Environment

- **WPPConnect version(s):** 1.16.1
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium 105
- **OS:** Windows 10
- **Node version:** Node 16.7.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. getAllChats and return undefined

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
waClient.getAllChats()
		.then(function (chats) {
			console.log(chats); // undefined
		});
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by momokang** [comment]
getAllChatsWithMessages works with WhatsApp business, but the output is different with getChats, I will suggest to use waClient.getChatById after fetches:

waClient.getAllChatsWithMessages()
		.then(function (chatsWithMessages) {
			// run waClient.getChatById
		});

**Comment by roysG** [comment]
@momokang  It not regrading to what you say. the function "getAllChats" stopped working and throw errror

**Comment by momokang** [comment]
@roysG oic, I had changed to getAllChatsWithMessages and it works fine now.

**Comment by edgardmessias** [comment]
Unable to reproduce here, could you provide more information and reopen the issue?
