### ISSUE TITLE
Ativar recurso: Mensagens Temporárias / Enable feature: Temporary Messages

### ISSUE THREAD

**Issue by ikarofsouza** [wppconnect-team/wppconnect#133]
Olá, gostaria de solicitar o recurso de Mensagens Temporárias.

- Ao ativar esse recurso, novas mensagens desaparecerão dessa conversa após 7 dias. Os participantes da conversa ainda podem salvar essas mensagens em outros locais.

---------------------------------

Hello, I would like to request the Temporary Messaging feature.

- When you activate this feature, new messages will disappear from this conversation after 7 days. Conversation participants can still save these messages to other locations.

![Screenshot_MT](https://user-images.githubusercontent.com/48399495/115150940-84c9f800-a062-11eb-9ad6-0ce459a1b04d.jpg)

**Comment by edgardmessias** [comment]
Released: https://github.com/wppconnect-team/wppconnect/releases/tag/v1.3.1
