### ISSUE TITLE
No longer displays the qrcode

### ISSUE THREAD

**Issue by loja5combr** [wppconnect-team/wppconnect#1332]
Anyone having a boot problem from yesterday to today? I'm not able to display the qrcode, without returning the tag below in the API.

`{"status":"INITIALIZING"}`

**Comment by edgardmessias** [comment]
Invalid ISSUE.

Please, edit your issue and fill all needed information

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no
