### ISSUE TITLE
WPP is not defined

### ISSUE THREAD

**Issue by fredEbho** [wppconnect-team/wppconnect#1335]
## Description

Hello, been getting the attached error since I upgraded to version 1.17.0
<img width="386" alt="Screenshot 2022-09-18 at 09 54 34" src="https://user-images.githubusercontent.com/35952541/190894073-0e18a660-f463-486b-a7eb-8a2dfc1094d2.png">

- **WPPConnect version(s):** 1.17.0

**Comment by wenioferraz** [comment]
Estou com esse problema também!

**Comment by antirek** [comment]
if use web 2.2230.15 - ok,
if use web 2.2234.6 or 2.2234.13 - not ok

use with wa-version 1.1.156

**Comment by voxsoftware** [comment]
Hi, any why to force using web 2.2230.15 while bug is solved?

**Comment by edgardmessias** [comment]
Unable to reproduce here

**Comment by downdawn** [comment]
![image](https://user-images.githubusercontent.com/41266749/191157248-f1c0af5a-25a3-4fd2-9ebe-182cdf143a9b.png)
If it is the first scan code login no problem. If the Tokens folder already exists, an error will occur

**Comment by jesusvalverde** [comment]
Work with options  whatsappVersion: '2.2230.15',  otherwise I see Error: WAPI is not defined

**Comment by jesusvalverde** [comment]
> 
Over the creation 


wa.create({session: idAcount,
                    whatsappVersion: '2.2230.15',
                     ...... })

**Comment by voxsoftware** [comment]
> > 
> 
> Over the creation
> 
> wa.create({session: idAcount, whatsappVersion: '2.2230.15', ...... })

Thanks, is a solution meanwhile.

**Comment by felipeescher** [comment]
> ![image](https://user-images.githubusercontent.com/41266749/191157621-9cd9fd74-d914-4032-a71a-bff42a1a8c8f.png)
> 
> If it is the first scan code login no problem. If the Tokens folder already exists, an error will occur

Was testing and looks like when the token is set the page load too fast, changed the order of the load hook and the page access looks like it fixed

**Comment by renat473** [comment]
close

fix alter file create-config.js whatsappVersion: '2.2230.15'

**Comment by renat473** [comment]
close

fix alter file create-config.js whatsappVersion: '2.2230.15'
