### ISSUE TITLE
getMessages get undefined for certain chatId

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1344]
## Description

getMessages get undefined for certain chatId
Not all chatId will have this issue, but if some of it have, then this app can't be known as "stable"

## Environment

- **WPPConnect version(s):** 1.16.1
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome 105
- **OS:** Windows 10
- **Node version:** Node 16.7.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Try to getMessages from a lot of chatId
2. You will find one or more chatId have this issue

## Your Code

```
waClient.getMessages(chatId)
		.then(function (allMsg) {
			if (allMsg == undefined) {
				return;
			}
			return allMsg;
		});
```

## Additional context / Screenshot

undefined

**Comment by momokang** [comment]
Ok, I know why it will show error for certain chatId, 
it's because you send button messages to user and they didnt respond it, 
I know the reason but I have no idea how to fix it.

**Comment by icleitoncosta** [comment]
Hello, I tried to reproduce this one to try to correct it, but here it is normally returning the messages. Could you test on the latest version and see if it's still connected?

**Comment by momokang** [comment]
> Hello, I tried to reproduce this one to try to correct it, but here it is normally returning the messages. Could you test on the latest version and see if it's still connected?

Hi, I tried with latest 1.19.1, still the same, it will only be error if last message is button messages
wpp.sendText(
customerPhone,
jsonMessage["message"], {
useTemplateButtons: false, // False for legacy
buttons: jsonButtons,
})

**Comment by icleitoncosta** [comment]
> > Hello, I tried to reproduce this one to try to correct it, but here it is normally returning the messages. Could you test on the latest version and see if it's still connected?
> 
> Hi, I tried with latest 1.19.1, still the same, it will only be error if last message is button messages wpp.sendText( customerPhone, jsonMessage["message"], { useTemplateButtons: false, // False for legacy buttons: jsonButtons, })

This was happening because we were using an alternative button template. Since it is no longer possible to send buttons, the error is not occurring anymore (when you receive it from the official API).
