### ISSUE TITLE
Client onMessage method not working

### ISSUE THREAD

**Issue by paraisotech** [wppconnect-team/wppconnect#1351]
My bot doesn’t figure out any incoming messages, acts like nothing happened. I’m using the onMessage method… does anyone facing the same issue?

**Comment by hubermi** [comment]
Yes, I experience the same behaviour

**Comment by ojixzzz** [comment]
same problem

**Comment by paraisotech** [comment]
I found a solution that is to clear all sessions on phone, quit the bot instance and read the qrcode again. This behavior is recent… maybe when a new bot release the developers team had solved it.

**Comment by roysG** [comment]
Same here, suddenly method onMessage stop working in latest version
