### ISSUE TITLE
restart authorized instance wppconnect failed

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1366]
## Description

wppconnect instance was started, after reading qr-code, instance authorized - and  i can send/receive messages.
sometimes wppconnect eat a lot of RAM, and I restarted it. But instance doesn't start. Browser show that whatsapp-web is loading and nothing. After clearing of browser directory I must again start wppconnect instance and read qr-code.
Earlier wppconnect instance start without any additional authorizations after reboot.

In logs:
start clear wppconnect instance:
`````
info:     You're up to date
info:     [whatsappsession:browser] Using browser folder './tokens/whatsappsession'
info:     [whatsappsession:browser] Initializing browser...
info:     [whatsappsession:client] Initializing...
Status { statusSession: 'notLogged', session: 'whatsappsession' }
qr code callback start
info:     [whatsappsession:client] WhatsApp WEB version: 2.2236.10
info:     [whatsappsession:client] WA-JS version: 2.13.1
info:     [whatsappsession:session] Session Unpaired
Status { statusSession: 'qrReadSuccess', session: 'whatsappsession' }
Status { statusSession: 'inChat', session: 'whatsappsession' }
`````
after reboot 
`````
info:     You're up to date
info:     [whatsappsession:browser] Using browser folder './tokens/whatsappsession'
info:     [whatsappsession:browser] Initializing browser...
info:     [whatsappsession:client] Initializing...
info:     [whatsappsession:client] WhatsApp WEB version: 2.2236.10
info:     [whatsappsession:client] WA-JS version: 2.13.1

no any data continue 5 minutes 
`````
![Screenshot from 2022-10-11 13-50-43](https://user-images.githubusercontent.com/324436/195018397-d83b97cc-7840-4fe0-985e-d9f7cb5e11f8.png)

after delete token dir and start clear wppconnect instance - read qr-code again and can use to next reboot ))

## Environment

- **WPPConnect version(s):** 1.17.1
- **WA-JS version(s):** 2.13.1
- **Browser:** Chrome 106
- **OS:** Ubuntu 20.04
- **Node version:** Node 16.15.1
- **WhatsApp version:** 2.2236.10
- **MultiDevice (BETA):** yes

**Comment by antirek** [comment]
if I change to old versions wppconnect, wa.js and whatsapp-web - authorized session up after reboot successful.

- WPPConnect version(s): 1.16.1
- WA-JS version(s): 2.11.0
- Browser: Chrome 106
- OS: Ubuntu 20.04
- Node version: Node 16.15.1
- WhatsApp version: 2.2230.15
- MultiDevice (BETA): yes

**Comment by rsaisankalp** [comment]
yes facing the same issue

**Comment by jesusvalverde** [comment]
same

**Comment by dionatanfmsilva** [comment]
Same problem here
Testing on my local machine displays these errors on the console

![001](https://user-images.githubusercontent.com/28758829/195656562-f78f7303-ec42-4d27-b068-fd2b4e6ba496.png)

**Comment by antirek** [comment]
up to latest wppconnect@1.17.1, wa.js@2.13.2, wa-version@1.1.174
also try test other versions wa-web:
2.2230.15 - all ok
2.2232.8 - all ok
2.2234.13 - all ok
2.2236.10 - problem
2.2238.7 - problem

**Comment by rsaisankalp** [comment]
Issue is not resolved. Same issue is persisting

**Comment by rsaisankalp** [comment]
Issue still persists in 1.18.0

**Comment by jesusvalverde** [comment]
On 16 independent bots, so far no issues with 1.18.0

- WA-JS version: 2.13.3
- whatsappVersion: '2.2230.15',

**Comment by edgardmessias** [comment]
@rsaisankalp, please, make a test with 1.18.1

**Comment by antirek** [comment]
I tested with wppconnect@1.18.1 and whatsapp-web 2.2240.7-beta - all good
@edgardmessias thanks!
@rsaisankalp up whatsapp-web version

**Comment by edgardmessias** [comment]
Thank's @antirek

**Comment by rsaisankalp** [comment]
Wppconnect 1.18.1
WA web version 2.2234.13

Unable to reconnect. 
Numbers gets disconnected within one day
Some times recovers sometimes not

wppconne | info:     Checking for updates
1|wppconne | info:     [919686188814:browser] Using browser folder './userDataDir/919686188814'
1|wppconne | info:     [919686188814:browser] Initializing browser...
1|wppconne | info:     You're up to date
1|wppconne | info:     [916281503099:browser] Using browser folder './userDataDir/916281503099'
1|wppconne | info:     [916281503099:browser] Initializing browser...
1|wppconne | info:     [919686188814:client] Initializing...
1|wppconne | info:     [916281503099:client] Initializing...

1|wppconnect  | info:     [919686188814:client] WhatsApp WEB version: 2.2234.13
1|wppconnect  | info:     [919686188814:client] WA-JS version: 2.13.3
1|wppconnect  | info:     [919686188814:client] Auto close configured to 60s
1|wppconnect  | info: 2022-10-22T01:02:55.306Z isLogged
1|wppconnect  | info:     [919686188814:client] Auto close configured to 60s
1|wppconnect  | info:     [916281503099:client] WhatsApp WEB version: 2.2234.13
1|wppconnect  | info:     [916281503099:client] WA-JS version: 2.13.3
1|wppconnect  | info:     [916281503099:client] Auto close configured to 60s
1|wppconnect  | info: 2022-10-22T01:02:56.505Z isLogged
1|wppconnect  | info:     [916281503099:client] Auto close configured to 60s
1|wppconnect  | info:     [919686188814:client] Closing the page
1|wppconnect  | info: 2022-10-22T01:03:55.588Z browserClose
1|wppconnect  | error: 2022-10-22T01:03:55.750Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
1|wppconnect  |     at CDPSession.send (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:265:35)
1|wppconnect  |     at ExecutionContext._ExecutionContext_evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:268:46)
1|wppconnect  |     at ExecutionContext.evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:113)
1|wppconnect  |     at DOMWorld.evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:191:24)
1|wppconnect  | info:     [916281503099:client] Closing the page
1|wppconnect  | info: 2022-10-22T01:03:56.745Z browserClose
1|wppconnect  | error: 2022-10-22T01:03:56.885Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
1|wppconnect  |     at CDPSession.send (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:265:35)
1|wppconnect  |     at ExecutionContext._ExecutionContext_evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:268:46)
1|wppconnect  |     at ExecutionContext.evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:113)
1|wppconnect  |     at DOMWorld.evaluate (/home/ec2-user/whatsappserver/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:191:24)
