### ISSUE TITLE
Unread messages methods not working

### ISSUE THREAD

**Issue by LucasPonzo** [wppconnect-team/wppconnect#137]
## Description

When session is successfully initialized, I need to get the unread messages arrived when the session was not connected. 

I tried to use: getAllNewMessages, getAllUnreadMessages and getUnreadMessages but all of then returns 0 messages in the returned list.

Suggestion: It can return an array of Chat objects (that contains unread messages), and on each chat object it could have an messageList array only with the unreaded messages. Or it can return a flat array of message objects (unreaded messages of course) with a field indicating the chatId (xxx@c.us).

## Environment

- **Wppconnect version(s):** [latest]
- **Browser:** [Chrome and Chromium latest]
- **OS:** [Windows and Linux]
- **Node version:** [Node 12.6.1]

**Comment by edgardmessias** [comment]
Fixed at v1.3.6

Note: getAllNewMessages depends of the time of message to consider a new message
