### ISSUE TITLE
Erro ao recuperar seção 

### ISSUE THREAD

**Issue by megustalol** [wppconnect-team/wppconnect#1387]
## Description

Ao tentar reconectar acontece esse erro, também após algumas hora com a seção ativa ela "trava" e é preciso reiniciar precisando ler o qr cod novamente pois não está recuperando.

## Environment

- **WPPConnect version(s): 1.18.1
- **WA-JS version(s):** 2.13.3
- **Browser:** Chrome 
- **OS:** Windows server 
- **Node version:** 8.18.0
- **WhatsApp version:** 2.2234.13
- **MultiDevice (BETA):** yes

[:browser] Initializing browser...
| info:     [:client] Initializing...
| info:     [:client] WhatsApp WEB version: 2.2234.13
| info:     [:client] WA-JS version: 2.13.3
| info:     [:client] Auto close configured to 60s
| Status Session:  isLogged
| info:     [:client] Auto close configured to 60s
| info:     [:client] Closing the page
| Status Session:  autocloseCalled
| Status Session:  browserClose
| Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
|     at CDPSessionImpl.send (C:\Users\Administrator\Desktop\Pasta\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:316:35)
|     at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Desktop\Pasta\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:211:46)

**Comment by icleitoncosta** [comment]
Qual a configuração do servidor que está rodando o WPPCONNECT?
Isso pode ser um erro de falta de recursos que causa o crash do chrome

**Comment by edgardmessias** [comment]
@megustalol, pelo seu log, parece que só foi ação do autoclose.

Mas para melhor verificação, faça o seguinte, aumente o nível de LOG para silly, e assim que ocorrer o problema, anexe o log para termos uma melhor direção do que fazer.

Como alterar o nível de LOG: https://wppconnect.io/docs/tutorial/basics/configuring-logger

**Comment by megustalol** [comment]
O erro era ação do autoclose, não dando tempo o suficiente para carregar a seção, obrigado.
