### ISSUE TITLE
[Bug]: Error: An executablePath or channel must be specified for puppeteer-core at assert 

### ISSUE THREAD

**Issue by tolgakocadag** [wppconnect-team/wppconnect#1402]
"@wppconnect-team/wppconnect": "^1.19.0",
ubuntu 20.04
- **Node version:** v14.19.0

**Comment by momokang** [comment]
My previous wppconnect is log disable with following script:
wppconnect.defaultLogger.transports.forEach((t) => (t.silent = true));
updatesLog: false,

After I comment them out (enable to show logs)
The session able to resume, not sure if it helps.
