### ISSUE TITLE
whatsapp communities message is not going

### ISSUE THREAD

**Issue by rsaisankalp** [wppconnect-team/wppconnect#1414]
whatsapp communities message is not going

**Comment by icleitoncosta** [comment]
At the moment we are still not able to use the communities.

What error does it return?

**Comment by edgardmessias** [comment]
@rsaisankalp , please, respect the issue template: https://github.com/wppconnect-team/wppconnect/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by rsaisankalp** [comment]
Any update to use send message to communities

**Comment by icleitoncosta** [comment]
> 


> Any update to use send message to communities


please, respect the issue template: https://github.com/wppconnect-team/wppconnect/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
