### ISSUE TITLE
not qrCatch callback

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#1422]
## Description
create wppconnect instance, start instance but not execute catchQr callback after start
log
`````
   [whatsappsession:browser] Using browser folder './tokens/whatsappsession'
   [whatsappsession:browser] Initializing browser...
   [whatsappsession:client] Initializing...
   [whatsappsession:session] Session Unpaired
   [whatsappsession:client] WhatsApp WEB version: 2.2243.7
   [whatsappsession:client] WA-JS version: 2.15.2
 -- and here must receive qr
`````
same code on previous used version wa.js wa_js 2.13.4 execute normally

## Environment

- **WPPConnect version(s):**  1.19.0
- **WA-JS version(s):** 2.15.2
- **Browser:** Chrome 107
- **OS:** Ubuntu 20.04
- **Node version:** Node 18.12.1
- **WhatsApp version:** 2.2243.7
- **MultiDevice (BETA):** yes

**Comment by antirek** [comment]
ok, test with another wa-web versions 
wa.js@2.15.2

2.2241.7 - ok, show qr-code
2.2242.6 - not ok, no qr-code
2.2243.7 - not ok, no qr-code

if I open web.whatsapp.com in my browser - show code, no problems (and I see that use version 2.2243.7)
if I open web.whatsapp.com in automated browser, also 2.2243.7, I see only "Whatsapp end-to-end encrypted" some minutes without changes

![Screenshot from 2022-11-17 13-03-13](https://user-images.githubusercontent.com/324436/202369328-3e731347-2be8-43b3-87f1-c41b301b78f5.png)

**Comment by edgardmessias** [comment]
Thanks @antirek , I will try to see whats happen
