### ISSUE TITLE
return pid of puppetter process before client init

### ISSUE THREAD

**Issue by wduandy** [wppconnect-team/wppconnect#1425]
**Is your feature request related to a problem? Please describe.**
Yes, in the current scenario sometimes wppconnect spawn zombie processes that cannot be terminated.

**Describe the solution you'd like**
Return the PID of the puppetter instance for future handling.

**Comment by DevDefault** [comment]
> **Is your feature request related to a problem? Please describe.** Yes, in the current scenario sometimes wppconnect spawn zombie processes that cannot be terminated.
> 
> **Describe the solution you'd like** Return the PID of the puppetter instance for future handling.

Hello, I need the same function, did you get any solution?

**Comment by edgardmessias** [comment]
Yes, I will create a callback function to pass to create method

**Comment by DevDefault** [comment]
> Sim, vou criar uma função callback para passar para o método create

Thank's ❤️

**Comment by wduandy** [comment]
> Yes, I will create a callback function to pass to create method

Thanks!!! ❤️

**Comment by jaderesp** [comment]
I don't know if it's suitable for the layout of the project, but I'm using the library to store the pid of each session in the global variable of sessions via puppeteer: https://www.npmjs.com/package/find-process
