### ISSUE TITLE
Check Number Status Not Working

### ISSUE THREAD

**Issue by krunal-sprouto** [wppconnect-team/wppconnect#1428]
In wppconnect-wa.js t.queryExists function got return null in all numbers.

checkNumberStatus function not working

window.WAPI.checkNumberStatus = async function (id) {
          const result = await WPP.contact.queryExists(id);
      
          if (!result) {
            return {
              id: id,
              isBusiness: false,
              canReceiveMessage: false,
              numberExists: false,
              status: 404,
            };
          }
      
          return {
            id: result.wid,
            isBusiness: result.biz,
            canReceiveMessage: true,
            numberExists: true,
            status: 200,
          };
        };

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** ^1.19.1
- **WA-JS version(s):** ^2.15.2
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Please, update the wa-js to latest version: [v2.16.1](https://github.com/wppconnect-team/wa-js/releases/tag/v2.16.1)

`npm install @wppconnect/wa-js@latest`
