### ISSUE TITLE
Reply messages not show on .onMessage

### ISSUE THREAD

**Issue by etc-tiago** [wppconnect-team/wppconnect#1431]
## Description

I noticied starting today that .onMessage is not called when the user replay some message.

## Environment

- **WPPConnect version(s):** 1.19.1
- **WA-JS version(s):** 1.1.202
- **Browser:** 107
- **OS:** OSX 12.4
- **Node version:** Node 16
- **MultiDevice (BETA):** default option of package

## Log Output

No logs

## Your Code

I use the example code of docs.
```js
const wppconnect = require('@wppconnect-team/wppconnect');

wppconnect
  .create()
  .then((client) => start(client))
  .catch((error) => console.log(error));

function start(client) {
  client.onMessage((message) => {
    console.log(message); // not call on reply messages
  });
}
```

**Comment by etc-tiago** [comment]
O problema foi corrigido. Provavelmente é uma coisa da web do whatsapp...

**Comment by willpexeroo** [comment]
Só funciona para chats @c.us, se voce tentar com chat @lid e ele responder uma mensagem sua como 'resposta' nada é capturado.

Preciso capturar replays de chats @lid mas infelizmente nao achei nenhuma alternativa.
