### ISSUE TITLE
Session Unpaired

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1433]
## Description

Re-login and get session unpaired

## Environment

- **WPPConnect version(s):** 1.19.1
- **WA-JS version(s):** 2.16.0
- **Browser:** Chromium
- **OS:** Ubuntu
- **Node version:** Node 18.12.1
- **WhatsApp version:** 2.2234.13
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Login by scan qr code
2. Disconnect node
3. Login again and failed to login

## Log Output

```
Session Unpaired
WhatsApp WEB version: 2.2234.13
WA-JS version: 2.16.0
Auto close configured to 60s
```

wppconnect
	.create({
		session: 'session' + port,
		puppeteerOptions: {
			args: ['--no-sandbox', '--use-gl=egl'],
			userDataDir: './tokens/session' + port,
			executablePath: executablePath()
		},
		disableWelcome: true,
		catchQR: (base64Qrimg, asciiQR, attempts, urlCode) => {
		},
		statusFind: (statusSession, session) => {
			console.log("statusSession: " + statusSession);
		},
	})
	.then((client) => waConnected(client))
	.catch((error) => console.log(error));

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by momokang** [comment]
I hosted it in Ubuntu hosting environment using pm2.
I'm connecting 2 WhatsApp number in same server.
The node will shutdown randomly, 
once per day, and wake up by pm2 then try reconnect @wppconnect.
Then it failed to reconnect and auto-reply failed.
.
**Update:** 
I tried with fs-extra to backup the whole tokens/session folder and session.json and paste it whenever failed to reconnect, it is still failed to reconnect WhatsApp as well.
.
It's frustrated as I can't keep tell my client to re-connect via qrcode as it's not auto-reply works.
Anyone has the same issue or work-around to fix it? 
.
Much appreciate.

**Comment by momokang** [comment]
Update:
Working with token store now

```
var myTokenStore = new wppconnect.tokenStore.FileTokenStore({
	decodeFunction: JSON.parse,
	encodeFunction: JSON.stringify,
	encoding: 'utf8',
	// fileExtension: '.my.ext',
	path: './tokens/session' + port,
});
```

it works quite well for 1 day, let monitor it more

**Comment by momokang** [comment]
Update:
One of the session failed to re-login, I suspect it's because I initial the chromium at same time for few wppconnect, so I delayed it. 
Overall it's successfully re-connected session.
Lets monitor for few more days.

**Comment by momokang** [comment]
Update:
myTokenStore works like a charm, somehow it cleared the token session after first login, but after 2nd login it's working fine now.
This git repository deserves a medal, can you fix the donate paypal link?

**Comment by edgardmessias** [comment]
@momokang , I am will try to fix the paypal link later, but you can send to this address: `edgardmessias+1@gmail.com`
