### ISSUE TITLE
The package.json updated, but the bump version is the same

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1437]
Why you did not bumped the version?

**Comment by edgardmessias** [comment]
What?

**Comment by roysG** [comment]
When i do the command: "npm install"

I get the latest version of 1.19.1. 

But the package.json is not the updated one.

As you can see, you did updates in the package.json.

**Comment by edgardmessias** [comment]
Do this: `npm install @wppconnect-team/wppconnect@latest`
