### ISSUE TITLE
The Session does not start

### ISSUE THREAD

**Issue by alexolmait** [wppconnect-team/wppconnect#1438]
## The Session does not start

Wppconnect starts initializing a session but newer ends.
No QR code is generated.
This issue has started appearing since 28 Nov.

## Environment

- **WPPConnect version(s):** 1.16, 1.17 (Docker version)
- **Browser:** Chromium XX
- **OS:** Ubuntu 20.04

Running a few instances on different machines; and the issue started appearing on all of them.

## Steps to Reproduce

1. Generate token {{baseUrl}}/api/nova/:secretkey/generate-token
2. start session {{baseUrl}}/nova/start-session
3. {{baseUrl}}/nova/status-session

Updated wppconnect version 1.16 to 1.17
Rebuild docker images, but the issue persists

## Log Output

```
{
    "status": "success",
    "session": "nova",
    "token": "$2b$10$M8BSLYBz5rh41MP7uo1LaelxvqoYC8a3OfKYS6_TnzYf6BFCBayLO",
    "full": "nova:$2b$10$M8BSLYBz5rh41MP7uo1LaelxvqoYC8a3OfKYS6_TnzYf6BFCBayLO"
}

{
    "status": "INITIALIZING",
    "session": "nova"
}
```

## P.S.

Wondering if others are having the same problem?

**Comment by YosefAdPro** [comment]
same problem 
latest version of wppconnect 

Initializing browser...

**Comment by edgardmessias** [comment]
Please, increase the log detail to silly and post it.

How to increase the log: https://wppconnect.io/docs/tutorial/basics/configuring-logger

**Comment by YosefAdPro** [comment]
```
warning @wppconnect/wa-js@2.15.2: The engine "whatsapp-web" appears to be invalid.


info: 2022-11-30T12:39:28.113Z Server is running on port: 21465
info: 2022-11-30T12:39:28.119Z  Visit http://localhost:21465/api-docs for Swagger docs
info: 2022-11-30T12:39:28.119Z WPPConnect-Server version: 1.7.2
info:
  _       ______  ____  ______                            __
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     [S1:browser] Using browser folder './userDataDir/S1'
info:     [S1:browser] Initializing browser...
info:     You're up to date

```

**Comment by YosefAdPro** [comment]
After I changed the version from `"wa-version": "^1.1.197",` to `1.1.204`
The other sessions started working, but it crashes after a while

```
info:     [S93300:client] WhatsApp WEB version: 2.2234.13
info:     [S93300:client] WA-JS version: 2.16.2
info:     [S93300:client] Auto close configured to 60s
info: 2022-11-30T13:24:26.483Z isLogged
info:     [S93300:client] Auto close configured to 60s
info: 2022-11-30T13:24:34.068Z [S93300] 0% - Connecting…
info: 2022-11-30T13:24:37.670Z [S93300] 100% - Organizing messages
info:     [S93300:client] Closing the page
info: 2022-11-30T13:25:26.788Z browserClose


error: 2022-11-30T13:25:27.610Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:316:35)
    at ExecutionContext._ExecutionContext_evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
    at async ExecutionContext.evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
error: 2022-11-30T13:25:27.779Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:316:35)
    at ExecutionContext._ExecutionContext_evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
    at async ExecutionContext.evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)


```

**Comment by alexolmait** [comment]
After a few minutes of initialization I get this error:

![image](https://user-images.githubusercontent.com/103721117/205083363-50741deb-4593-403c-a524-03303fdbde65.png)

**Comment by alexolmait** [comment]
I use all kind versions, but I get the same issue for updated one as well.
![image](https://user-images.githubusercontent.com/103721117/205242264-11347935-2671-43f4-b0cf-c48786d69a01.png)

**Comment by momokang** [comment]
1. Use newer version 1.19.1
2. Make sure your package is not too old, example puppeteer package that create chromium
3. Delete your session folder and try again

**Comment by alexolmait** [comment]
A change of package manager in DockerFile from yarn to npm helped.
I also made some changes in config.json of server as redisHost configuration differed from the old one.

**Comment by YosefAdPro** [comment]
> After I changed the version from `"wa-version": "^1.1.197",` to `1.1.204` The other sessions started working, but it crashes after a while
> 
> ```
> info:     [S93300:client] WhatsApp WEB version: 2.2234.13
> info:     [S93300:client] WA-JS version: 2.16.2
> info:     [S93300:client] Auto close configured to 60s
> info: 2022-11-30T13:24:26.483Z isLogged
> info:     [S93300:client] Auto close configured to 60s
> info: 2022-11-30T13:24:34.068Z [S93300] 0% - Connecting…
> info: 2022-11-30T13:24:37.670Z [S93300] 100% - Organizing messages
> info:     [S93300:client] Closing the page
> info: 2022-11-30T13:25:26.788Z browserClose
> 
> 
> error: 2022-11-30T13:25:27.610Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
>     at CDPSessionImpl.send (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:316:35)
>     at ExecutionContext._ExecutionContext_evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
>     at async ExecutionContext.evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
> error: 2022-11-30T13:25:27.779Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
>     at CDPSessionImpl.send (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:316:35)
>     at ExecutionContext._ExecutionContext_evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
>     at async ExecutionContext.evaluate (/home/node/app/node_modules/@wppconnect-team/wppconnect/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
> ```

It doesn't work at all.

**Comment by aislanspeedio** [comment]
I'm getting the same error now when trying to send messages...

`Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.`
