### ISSUE TITLE
How to add a contact and get Contact Id by number?

### ISSUE THREAD

**Issue by rajenpal033** [wppconnect-team/wppconnect#1444]
I want a contact to be added programmatically. is there any such method available? Also if I want to get the Contact Id string using phone number, is that possible?

**Comment by icleitoncosta** [comment]
For you to create the contact on the device (cell phone) it is not possible.
You can use checkNumberStatus (https://wppconnect.io/wppconnect/classes/Whatsapp.html#checkNumberStatus.checkNumberStatus-1) to be able to check what his ID is, and if that number exists.

**Comment by rajenpal033** [comment]
Hello @icleitoncosta thank for your solution but the checkNumberStatus also need the contact id as parameter, I want to fetch the contact id using phone number.

**Comment by momokang** [comment]
checkNumberStatus is what you need, the 'contactId' is api document typo, in fact you should provide phone number with '@c.us', example 'xxxxxxxxx@c.us' and it will return the phone is valid whatsapp or not.
