### ISSUE TITLE
Session gets logout randomly.

### ISSUE THREAD

**Issue by hardik323** [wppconnect-team/wppconnect#1462]
## Description
We're running wpp-connect 1.19.2 and running multiple sessions using pm2 in production. The issue is the sessions gets logout randomly in general 24 to 48 hours and it appears that our users needs to scan the QR code again and again.

## Environment
Ubuntu 20.04
Node 18.7.0

- **WPPConnect version(s):** 1.19.2
- **WA-JS version(s):** 2.17.0
- **Browser:** Chromium 0.15.1
- **OS:** Ubuntu 20.04
- **Node version:** 18.7.0
- **WhatsApp version:** 2.2230.9
- **MultiDevice (BETA):** yes

## Steps to Reproduce
Scan the device (multiple with different pm2)
It will logout randomly in 24 to 48 hours.

## Log Output
- It generates new QR hence, requires to scan it again.

**Comment by momokang** [comment]
It happens on me, there are 4 sessions on server with pm2, but only 1 session will logout randomly without reason. Any idea? @icleitoncosta

**Comment by momokang** [comment]
Hi, as @icleitoncosta mentioned, it's highly possible the local machine issue, like CPU spike, but is there an option if it's due to CPU spike and try to relogin, don't delete the tokenSession and try to reconnect with existing tokenSession? It's annoying that it logout if CPU spike at that particular moment and needed to re-login WhatsApp.

**Comment by danuwardinesh** [comment]
Hi @momokang As @hardik323 mention it happen so many times even there is no such memory and CPU usages, CPU are normal like 10-30% and I have available 18GB on my VM .

**Comment by momokang** [comment]
Same here, my pm2 services will auto restart without any reason.

**Comment by edgardmessias** [comment]
@hardik323 @momokang @danuwardinesh , could you test with the latest version of lib?

https://github.com/wppconnect-team/wppconnect/releases/tag/v1.23.0

**Comment by danuwardinesh** [comment]
@edgardmessias I have upgraded version 1.23.0 and the result is same still my sessions are log out :

1. session are log out during the active session like sending messages are in queue, 
2. WPP/PM2 services were frequently restart autometically as well

**Comment by momokang** [comment]
@danuwardinesh it works well for me if you set the token store

var myTokenStore = new wppconnect.tokenStore.FileTokenStore({
	decodeFunction: JSON.parse,
	encodeFunction: JSON.stringify,
	encoding: 'utf8',
	// fileExtension: '.my.ext',
	path: './tokens/session' + port,
});

it will solve the session logout and unable login issue.
wpp/pm2 frequently restart I have no clue either

**Comment by edgardmessias** [comment]
@momokang , I removed the tokenstore on latest version

**Comment by wasare** [comment]
> @momokang , I removed the tokenstore on latest version

Now what's the recommended method to store the tokens to restore previous the sessions ?

**Comment by edgardmessias** [comment]
The method stil existing, basicaly is the userDataDir argument, but it is setted automatically to tokens folder

**Comment by icleitoncosta** [comment]
> @edgardmessias can you give us the new method to restore the session ?

It is only necessary to use the same name as the previously created session in the "create" function.
