### ISSUE TITLE
Stuck in Initializing browser

### ISSUE THREAD

**Issue by roux3** [wppconnect-team/wppconnect#1474]
I have a problem in this latest version of wppconnect(1.20.0) wppconnect does not run, 
it just stays in 'Initializing browser' and does not start.

![image](https://user-images.githubusercontent.com/43356551/208315668-e8516afe-4f11-4554-ad8c-9c736d1283d2.png)

**Comment by renat473** [comment]
Atualize a versão do nodejs para 16.

**Comment by roux3** [comment]
@renat473 Updated but still doing the same thing.

**Comment by edgardmessias** [comment]
Aumente o nível do LOG: https://wppconnect.io/docs/tutorial/basics/configuring-logger

**Comment by roux3** [comment]
@edgardmessias I just solved it by updating to version 19 of node. Thank you friend.
