### ISSUE TITLE
WPPCONNECT e ARM64

### ISSUE THREAD

**Issue by JandersonFB** [wppconnect-team/wppconnect#1485]
Bom dia,
Estou tentando rodar o Wppconnect em um processador ARM64, porém ele só fica travado nesse estado:
Alguém já passou por algo semelhante ?

![image](https://user-images.githubusercontent.com/11274709/209829441-a52015e3-ee3e-4e8d-93f8-2c58a6698d3c.png)

**Comment by renat473** [comment]
atualize a versão do nodejs para versão 16 e faça a instalação do google chrome

**Comment by JandersonFB** [comment]
@renat473 desculpe se minha pergunta foi tão "basica" rs
Mas está com o NODE16 e o CHROME instalado.

**Comment by renat473** [comment]
entra no canal do discord , https://discord.gg/JU5JGGKGNG que fica mais fácil lhe ajudar com seu problema.

Lembrando que o arm64 não vai funcionar o processo precisa ser 64bits.

**Comment by visuweb** [comment]
Olá amigo @JandersonFB  vc conseguiu colocar o WPPCONNECT para rodar em ARM64??
