### ISSUE TITLE
How to check that all messages synced in the web?

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1488]
## Description

The getMessages working ok. 
but for getting all the older messages, in the first time the whatsapp in the phone should be open until all the messages synced in the web.

Is there any command to let us see this processing?

## Environment

- **WPPConnect version(s):** latest
- **WA-JS version(s):** 2.18.0
- **Browser:** Chrome XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:**  2.2234.13
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. run the command getMessages
3. You will get less than 20 last messages.

```
If relevant, paste all of your Log Output
```

## Your Code

``
`const allMsgs = await client.getMessages('number@c.us',{count:100});`

**Comment by icleitoncosta** [comment]
That today is available in LIB no. I don't think there is a status of the process even on WhatsApp, maybe it's possible to get it through Puppeeter.

**Comment by icleitoncosta** [comment]
> ## Description
> The getMessages working ok. but for getting all the older messages, in the first time the whatsapp in the phone should be open until all the messages synced in the web.
> 
> Is there any command to let us see this processing?
> 
> ## Environment
> * **WPPConnect version(s):** latest
> * **WA-JS version(s):** 2.18.0
> * **Browser:** Chrome XX
> * **OS:** Windows X / OSX X.Y.Z
> * **Node version:** Node XY
> * **WhatsApp version:**  2.2234.13
> * **MultiDevice (BETA):** yes
> 
> ## Steps to Reproduce
> 1. run the command getMessages
> 2. You will get less than 20 last messages.
> 
> ```
> If relevant, paste all of your Log Output
> ```
> 
> ## Your Code
> `` `const allMsgs = await client.getMessages('number@c.us',{count:100});`

Hello, you can use statusFind, and execute the functions after event inChat, or check is sync with function `client.isMainReady`.
