### ISSUE TITLE
Problem loading all messages

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1494]
Hi,
When the whatsapp sync all the user׳s messages, the next time i restart the whatsapp and there are a lot of messages to load, the loading may suddenly stop with error "Phone Not Connected".

This message is not accurate, cause it was my phone and i was connected.
When i tried restart it again and load the messages, it was ok.

But sometimes it make take a longer time to load the messages and then again the same error..

**Comment by renat473** [comment]
this is a normal problem with whatsapp itself when there is a history of many conversations.

We recommend cleaning up conversations.
