### ISSUE TITLE
Unconsistent output

### ISSUE THREAD

**Issue by FerryAr** [wppconnect-team/wppconnect#1504]
## Description

Unconsistent output from getAllChats() and getAllChatsWithMessages()

## Environment

- **WPPConnect version(s):** 1.20.0
- **WA-JS version(s):** 2.18.1
- **Browser:** Chromium latest from Homebrew
- **OS:** MacOS Monterey 12.6
- **Node version:** Node 18.13.0
- **WhatsApp version:** 2.22.24.78
- **MultiDevice (BETA):** yes

## Output

getAllChats()
![Screen Shot 2023-01-17 at 09 03 03](https://user-images.githubusercontent.com/38641932/212793827-6bae6233-eb58-4c9e-8290-827966747cf6.png)

getAllChatsWithMessages()
![Screen Shot 2023-01-17 at 09 04 02](https://user-images.githubusercontent.com/38641932/212793882-c86e13ed-dbdd-4a8f-aedc-230b6dc559e4.png)

With getAllChats() I can see there is contact data but no message, but with getAllChatsWithMessages() the messages is there but not the contact data. I want to use the contact data to display the contact and the message data to display the latest message

**Comment by icleitoncosta** [comment]
This is a normal result, as this return comes from WhatsApp itself.
I suggest doing the following:

```
const allChatsWithMessages = await client.getAllChatsWithMessages();
for (const msgs of allChatsWithMessages) {
    const contact = client.getChatById(msgs.id);
    msgs.contact = contact;
}
console.log(allChatsWithMessages)
```
With this code you will return the chat already formatted as you need. We avoid messing too much with the return of what WhatsApp sends us to avoid BREAKING CHANGES.
