### ISSUE TITLE
Enviar VCARD com texto "ENCAMINHADO"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#151]
queria mandar um VCARD 
escrito encaminhado

como no exemplo abaixo:
![WhatsApp Image 2021-04-24 at 19 29 33](https://user-images.githubusercontent.com/35501007/115974572-15f21080-a534-11eb-8768-7f9acc345e0e.jpeg)

Detalhe: Se eu enviar TEXTO sendMessageOptions inserindo isForwarded:true vai

Somente VCARD que não vai.

Obrigado

**Comment by moskoweb** [comment]
Mas por que não manda o vcard direto pela opção 'contact-vcard'?? Ele vai a opção de mensagem e também de adicionar o contato.

**Comment by mvac1991** [comment]
> Mas por que não manda o vcard direto pela opção 'contact-vcard'?? Ele vai a opção de mensagem e também de adicionar o contato.

Pq o "encaminhado" dá um ar que o próprio cara foi lá e mandou, tipo um ar mais humano.

**Comment by mvac1991** [comment]
@edgardmessias fechou a ISSUE e não escreveu nada, o que houve?

**Comment by edgardmessias** [comment]
Esse recurso não será implementado.

**Comment by mvac1991** [comment]
> Esse recurso não será implementado.

Qual motivo?

**Comment by edgardmessias** [comment]
@mvac1991 , estou filtrando o que é relevante por minha parte implementar.

Caso queira, sinta-se livre em fazer PR para contribuir com o projeto

**Comment by mvac1991** [comment]
> @mvac1991 , estou filtrando o que é relevante por minha parte implementar.
> 
> Caso queira, sinta-se livre em fazer PR para contribuir com o projeto

Gostaria eu de atender o seu pedido!
