### ISSUE TITLE
Ao enviar VCARD do mesmo WhatsApp o NOME fica como "VOCÊ"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#152]
Estou com um BUG no envio de VCARD.

Mesmo passando o NOME como parâmetro string, ao enviar o meu contato do meu próprio número ele fica como "VOCÊ"
![image](https://user-images.githubusercontent.com/35501007/115974632-708b6c80-a534-11eb-8743-13ac3c868e3f.png)

Quando envio um VCARD de outro WhatsApp dá certo.

**Comment by igorgazoni** [comment]
após atualização para v1.3.2 ### bug ainda ocorre.

**Comment by edgardmessias** [comment]
Corrigido na versão v1.3.3
