### ISSUE TITLE
 Error: Version not available for 2.2245.x

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1553]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** Latest
- **WA-JS version(s):** Latest
- **Browser:** Chrome 
- **OS:** Linux
- **Node version:**: v16.19.0
- **WhatsApp version:** 
- **MultiDevice (BETA):** yes

 Error: Version not available for 2.2245.x

**Comment by edgardmessias** [comment]
Please, use at moment: `whatsappVersion: null` or `whatsappVersion: '2.2305.7'`.

The WhatsApp was blocked all previous versions
