### ISSUE TITLE
How to set proxy account password?

### ISSUE THREAD

**Issue by downdawn** [wppconnect-team/wppconnect#1555]
How to set proxy account password?

let proxyUrl = 'http://username:passwd@127.0.0.1:8080'
browserArgs: ['--no-sandbox', '--disable-setuid-sandbox', '--proxy-server=' + proxyUrl]

proxy not working

**Comment by edgardmessias** [comment]
This a limitation by chromium, but as an alternative, you can use [proxy-chain](https://www.npmjs.com/package/proxy-chain) to create a localhost proxy using a remove proxy
