### ISSUE TITLE
Error: Evaluation failed: ReferenceError: WPP is not defined

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#1557]
## Description

 LOADING_SCREEN 0 WhatsApp
714|5d73b9bf51f9648f44fb500b6e84ba91  | leftSecondFromStoppedLoop 0.108
714|5d73b9bf51f9648f44fb500b6e84ba91  | verbose:  [5d73b9bf51f9648f44fb500b6e84ba91:page] Page loaded
714|5d73b9bf51f9648f44fb500b6e84ba91  | verbose:  [5d73b9bf51f9648f44fb500b6e84ba91:client] Injecting wapi.js
714|5d73b9bf51f9648f44fb500b6e84ba91  | Error: Evaluation failed: ReferenceError: WPP is not defined
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at pptr://__puppeteer_evaluation_script__:1:16
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at ExecutionContext._ExecutionContext_evaluate (/root/msgto/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:255:15)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at runMicrotasks (<anonymous>)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
714|5d73b9bf51f9648f44fb500b6e84ba91  |     at async ExecutionContext.evaluate (/root/msgto/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:143:16)
714|5d73b9bf51f9648f44fb500b6e84ba91  | (SIGINT) Shutting down...
714|5d73b9bf51f9648f44fb500b6e84ba91  | env prod serverId undefined
714|5d73b9bf51f9648f44fb500b6e84ba91  | whatsappWebApi.serverId 5d73b9bf51f9648f44fb500b6e84ba91

## Environment

- **WPPConnect version(s):** Latest
- **WA-JS version(s):** Latest
- **Browser:** Chrome 
- **OS:** Linux
- **Node version:** 
- **WhatsApp version:** Latest
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Fixed with latest release
