### ISSUE TITLE
Client.OnMessage does not fire event on group message received

### ISSUE THREAD

**Issue by hardik323** [wppconnect-team/wppconnect#1564]
## Description
I want to receive image messages from the group
It works for my number (india) but not for Sweden number. i.e. If QR is scanned from Sweden number.

It shows following logs:
0|index  | debug:    [chat1:client] Emitting onAnyMessage event (0 registered)
0|index  | debug:    [chat1:client] Emitting onPresenceChanged event (0 registered)

## Environment

- **WPPConnect version(s):**1.22.0
- **WA-JS version(s):** 2.19.1
- **Browser:**  Chromium 0.15.1
- **OS:** Ubuntu 22
- **Node version:** Node 18.14.2
- **WhatsApp version:** 1.1.257
- **MultiDevice (BETA):** yes

## Log Output

```
0|index  | debug:    [chat1:client] Emitting onAnyMessage event (0 registered)
```

## Your Code
async function start(client) {
  whatsppInstance = client; //It will be used in REST requests

  client.onMessage(async (msg) => {

    try {
      console.log('msg', msg)
      if (!IsMessageFromGroup(msg)) {
        console.log('image is not in group')
        return;
      }

      if (!IsImageMessage(msg)) {
        console.log('It is not image message')
        return;
      }

      if (!await IsGroupMatches(whatsppInstance, msg, process.env.GROUP_NAMES)) {
        console.log('Group not matched')
        return;
      }

      let buffer = await GetImageBufferFromMessage(whatsppInstance, msg)

      await downloadImage(whatsppInstance, msg)

    } catch (e) {
      console.log(e);
    }
  });
}

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by icleitoncosta** [comment]
Hello @hardik323, i not have way to reproduce this issue because have a Sweden number, you have a time to try us together solve this issue?

**Comment by icleitoncosta** [comment]
Closed, as it has no author iteration.
