### ISSUE TITLE
Conexões simultâneas

### ISSUE THREAD

**Issue by FelipeAugustoCrici** [wppconnect-team/wppconnect#1570]
Quando faço o rebot na API, apenas 7 conexões são refeitas, poderia me dizer se possui limitação? Ou se possui alguma solução para que todas as sessões sejam refeitas?

Estou usando a última versão lançada LTS

Uso disco para armazenar as sessões e depois recuperá-las.

**Comment by icleitoncosta** [comment]
Opa, não há limitação. A limitação é apenas hardware. Memória e processamento, é bom avaliar o consumo, ou aumentar os recursos do VPs para testar.
