### ISSUE TITLE
Como desabilitar o console.log dos eventos

### ISSUE THREAD

**Issue by AlexORocha** [wppconnect-team/wppconnect#1578]
Boa tarde! Tudo bem?

Estou com uma dúvida para desabilitar o console.log dos eventos emitidos pelo client.

Estes, no caso:

![image](https://user-images.githubusercontent.com/81656002/225421217-be39e393-19f8-45c3-988d-9c3f99ae6ee2.png)

Ah, o link para o discord também está expirado, por isso perguntei aqui e não localizei na documentação =/

Obrigado!

**Comment by edgardmessias** [comment]
https://wppconnect.io/docs/tutorial/basics/configuring-logger

**Comment by AlexORocha** [comment]
Legal!

Obrigado, Edgard!

E uma última dúvida, como poderia deixar para exibir os logs apenas de um evento em específico, ex: onInterfaceChange ?

**Comment by edgardmessias** [comment]
Só implementar um log personalizado com o winston

**Comment by AlexORocha** [comment]
Perfeito, obrigado!
