### ISSUE TITLE
checkNumberStatus() returns false for valid numbers

### ISSUE THREAD

**Issue by renandecarlo** [wppconnect-team/wppconnect#1581]
## Description

`checkNumberStatus()` returns false for valid numbers on v1.23.0, WA-JS v2.22.2
Seems to work fine on v1.22.0 with both WA-JS v2.22.2 and v2.19.1

It seems to fail only when node process has been abruptly closed.
For instance, open the program, close it with "ctrl + c", or kill the process.
The next time you open it, checkNumberStatus() will fail.

If you close it through the WhatsApp Web window instead, then it works fine.

## Environment

- **WPPConnect version(s):** 1.23.0
- **WA-JS version(s):** 2.22.2
- **Browser:** Chrome 111.0.5563.65
- **OS:** Windows 10
- **Node version:** v16.16.0
- **WhatsApp version:** 2.2307.10

## Steps to Reproduce

1. Open the program. Close it with "ctrl + c" or kill its process.
2. Open it again, `checkNumberStatus()` will fail for valid numbers.
3. Close it through WhatsApp Web window close button.
4. Open it up again, `checkNumberStatus()` will work fine.

## Additional context / Screenshot

Maybe something to do with #933e5d7?

**Comment by icleitoncosta** [comment]
Hello, today I tested it with several different DDDs, could you simulate or send a number that the error is happening to you to test and try a solution?

**Comment by renandecarlo** [comment]
@icleitoncosta Yes, I've recorded the behavior. It seems to do it with any number really. I grabbed a random one.
It seems to do it only if you immediately call for `checkNumberStatus()` after client initialization. Then it doesn't work at all, even after full wpp load.


https://user-images.githubusercontent.com/6974980/227604615-fc24347a-7f80-437e-9010-a00110fc9f11.mp4


````js
// Code used:
const wppconnect = require('@wppconnect-team/wppconnect');

(async () => {
	try {
		client = await wppconnect.create({
			session: 'bug_test', 
			headless: false, 
		})

        const check = async () => {
            try {
                const result = await client.checkNumberStatus(`593968125586@c.us`)
        
                console.log(result)
        
            } catch(err) { 
                console.error(err)
            }
        }

        check()
        setTimeout(check, 1000 * 10)

	} catch(err) {
		console.error(err)
	}
})()
````

**Comment by icleitoncosta** [comment]
Thank you very much for the video, I will do some tests now.

**Comment by icleitoncosta** [comment]
> Thank you very much for the video, I will do some tests now.

So this is happening because it's calling the function, before being logged in. 
Wait for the inChat event, and after that execute the calls.

**Comment by renandecarlo** [comment]
I see. However, `inChat` seems to trigger once even before it's logged in. Is there any other event I can listen?
The same code also seemed to work on previous versions just as fine.

For instance, here's the log:
````
info:     
  _       ______  ____  ______                            __
  | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
  | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
  | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_
  |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
info:     Checking for updates
info:     You're up to date
info:     [bug_test:browser] Using browser folder 'C:\Websites\aiqfome\geraldin-bot\bug_test\tokens\bug_test'
info:     [bug_test:browser] Initializing browser...
http:     [bug_test:browser] checking headless...
http:     [bug_test:browser] headless option is disabled, browser visible
info:     [bug_test:client] Initializing...
verbose:  [bug_test:client] Setting WhatsApp WEB version to 2.2307.x
http:     [bug_test:client] Waiting page load
verbose:  [bug_test:client] Loading WhatsApp WEB
verbose:  [bug_test:client] WhatsApp WEB loaded
verbose:  [bug_test:page] Page loaded
verbose:  [bug_test:client] Injecting wapi.js
verbose:  [bug_test:client] wapi.js injected
http:     [bug_test:client] Connected
-> Session change: inChat
debug:    [bug_test:client] Exposing onMessage function
info:     [bug_test:client] WhatsApp WEB version: 2.2307.10
info:     [bug_test:client] WA-JS version: 2.22.2
debug:    [bug_test:client] Exposing onAnyMessage function
debug:    [bug_test:client] Exposing onAck function
debug:    [bug_test:client] Exposing onNotificationMessage function
debug:    [bug_test:client] Exposing onParticipantsChanged function
debug:    [bug_test:client] Exposing onStateChange function
debug:    [bug_test:client] Exposing onStreamChange function
debug:    [bug_test:client] Exposing onIncomingCall function
http:     [bug_test:client] Checking is logged...
info:     [bug_test:client] Auto close configured to 60s
http:     [bug_test:client] Authenticated
-> Session change: isLogged
debug:    [bug_test:client] Exposing onInterfaceChange function
debug:    [bug_test:client] Exposing onPresenceChanged function
debug:    [bug_test:client] Exposing onLiveLocation function
debug:    [bug_test:client] Exposing onAddedToGroup function
debug:    [bug_test:client] Exposing onRevokedMessage function
debug:    [bug_test:client] Exposing onReactionMessage function
debug:    [bug_test:client] Exposing onPollResponse function
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: SYNCING (CONNECTING)
info:     [bug_test:client] Auto close configured to 180s
http:     [bug_test:client] Checking phone is connected...
debug:    [bug_test:client] Registering onStateChange event
checkNumberStatus() {
  id: '593968125586@c.us',
  isBusiness: false,
  canReceiveMessage: false,
  numberExists: false,
  status: 404
}
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: SYNCING (CONNECTING)
debug:    [bug_test:client] Emitting onStateChange event (1 registered)
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: SYNCING (CONNECTING)
debug:    [bug_test:client] Emitting onStateChange event (1 registered)
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: SYNCING (CONNECTING)
debug:    [bug_test:client] Emitting onStateChange event (1 registered)
checkNumberStatus() {
  id: '593968125586@c.us',
  isBusiness: false,
  canReceiveMessage: false,
  numberExists: false,
  status: 404
}
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: MAIN (NORMAL)
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: MAIN (NORMAL)
debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
http:     [bug_test:client] Current state: MAIN (NORMAL)
http:     [bug_test:client] Connected
-> Session change: inChat

````

**Comment by icleitoncosta** [comment]
> I see. However, `inChat` seems to trigger once even before it's logged in. Is there any other event I can listen? The same code also seemed to work on previous versions just as fine.
> 
> For instance, here's the log:
> 
> ```
> info:     
>   _       ______  ____  ______                            __
>   | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
>   | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
>   | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_
>   |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
> info:     Checking for updates
> info:     You're up to date
> info:     [bug_test:browser] Using browser folder 'C:\Websites\aiqfome\geraldin-bot\bug_test\tokens\bug_test'
> info:     [bug_test:browser] Initializing browser...
> http:     [bug_test:browser] checking headless...
> http:     [bug_test:browser] headless option is disabled, browser visible
> info:     [bug_test:client] Initializing...
> verbose:  [bug_test:client] Setting WhatsApp WEB version to 2.2307.x
> http:     [bug_test:client] Waiting page load
> verbose:  [bug_test:client] Loading WhatsApp WEB
> verbose:  [bug_test:client] WhatsApp WEB loaded
> verbose:  [bug_test:page] Page loaded
> verbose:  [bug_test:client] Injecting wapi.js
> verbose:  [bug_test:client] wapi.js injected
> http:     [bug_test:client] Connected
> -> Session change: inChat
> debug:    [bug_test:client] Exposing onMessage function
> info:     [bug_test:client] WhatsApp WEB version: 2.2307.10
> info:     [bug_test:client] WA-JS version: 2.22.2
> debug:    [bug_test:client] Exposing onAnyMessage function
> debug:    [bug_test:client] Exposing onAck function
> debug:    [bug_test:client] Exposing onNotificationMessage function
> debug:    [bug_test:client] Exposing onParticipantsChanged function
> debug:    [bug_test:client] Exposing onStateChange function
> debug:    [bug_test:client] Exposing onStreamChange function
> debug:    [bug_test:client] Exposing onIncomingCall function
> http:     [bug_test:client] Checking is logged...
> info:     [bug_test:client] Auto close configured to 60s
> http:     [bug_test:client] Authenticated
> -> Session change: isLogged
> debug:    [bug_test:client] Exposing onInterfaceChange function
> debug:    [bug_test:client] Exposing onPresenceChanged function
> debug:    [bug_test:client] Exposing onLiveLocation function
> debug:    [bug_test:client] Exposing onAddedToGroup function
> debug:    [bug_test:client] Exposing onRevokedMessage function
> debug:    [bug_test:client] Exposing onReactionMessage function
> debug:    [bug_test:client] Exposing onPollResponse function
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: SYNCING (CONNECTING)
> info:     [bug_test:client] Auto close configured to 180s
> http:     [bug_test:client] Checking phone is connected...
> debug:    [bug_test:client] Registering onStateChange event
> checkNumberStatus() {
>   id: '593968125586@c.us',
>   isBusiness: false,
>   canReceiveMessage: false,
>   numberExists: false,
>   status: 404
> }
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: SYNCING (CONNECTING)
> debug:    [bug_test:client] Emitting onStateChange event (1 registered)
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: SYNCING (CONNECTING)
> debug:    [bug_test:client] Emitting onStateChange event (1 registered)
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: SYNCING (CONNECTING)
> debug:    [bug_test:client] Emitting onStateChange event (1 registered)
> checkNumberStatus() {
>   id: '593968125586@c.us',
>   isBusiness: false,
>   canReceiveMessage: false,
>   numberExists: false,
>   status: 404
> }
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: MAIN (NORMAL)
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: MAIN (NORMAL)
> debug:    [bug_test:client] Emitting onInterfaceChange event (1 registered)
> http:     [bug_test:client] Current state: MAIN (NORMAL)
> http:     [bug_test:client] Connected
> -> Session change: inChat
> ```

I will check and fix this early inChat that is occurring, probably the change should prove directly from whatsapp web to have changed something.

**Comment by renandecarlo** [comment]
Great, thanks! I've no idea why it works just fine when it's properly closed though. As it did in previous versions.
I could temporarily fix it calling `checkNumberStatus()` after:
````
if(statusSession == 'inChat' && typeof client !== 'undefined')
````
On the first `inChat` event it seems `client` is not yet created. So it works for the second one.

I'm not sure how wppconnect inner works, but It'd be great if we also could have access to the interface/socket state, so we could listen for `CONNECTED`/`NORMAL` states.

**Comment by icleitoncosta** [comment]
> Great, thanks! I've no idea why it works just fine when it's properly closed though. As it did in previous versions. I could temporarily fix it calling `checkNumberStatus()` after:
> 
> ```
> if(statusSession == 'inChat' && typeof client !== 'undefined')
> ```
> 
> On the first `inChat` event it seems `client` is not yet created. So it works for the second one.
> 
> I'm not sure how wppconnect inner works, but It'd be great if we also could have access to the interface/socket state, so we could listen for `CONNECTED`/`NORMAL` states.

Thanks for the contribution, but I've already released a fix, I'm going to release the release of it.

https://github.com/wppconnect-team/wppconnect/commit/4900765f20a7c879e597ce01ebcce05bf244006b

**Comment by icleitoncosta** [comment]
I will mark the issue as resolved, and only run the calls after inChat, if you need to, you can reopen it.
