### ISSUE TITLE
sendText with buttons useTemplateButtons: false, dont work on android normal whatsapp 

### ISSUE THREAD

**Issue by aureodiasneto** [wppconnect-team/wppconnect#1585]
im using the latest version 1.2.3, and it only show the buttons on web, ios and android business app, the normal app dont show the buttons.

how to deal with that?

**Comment by edgardmessias** [comment]
This is a known issue, but there's nothing that we can do about it, because it's a WhatsApp limitation.

**Comment by aureodiasneto** [comment]
very random, without even updating the app sometimes it works and sometimes it doesn't.

**Comment by ozozozd** [comment]
@edgardmessias thank you so much for the great work you guys are doing! I hope it doesn't feel like thankless work.

Do you think it's a bug they are going to fix? Or should we be worried that it'a a feature they are testing as a way to prevent button template messages from being seen unless they are sent using the WhatsApp Business API?

muito obrigado pelo seu trabalho, e muito amor a trancoso!

**Comment by edgardmessias** [comment]
@ozozozd , there are a lot of people trying to figure out how to send the buttons, I always stay contacting them.

In parallel, I'm investigating call features, like offer, accept, end....

**Comment by CaduhDEV** [comment]
se utilizar os templates button, funciona normalmente ? alguns dos clientes do meu bot não consegue vizualizar os botões.

**Comment by edgardmessias** [comment]
@CaduhDEV , não está funcionando nenhum tipo de botão. A Meta bloqueou todos tipos no momento.

**Comment by aureodiasneto** [comment]
Do you think that now buttons will work only through the official api?

**Comment by CaduhDEV** [comment]
Aparentemente usuários que não são usuários beta do whatsapp não são compatíveis com as mensagens de botões, posso estar errado, mas testei em 1 whatsapp com beta access e funciona normalmmente, e no sem beta n funciona.

**Comment by marcelomedina22** [comment]
Buttons (not template)  & send-list are displaying on iOS devices, also web. This issue is happing android version higher than 2.23.3.15. Seems like a meta changed their attributes. I don't think this a block by Meta, otherwise iOS will not working as well, also most their coder are US based, so iPhone users.

**Comment by CaduhDEV** [comment]
se alguém descobrir como monta o objeto de botões atualizados favor avisar aqui, estou numa busca de descobrir como posso montar os botões compativeis com android superior a 2.23.3.15 @marcelomedina22

**Comment by Inevitable-Dev** [comment]
@CaduhDEV I came in the comments of another API that in the object of the button msg sent by the Official WhatsApp API seems to have a new Key called "recipientKeyHash" that seems to always receive a random code value that looks like this: 
`"recipientKeyHash": "nopVs9S5HXw9mg=="`

There is still no understanding of how this value is Generated.

**Comment by lucazin** [comment]
Some alternatives than send-buttons ?

**Comment by lucazin** [comment]
> @CaduhDEV , não está funcionando nenhum tipo de botão. A Meta bloqueou todos tipos no momento.

Funciona apenas da API Oficial?

**Comment by CaduhDEV** [comment]
@lucazin eu não sei bem oq fazer, estou aguardando os desenvolvedores do wppconnect conseguir alguma alternativa para isso, enquanto isso o melhor metodo seria o antigo: responder as perguntas do bot usando numeros:

digite 1 para fazer isso
digite 2 para fazer aquilo

**Comment by lucazin** [comment]
Vou ter que mudar toda lógica.

Em sáb., 25 de mar. de 2023 14:58, CaduhDEV ***@***.***>
escreveu:

**Comment by raajrush** [comment]
One of the developers at Baileys has found a solution and will be sending a pull request shortly.

**Comment by manish-snappe** [comment]
Any headway on this @raajrush ?

**Comment by roysG** [comment]
Any update? @raajrush

**Comment by edgardmessias** [comment]
I did it on WA-JS

> One of the developers at Baileys has found a solution and will be sending a pull request shortly.

**Comment by roysG** [comment]
When this update should be also implemented in this library? @edgardmessias

**Comment by edgardmessias** [comment]
Closed at https://github.com/wppconnect-team/wppconnect/releases/tag/v1.23.2

**Comment by manish-snappe** [comment]
I updated to 1.23.2, still buttons are not working @edgardmessias

**Comment by edgardmessias** [comment]
@manish-snappe , are you using business account? If yes, this will never work, the Meta is blocking message buttons from business account and they probally will block with normal accounts too

**Comment by lucazin** [comment]
Lists are working?

Em ter., 4 de abr. de 2023 14:03, Edgard Lorraine Messias <
***@***.***> escreveu:

**Comment by edgardmessias** [comment]
@lucazin , is working for some accounts

**Comment by lucazin** [comment]
Do you believe, list will still working?
Because a will change the application to use just lists without buttons.

Em ter., 4 de abr. de 2023 14:06, Edgard Lorraine Messias <
***@***.***> escreveu:

**Comment by roysG** [comment]
The problem still exists also in latest version.

I see the buttons only on the web. not on iphone or android.

Is there any change that needs to do to in the function himself or in the command that we call it?

**Comment by marcelomedina22** [comment]
Eu reparei que o wppconnect usa apenas o templatebutton, o templatebutton não funcionava antes. No iPhone.

Eu usava uma versão modificada do myzap que estava a versão legacy dos buttons, anterior a templateButton enviava normalmente parou no mesmo dia que sendlist parou. Acredito que deva precisar da mesma atualização. Porém usar a versão legacy dos buttons, sem template. Seria possível usar duas rotas oara legacy button e templatebutton?

Alguém marca o edgar por gentileza.

**Comment by edgardmessias** [comment]
@marcelomedina22 , por padrão o tipo dos botões é automático.

Se você colocar botão de URL ou Ligação, automaticamente é template, caso contrário, ele usa o meio antigo
