### ISSUE TITLE
WPP is restarting autometically

### ISSUE THREAD

**Issue by danuwardinesh** [wppconnect-team/wppconnect#1603]
Ubuntu 20.04
Node 18.7.0

WPPConnect version(s): 1.23.0
WA-JS version(s): 2.17.0
Browser: Chromium 0.15.1
OS: Ubuntu 20.04
Node version: 18.7.0
WhatsApp version: 2.2230.9
MultiDevice (BETA): yes

1. WPP is restarting autometically when it has traffic like 100 messages in queue 
2. VM CPU is normal like 20-30% in use 
3. Available Memory : 18Gb is showing 
![WPP-Restart](https://user-images.githubusercontent.com/104440840/228247377-4c3bcc2c-69d0-4e95-b8b2-aee16921e647.JPG)

**Comment by icleitoncosta** [comment]
Hello, please update WAJS and WppConnect to the latest version, observer the logger when the error occurs.

**Comment by danuwardinesh** [comment]
hi, @icleitoncosta can you recommend us what is the best version should I use. for WA-JS and WppConnect 

because WppConnect that I am using is 1.23.1 right now.

**Comment by icleitoncosta** [comment]
It is always ideal to use the latest versions.

In your specific case, the version that is set for WhatsApp is very old and no longer supported. Fix a more recent version, such as 2.2310.x, which is probably causing the automatic restarts.

You can check the active versions of WhatsApp here:
https://wppconnect.io/whatsapp-versions

**Comment by danuwardinesh** [comment]
@icleitoncosta I have update the @wppconnect/wa-js package and the whatsapp-version still shows like this: 
![image](https://user-images.githubusercontent.com/104440840/230871236-26d100d3-163f-4426-8187-d2dcfdf402e1.png)

**Comment by icleitoncosta** [comment]
Not this files, please on create function set the whatsapp version:

```
create({
    session: 'nameSession',
    whatsAppVersion: '2.2311.x
});
```
