### ISSUE TITLE
checkNumberStatus is returning false even for a valid number

### ISSUE THREAD

**Issue by manish-snappe** [wppconnect-team/wppconnect#1604]
While checking if a number is valid using checkNumberStatus, we are sometimes getting false (invalid number). Even for a valid WhatsApp number. After restart, it gives a true response. For the same number

**Comment by manish-snappe** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/68492452/228301645-d621563f-1460-438a-af3f-7530f62df743.png">
Reference response

**Comment by Saifallak** [comment]
isnt this fixed by (https://github.com/wppconnect-team/wa-js/commit/556a97ff31b2d1961a5e5e5ec61a6e13441dd4d6) ?

**Comment by antirek** [comment]
same problem
wa.js 2.23.2
wppconnect 1.23.2
chrome 110

@edgardmessias Edgar, please, comment https://github.com/wppconnect-team/wa-js/blob/556a97ff31b2d1961a5e5e5ec61a6e13441dd4d6/src/contact/functions/queryExists.ts#L111 
after 15 secs can repeat check number exists and request will be to whatsapp server but not cache?

**Comment by edgardmessias** [comment]
@antirek , yes, this is the idea, I tried to avoid some ban with repetitive error

**Comment by mahmouds12** [comment]
same here
