### ISSUE TITLE
Unable to install Library because of powershell error

### ISSUE THREAD

**Issue by MazanLabeeb** [wppconnect-team/wppconnect#1605]
## Description

When I run command "npm i --save @wppconnect-team/wppconnect", it failed with the following error:

npm ERR! command failed

npm ERR! command powershell -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy

npm ERR! The token '&&' is not a valid statement separator in this version.

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX 
- **OS:** Windows X 
- **Node version:** Node 16.13.2
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. run command 
npm i --save @wppconnect-team/wppconnect

## Log Output

```
npm ERR! code 1
npm ERR! path D:\Orders\Upwork\Simon\node_modules\sharp
npm ERR! command failed
npm ERR! command powershell -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! At line:1 char:26
npm ERR! + -- (node install/libvips && node install/dll-copy && prebuild-install ...
npm ERR! +                          ~~
npm ERR! The token '&&' is not a valid statement separator in this version.
npm ERR! At line:1 char:51
npm ERR! + -- (node install/libvips && node install/dll-copy && prebuild-install ...
npm ERR! +                                                   ~~
npm ERR! The token '&&' is not a valid statement separator in this version.
npm ERR! At line:1 char:101
```

## Additional context / Screenshot

<img width="584" alt="Untitled" src="https://user-images.githubusercontent.com/22959243/228427462-cc76109a-b3ca-431f-9b85-0269921003ba.png">

**Comment by renat473** [comment]
could you try to fix this maybe it will help with your problem

this is linked to a problem of nodejs itself

https://weekendprojects.dev/posts/fix-for-npm-sharp-command-failed-error/

**Comment by icleitoncosta** [comment]
As @renat473 has already informed, this is a known error in Node.js, and typically clearing the cache of NPM (or Yarn) resolves the issue.

I'm closing the issue.
