### ISSUE TITLE
Dúvida: requisitos mínimos

### ISSUE THREAD

**Issue by AlexORocha** [wppconnect-team/wppconnect#1608]
Bom dia!

Perdão por enviar por aqui a dúvida, o link do Discord não está funcionando.

Vocês possuem algum descritivo dos requisitos mínimos de OS para executar o projeto?

Abs!

**Comment by renat473** [comment]
Olá , 4 cores de VCPU com 6G de ram,

dúvidas no discord ou no grupo do whatsapp , https://discord.com/invite/JU5JGGKGNG
