### ISSUE TITLE
how detect user if "online"

### ISSUE THREAD

**Issue by witchfindertr** [wppconnect-team/wppconnect#1624]
how detect user if "online" this is possible for wppconnect?

**Comment by icleitoncosta** [comment]
Hello, yes. It is possible.
Check the event "onpresencechanged".

https://wppconnect.io/wppconnect/classes/Whatsapp.html#onPresenceChanged

Usage:

`
client.onPresenceChanged((event) => {
console.log(event.isOnline);
});
`
