### ISSUE TITLE
Is there any way to persist the session using redis?

### ISSUE THREAD

**Issue by DanielXavierJob** [wppconnect-team/wppconnect#1632]
I'm creating a multi device connection end-point with whatsapp using NestJs, but I'm not finding a way to persist whatsapp sessions in the framework, I believe there is some way using redis, but I haven't found anything yet

**Comment by icleitoncosta** [comment]
Do you want the sessions to automatically return when the server restarts (for example)?

If that's the case, you just need to use "create" and give it the same name as the previous session.

**Comment by DanielXavierJob** [comment]
Can I get message events just by specifying the name of the session I want to fetch?

**Comment by icleitoncosta** [comment]
> Can I get message events just by specifying the name of the session I want to fetch?

No, first create the session, and after use the client.onAnyMessage(message => console.log(message));

**Comment by icleitoncosta** [comment]
Hi @DanielXavierJob, i go close the issue, because i imagine was solved.
