### ISSUE TITLE
quotedMsgId is null and quotedMsg doesn't have id

### ISSUE THREAD

**Issue by usernein** [wppconnect-team/wppconnect#1634]
How can i get the id of a quoted message? The docs says to use quotedMsgId since quotedMsgObj is deprecated, but what i receive is a quotedMsg object that doesn't have any id:
![Screenshot from 2023-04-08 21-24-54](https://user-images.githubusercontent.com/29507335/230748031-463c39e6-b279-4f1a-b7ab-cd4d36a76868.png)

**Comment by Saifallak** [comment]
Try

```js
const quotedMsgId =
        messageObj.quotedParticipant == messageObj.from
          ? "false_" + messageObj.chatId + "_" + messageObj.quotedStanzaID
          : "true_" + messageObj.chatId + "_" + messageObj.quotedStanzaID;

```


Based on this message https://discord.com/channels/844351092758413353/844548322978037800/1087333558382764112


Or wait for https://github.com/wppconnect-team/wa-js/pull/1031

**Comment by icleitoncosta** [comment]
Hi, i close this issue because that is solved on last wa-js update.
