### ISSUE TITLE
status image

### ISSUE THREAD

**Issue by amiruldev20** [wppconnect-team/wppconnect#1636]
send image status not working. I tried to send a status text it worked fine. then i try to send image status why can't it work properly? the status cannot be seen by other people, but I checked on the wa web bot there is this status. response results
{
  id: 'true_status@broadcast_2AF4E9DCB00C75BE75C16D0E5153C741_6285157489446@c.us',
  ack: 1,
  sendMsgResult: {
    _flags: 269,
    _value: 'OK',
    _onFulfilled: {},
    _resolveLevel: 2,
    _thenableParent: null,
    _parent: {
      _flags: 13,
      _value: 'OK',
      _onFulfilled: {},
      _resolveLevel: 2,
      _thenableParent: null
    }
  }
}

**Comment by icleitoncosta** [comment]
Hi @amiruldev20, the send status image, text and video, is a alternative method to send status by the wa web, but how the wa web not have the function, maybe us not will get solve this issue in this moment.

**Comment by edgardmessias** [comment]
@icleitoncosta @amiruldev20 , wait for next version of WA-JS, that will be fixed
