### ISSUE TITLE
Buttons stopped working on iPhone and Web - in addition to Android

### ISSUE THREAD

**Issue by ozozozd** [wppconnect-team/wppconnect#1653]
## Description
Buttons don't show up on iPhone, Android or the Web anymore.

1.23.0 still sends the buttons to iPhone and Web.
1.23.2 took away to the buttons from iPhone and Web.

## Environment

- **WPPConnect version(s):** 1.23.0
- **WA-JS version(s):** 2.22.2
- **Browser:** Chromium
- **OS:** OSX 13.2.1
- **Node version:** v.18.14.0
- **WhatsApp version:** 2.2307.10
- **MultiDevice (BETA):** Yes

## Steps to Reproduce

1. Send a button message
2. Observe that on iPhone 8 Plus 15.5, WhatsApp 23.8.78 (latest) doesn't receive the message.
3. Observe that WhatsApp Web doesn't receive the message.

**Comment by owais-symtera** [comment]
facing same issue

**Comment by m-demetrio** [comment]
I have the same problem

**Comment by johnhoffmannsantos** [comment]
same problem here

**Comment by edgardmessias** [comment]
There are nothing to do about the buttons, because the Meta is blocking it.

We did it in the past because of some bug in the WhatsApp app, but they fixed it.
