### ISSUE TITLE
Message can not be sent  when load message  use loadAndGetAllMessagesInChat

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#166]
Message can not be sent  when loading message  use loadAndGetAllMessagesInChat function
I  load  message size  about 1100
Message be be sent after the data loaded

![image](https://user-images.githubusercontent.com/1323545/116516787-9c29a080-a900-11eb-8126-bb8afd87f36a.png)

**Comment by edgardmessias** [comment]
@Lucipher , could you provide an exemple of code?

**Comment by Lucipher** [comment]
var res = await client.loadAndGetAllMessagesInChat(chatId, true);
                        if (res && res.length > 0) {
                            console.log("message length",res.length)
                            for (const message of res) {
                                let msg = await Sessions.formatMsg(client, message, true)
                                if (!message.fromMe && message.isGroupMsg) {
                                    msg['from'] = message['author'];
                                    msg['to'] = message['from'];
                                }

                                msgs.push(msg);
                            }
                        }


@edgardmessias

**Comment by Lucipher** [comment]
@edgardmessias 

If the load number is more than 1000, it will get stuck and will not be able to send or receive messages
