### ISSUE TITLE
poll with only one choice option

### ISSUE THREAD

**Issue by meshesha** [wppconnect-team/wppconnect#1706]
## Description

when create poll with "Allow multiple answers" disabled  (for limit only to one choice) , the message appears as "unknown" type instead as "poll_creation" type.

## Environment

- **Wppconnect-server version(s):** [2.0.1]
- **Browser:** [Chrome 112.0.5615.49]
- **OS:** [ubuntu 20.4]
- **Node version:** [18.4.0]
- **WhatsApp version:** [2.23.7.78]
- **MultiDevice (BETA):** no

**Comment by icleitoncosta** [comment]
Hi, how is the code you try execute?

**Comment by edgardmessias** [comment]
This happen for old WhatsApp app version, with the current version, this will work.
