### ISSUE TITLE
error: client.removeParticipant() does not accept recent group IDs

### ISSUE THREAD

**Issue by ch4rliedev** [wppconnect-team/wppconnect#1709]
## Description

When trying to use "client.removeParticipant()" in the WPPConnect lib I get the error:
"error: [Boruto Raiden:client] Error: Chat 120363136981613165@g.us is not a group"

Even if that ID is a group. Reading the documentation, apparently the type of ID that is accepted has a hyphen in the middle of it, and in a quick search, old groups like 2017 have this ID, indicating that whatsapp has changed the way it identifies groups currently.

## Environment

- **WPPConnect version(s):** 1.25.0
- **WA-JS version(s):** 2.24.2
- **Browser:** Chromium XX
- **OS:** Windows 10 22H2 - 19045.3031
- **Node version:** Node 18.16.0
- **WhatsApp version:** 2.2307.10
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Just try to remove a member from a group using "client.removeParticipant(groupId, userId)"

## Log Output

error:    [Boruto Raiden:client] Error: Chat 120363136981613165@g.us is not a group

## Your Code

`await client.removeParticipant('120363136981613165@g.us', target.id_wpp_complete)` "target.id_wpp_complete" retorna "559999999@c.us"

## Additional context / Screenshot

![image](https://github.com/wppconnect-team/wppconnect/assets/88893508/02ce112b-49a7-4c79-b84a-3be9e4efd82d)

**Comment by icleitoncosta** [comment]
Hi @ch4rliedev, do you can test in the latest version?
