### ISSUE TITLE
Request of the function that makes the listen when the user enters and leaves the group

### ISSUE THREAD

**Issue by ikarofsouza** [wppconnect-team/wppconnect#171]
- Solicitação da função que faz o listen quando o usuário entra e sai do grupo, assim como a onMessage e onAnyMessage.

- Request of the function that makes the listen when the user enters and leaves the group, as well as onMessage and onAnyMessage.

![Screenshot2](https://user-images.githubusercontent.com/48399495/116792745-83fd8100-aaba-11eb-9814-b4dcb9d24fcd.png)

![Screenshot1](https://user-images.githubusercontent.com/48399495/116792746-84961780-aaba-11eb-9bc8-40bcc8a68f41.png)

**Comment by edgardmessias** [comment]
Hoje você pode fazer isso olhando o onMessage, e olhar para os atributos: isNotification, subtype e recipients
