### ISSUE TITLE
Error on sendLocation function

### ISSUE THREAD

**Issue by Rubens-Gasparotto** [wppconnect-team/wppconnect#1726]
## Description

The service get stucked when trying to send location message. I've tried to send using sendLocation("5515912345678@c.us", -23.478189, -47.424180, 'Prefeitura') and sendLocation("5515912345678@c.us", { latitude: -23.478189, longitude: -47.424180 })

## Environment

- **WPPConnect version(s):** 1.27.2
- **WA-JS version(s):** 2.24.2
- **Browser:** Chrome 114.0.5735.110
- **OS:** Windows 10
- **Node version:** Node 16.14.0
- **WhatsApp version:** 2.2307.10
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Call function sendLocation("5515912345678@c.us", -23.478189, -47.424180, 'Prefeitura')

## Log Output

error:   ┏ timeout +40s
error:   ┃ [1] Error: timeout
error:   ┃ [2]     at exports.toError (C:\Users\Rubens.Gasparotto\Documents\wpp-connect\node_modules\await-timeout\src\utils.js:20:38)
error:   ┃ [3]     at Timeout.fn [as _onTimeout] (C:\Users\Rubens.Gasparotto\Documents\wpp-connect\node_modules\await-timeout\src\index.js:32:46)
error:   ┃ [4]     at listOnTimeout (node:internal/timers:559:17)
error:   ┗ [5]     at processTimers (node:internal/timers:502:7)

## Additional context / Screenshot

![image](https://github.com/wppconnect-team/wppconnect/assets/54379903/209ac54e-a086-4221-bcca-a4d3e6db087e)

**Comment by edgardmessias** [comment]
Fixed with latest version of WA-JS: https://github.com/wppconnect-team/wa-js/releases/tag/v2.24.4

Note: This is a BUG from WhatsApp WEB, but we can work arround to fix it with wa-js
