### ISSUE TITLE
Error on WAPI.sendMessage

### ISSUE THREAD

**Issue by Khaldoun-Baz** [wppconnect-team/wppconnect#1730]
## Description

Facing error when when i m executing the WAPI.sendMessage

![error](https://github.com/wppconnect-team/wppconnect/assets/66871169/1bf054f7-d9e7-488c-8590-275ceb5dbc5d)

**Comment by Waley23** [comment]
to chrome web view how sir,, can you do it??

**Comment by ono77** [comment]
same problem with WAPI.sendMessage
