### ISSUE TITLE
get statusSession  as a function

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect#1738]
Hello , 
thank for great library I have a question about  statusSession , I need to get it as function , I tried client.getstatusSession or this.statusSession but it doesn't work can you help me on this thanks 

wppconnect.create({
    session: 'MySession', //Pass the name of the client you want to start the bot   
    statusFind: (statusSession, session) => {
      console.log('Status Session: ', statusSession);
}
....

**Comment by Rubens-Gasparotto** [comment]
Hello @mitnick2012

The function `wppconnect.create` will return a wpp session. With this session you can call `session.client.onStateChange`

`onStateChange` will send a event `SocketState` everytime the status has changed.

**Comment by mitnick2012** [comment]
@Rubens-Gasparotto  can you please specify how to implement that in a simple example thanks

**Comment by Rubens-Gasparotto** [comment]
@mitnick2012, sorry for answering so late

Here is what I did

I've created a variable to store some data of my session
```typescript
this.session = {
  name: SESSION_NAME,
  qrcode: null,
  client: null,
  state: SessionState.STARTING,
  wid: null
};
```
And the function to initialize session is this
```typescript
async initSession() {
  this.session.state = SessionState.STARTING;

  const client = await create(** creation options **);

  // The status take changes below
  this.session.client?.onStateChange((state) => {
    this.session.state = state;
  });

  return client;
}
```

And I set the client like this

```typescript
this.session.client = await this.initSession();
```

**Comment by mitnick2012** [comment]
it's good thanks for support.
