### ISSUE TITLE
Função getChatById não traz mais chat que não esteja em conversa.

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#1742]
Função getChatById não traz mais chat que não esteja em conversa/carregado no front.

- **WPPConnect version(s):** 1.27.3
- **WA-JS version(s):** 2.24.4
- **Browser:** Chrome 114
- **OS:** Windows 11
- **Node version:** Node 18
- **WhatsApp version:** 2.2307.x

**Comment by icleitoncosta** [comment]
Neste caso, você pode utilizar a função `getContact`
