### ISSUE TITLE
I have problem to get notification on my mobile after connecting my WhatsApp to WPP 

### ISSUE THREAD

**Issue by danuwardinesh** [wppconnect-team/wppconnect#1758]
is there any ways we can enable notification even after connect my WhatsApp to WPP because right now I am not able to get notification on my mobile 

Dependency versions
        "@wppconnect-team/wppconnect": "^1.27.3",
        "@wppconnect/wa-js": "^2.23.1",
        "mkdirp": "^3.0.1",
        "mongoose": "^6.10.0",
        "node-redis-pubsub": "^5.0.0",
        "pm2": "^3.5.1",
        "uuid": "^9.0.0",
        "whatsapp-web.js": "^1.19.5",
        "winston": "^3.8.2"
        "pm2-slack": "^1.1.0"

**Comment by icleitoncosta** [comment]
Unfortunately, this is an "issue" with WhatsApp itself, and currently, there isn't a solution that we can provide.
