### ISSUE TITLE
send param on send message method and get it back on the webhook 

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect#1771]
Hello Team,
is there any way to send a custom param on send message Api and get this param back on webhook response, I tried that but didn't get the new param on webhook response.
thanks

**Comment by mitnick2012** [comment]
any solution to that, geeks ?

**Comment by icleitoncosta** [comment]
Hello, currently there is no way to do this, but could you provide more details about what you need to do? Depending on that, there might be another solution.

Regarding the webhook, the library doesn't have a webhook, only the wppconnect-server.

**Comment by icleitoncosta** [comment]
I will close an issue as it is out of iteration.
