### ISSUE TITLE
Reaction Message not working

### ISSUE THREAD

**Issue by ojauumdev** [wppconnect-team/wppconnect#1772]
Estou tentando fazer um post para /react-message

com o body:

{
  "messageId": "25847646066702151775",
  "reaction": "👍"
}

Mas recebo o erro:

![image](https://github.com/wppconnect-team/wppconnect/assets/115158157/dc324ad3-5ee5-4a8b-9984-1e4655113f15)

**Comment by mendoncart** [comment]
Eu também estou com o mesmo problema.

**Comment by ojauumdev** [comment]
Alguem conseguiu resolver o problema de reagir mensagem?

**Comment by ojauumdev** [comment]
![image](https://github.com/wppconnect-team/wppconnect/assets/115158157/7e003e15-9919-44e4-876b-63c42ae3fef7)

Not Working

**Comment by icleitoncosta** [comment]
Olá @ojauumdev, essa issue seria no server, mas já foi resolvida, era um erro no Swagger. 
Ao invés de messageId, o correto seria msgId.

Att,
