### ISSUE TITLE
npm run build is not working

### ISSUE THREAD

**Issue by JuliaCristine** [wppconnect-team/wppconnect#1774]
<img width="887" alt="image" src="https://github.com/wppconnect-team/wppconnect/assets/17750415/f8f3314b-b125-407e-bfbb-f5071b66e21d">

**Comment by franciscoeymardneto** [comment]
Hi, do you still having this issue? Try to get the lastest version of the project.

**Comment by icleitoncosta** [comment]
Hello @JuliaCristine, I imagine you've already resolved this, so I'll keep the issue closed. If you need any further details, feel free to reopen it.
