### ISSUE TITLE
Session disconnected over time

### ISSUE THREAD

**Issue by felipemmachado** [wppconnect-team/wppconnect#1781]
Hello, I'm testing de wppconnect and I connect my session on lib, 

over time, and over time and inactivity, the connection is terminated.

Is there a possibility to keep the session connected?

![image](https://github.com/wppconnect-team/wppconnect/assets/5105157/efb87bd8-c406-4000-891b-c9b0f56d59c3)

The log of close session.

Can someone help me?

**Comment by zindi-br** [comment]
@felipemmachado  O aparelho que esta tentando coenctar é IOS?

**Comment by felipemmachado** [comment]
> @felipemmachado O aparelho que esta tentando coenctar é IOS?

Sim sim.

**Comment by felipemmachado** [comment]
Você conseguiu contornar esse bug de alguma forma?

**Comment by zindi-br** [comment]
Eu testei um aparelho iphone diferente e não desconectou. Mas um outro aparelho ele desconecta logo apos colher o qcorde. Retornou esse log antes de desconectar

`error: 2023-08-18T13:23:57.805Z WAPI is not defined - Error: WAPI is not defined
    at /usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/usr/src/wpp-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fusr%2Fsrc%2Fwpp-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
info:     [autoescolalideranca-zindi-1:session] Session Unpaired
info: 2023-08-18T13:24:02.024Z desconnectedMobile`

**Comment by manish-snappe** [comment]
Frequency of the disconnect has increased recently. It does not disconnect immediately but happens after a few days. Even if there is a good activity happening on the number. And it is independent of iOS or Android

**Comment by dcrec1** [comment]
Im having the same issue, disconnection has increased.

**Comment by fredEbho** [comment]
What's really going on? This is a major happening too frequently now

**Comment by icleitoncosta** [comment]
Olá, na semana passada estava tendo esse erro, mas já foi resolvido, parecia uma issue do proprio  WhatsApp. 
Após atualizarem o projeto, já testaram se o erro persiste?

**Comment by felipemmachado** [comment]
Pra mim resolveu.
