### ISSUE TITLE
RESPONDENDO MENSAGENS MUITO ANTIGAS  onMessage!

### ISSUE THREAD

**Issue by LuizVeloso10** [wppconnect-team/wppconnect#1784]
**Pessoal bom dia, alguem ai passou por um problema com a funcao onMessage:**

O que acontece e que quando inicio ela, e que a funcao considera  eventos antigos ou seja conversas muito antigas, tratando quando eu estivesse recebendo a mensagem agora, alguem ja passsou por isso ?
.

---

- Documentation: https://wppconnect.io/wppconnect/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by dequister** [comment]
Sim, resolvi colocando:  message.isNewMsg

**Comment by LuizVeloso10** [comment]
Obrigado @dequister, vou da uma olhada no parâmetro, havia tentado com timestamp, porem o timestamp é sempre o atual, muito obrigado!
