### ISSUE TITLE
Como consigo salvar o token para quando eu parar o bot ele nao pedir o token novamente?

### ISSUE THREAD

**Issue by dequister** [wppconnect-team/wppconnect#1791]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://wppconnect.io/wppconnect/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by icleitoncosta** [comment]
Olá @dequister, para você recuperar a sessão você apenas precisa salvar o nome da sessão, e passar ela no create, então, de qualquer forma, um arquivo json, uma database, algum link externo, enfim... 

Agora, se você quer dizer os dados, é só salvar a pasta userDataDir (no caso é necessário deixa ela sempre salva, pois é ali que ficam a maior parte dos dados da sessão).

Att,

**Comment by dequister** [comment]
> 

ja estou passando no puppeteeroptions e mesmo assim nao funciona:
puppeteerOptions: {
userDataDir: .tokens/fila${fila},
headless: true,
args: [
'--no-sandbox',
'--disable-setuid-sandbox',
'--disable-dev-shm-usage',
'--disable-accelerated-2d-canvas',
'--no-first-run',
'--no-zygote',
'--single-process', // <- this one doesn't works in Windows
'--disable-gpu'
]
},

**Comment by dequister** [comment]
> Olá @dequister, para você recuperar a sessão você apenas precisa salvar o nome da sessão, e passar ela no create, então, de qualquer forma, um arquivo json, uma database, algum link externo, enfim...
> 
> Agora, se você quer dizer os dados, é só salvar a pasta userDataDir (no caso é necessário deixa ela sempre salva, pois é ali que ficam a maior parte dos dados da sessão).
> 
> Att,


ja estou passando no puppeteeroptions e mesmo assim nao funciona:
puppeteerOptions: {
userDataDir: '.tokens/wpp1',
headless: true,
args: [
'--no-sandbox',
'--disable-setuid-sandbox',
'--disable-dev-shm-usage',
'--disable-accelerated-2d-canvas',
'--no-first-run',
'--no-zygote',
'--single-process', // <- this one doesn't works in Windows
'--disable-gpu'
]
},
