### ISSUE TITLE
IDBDatabase erro

### ISSUE THREAD

**Issue by djphi** [wppconnect-team/wppconnect#1798]
Ando recebendo esse erro ao tentar enviar uma mensagem "Error [InvalidStateError]: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.". O que pode estar causando?

**Comment by icleitoncosta** [comment]
> Ando recebendo esse erro ao tentar enviar uma mensagem "Error [InvalidStateError]: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.". O que pode estar causando?

Olá, podem ser varios erros, mas creio que seja algo na configuração do seu servidor. Ele tem memória e processador suficientes?

**Comment by djphi** [comment]
Sim, minha máquina tem um Ryzen 7 5800x e 16gb de ram.

**Comment by icleitoncosta** [comment]
> Sim, minha máquina tem um Ryzen 7 5800x e 16gb de ram.

Faz o seguinte, passa no create, a configuração do log: 'silly', e quando o erro ocorrer, coloca o log completo aqui
