### ISSUE TITLE
return empty sender object

### ISSUE THREAD

**Issue by edupoli** [wppconnect-team/wppconnect#18]
Upon returning the message, the sender object is empty, and therefore it is not possible to obtain the url of the user's profile photo.
![sender](https://user-images.githubusercontent.com/30879448/109323460-3fdbcf00-7832-11eb-89e6-025633f1690f.png)

**Comment by edgardmessias** [comment]
Closed in https://github.com/wppconnect-team/wppconnect/commit/ca5f6efea3bfcb6b58acd949d2d9035d1088de4f
