### ISSUE TITLE
Getting 'chat_not_found' error while trying to get the group members and also with the other group functions

### ISSUE THREAD

**Issue by iamkunal9** [wppconnect-team/wppconnect#1815]
facing the error while trying to getgroupmembers

` return Promise.resolve(WPP.group.getParticipants(groupId)).then(function (participants) { return participants.map(function (p) { return p.id; }); });
                    } {
  code: 'chat_not_found',
  id: 'XXXXXXXXXXXXXX@c.us'
}`

**Comment by iamkunal9** [comment]
> facing the error while trying to getgroupmembers
> 
> ` return Promise.resolve(WPP.group.getParticipants(groupId)).then(function (participants) { return participants.map(function (p) { return p.id; }); }); } { code: 'chat_not_found', id: 'XXXXXXXXXXXXXX@c.us' }`

Using the latest version of wpp!

**Comment by icleitoncosta** [comment]
Hello, I was trying to reproduce the error to fix it; however, the error does not occur on my device. Could you please send me the group ID and provide more information?

Include the LIB version, Whatsapp Web version, WA-JS version, etc.

If possible, update to the latest version and check if the error still occurs. Please give us feedback here.
