### ISSUE TITLE
Get the phone number linked to the session

### ISSUE THREAD

**Issue by juankbenavidess** [wppconnect-team/wppconnect#1837]
I have used getHostDevice hoping to obtain the phone number linked to the session but it simply returns the following information: {"id":"1","platform":"iphone","smbTos":0,"pushname":"JB ","stale":false,"blockStoreAdds":false,"isVoipInitialized":false}.
I've researched other features, but no results.

**Comment by juankbenavidess** [comment]
I used getWid

**Comment by mithun35h** [comment]
+1

**Comment by edgardmessias** [comment]
Yes, you need to use getWid
