### ISSUE TITLE
Função: getAllTransmission and getAllUserTransmission

### ISSUE THREAD

**Issue by wenioferraz** [wppconnect-team/wppconnect#184]
Olá Equipe, 
Existe a possibilidade de criar a função de listar todas as listas de transmissões ?

1. Pegar todas as listas do contato (se possível mostrar informações dela, name, img, id ... )
2. Pegar todos os contatos que está dentro da lista de transmissão (semelhante ao **Contact** já existente)

OBS: Não sei se é cabível, mais também poder gerenciar as transmissões, changeName, changePic, addUser e removeUser

**Comment by edgardmessias** [comment]
A transmissão é um tipo de grupo, logo todas funções do grupo podem alterar dados da transmissão.

Criei a função `getAllBroadcastList` para retornar apenas listas de transmissão.

Obs.: Ainda não lançado, apenas na nightly
