### ISSUE TITLE
WAPI.SendFile / SendImage not working

### ISSUE THREAD

**Issue by ono77** [wppconnect-team/wppconnect#1846]
With last WA update verison 2.2340.9
the functions WAPI.sendImage and WAPI.sendFile are not working
In the browser console I see this error: 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isNewsletter')
    at t.getMaxNumberSelectableMedia (app.f8ceec360734d3a1abb3.js:51:662539)
    at app.f8ceec360734d3a1abb3.js:96:851568
    at Generator.next (<anonymous>)
    at t (vendor1~app.7f14216f970118f62a35.js:2:66483)
    at s (vendor1~app.7f14216f970118f62a35.js:2:66694)
    at vendor1~app.7f14216f970118f62a35.js:2:66753
    at new Promise (<anonymous>)
    at vendor1~app.7f14216f970118f62a35.js:2:66634
    at M.processAttachments (app.f8ceec360734d3a1abb3.js:96:852098)
    at d (<anonymous>:6:25287)

**Comment by icleitoncosta** [comment]
> With last WA update verison 2.2340.9 the functions WAPI.sendImage and WAPI.sendFile are not working In the browser console I see this error:
> 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isNewsletter') at t.getMaxNumberSelectableMedia (app.f8ceec360734d3a1abb3.js:51:662539) at app.f8ceec360734d3a1abb3.js:96:851568 at Generator.next () at t (vendor1~app.7f14216f970118f62a35.js:2:66483) at s (vendor1~app.7f14216f970118f62a35.js:2:66694) at vendor1~app.7f14216f970118f62a35.js:2:66753 at new Promise () at vendor1~app.7f14216f970118f62a35.js:2:66634 at M.processAttachments (app.f8ceec360734d3a1abb3.js:96:852098) at d (:6:25287)


I tried to execute the methods in question, but they work correctly, even using the specified version.
Are you really using the wppconnect project?

**Comment by icleitoncosta** [comment]
> With last WA update verison 2.2340.9 the functions WAPI.sendImage and WAPI.sendFile are not working In the browser console I see this error:
> 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isNewsletter') at t.getMaxNumberSelectableMedia (app.f8ceec360734d3a1abb3.js:51:662539) at app.f8ceec360734d3a1abb3.js:96:851568 at Generator.next () at t (vendor1~app.7f14216f970118f62a35.js:2:66483) at s (vendor1~app.7f14216f970118f62a35.js:2:66694) at vendor1~app.7f14216f970118f62a35.js:2:66753 at new Promise () at vendor1~app.7f14216f970118f62a35.js:2:66634 at M.processAttachments (app.f8ceec360734d3a1abb3.js:96:852098) at d (:6:25287)

Environment
**WPPConnect version(s): ?
Browser: ?
OS: ?
Node version: ?
**WhatsApp version:** ?

**Comment by icleitoncosta** [comment]
I will close the issue, without reply by author.

**Comment by ono77** [comment]
I fixed inverting the order of the last two arguments in the processFiles function in /process-files.js

Changed this code:
```
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob,
          };
        }),
    chat,
    1
  );
  return mediaCollection;
}
```

to this

```
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob,
          };
        }),
    1,
    chat
  );
  return mediaCollection;
}
```
