### ISSUE TITLE
Clear cache and clear cookie

### ISSUE THREAD

**Issue by momokang** [wppconnect-team/wppconnect#1873]
I'm running the app with pm2, but it looks like after awhile, the ram usage will be very high, I suspect it's due to cache and cookie, my current solution is close the browser and run it again every 2 hours, but it is wrong because close the browser randomly might break the transaction.

I like to request (or if there is existing function), to able to clear cache and cookie,
I think it should can be clear on puppeteer ?

I had declared puppeteer options like this

> 
session: 'session',
			puppeteerOptions: {
				args: [
					"--disable-web-security",
					"--no-sandbox",
					"--disable-setuid-sandbox",
					"--disable-web-security",
					"--aggressive-cache-discard",
					"--disable-cache",
					"--disable-application-cache",
					"--disable-offline-load-stale-cache",
					"--disk-cache-size=0",
					"--disable-background-networking",
					"--disable-default-apps",
					"--disable-extensions",
					"--disable-sync",
					"--disable-translate",
					"--hide-scrollbars",
					"--metrics-recording-only",
					"--mute-audio",
					"--no-first-run",
					"--safebrowsing-disable-auto-update",
					"--ignore-certificate-errors",
					"--ignore-ssl-errors",
					"--ignore-certificate-errors-spki-list",
					'--use-gl=egl'
				],
				userDataDir: './tokens/session',
				executablePath: executablePath()
			},

But the RAM is still going-up and increasing and it will cause user session logout, is there any solution?
Perhaps something like, wppconnection.clearCookie()
Thanks.

**Comment by momokang** [comment]
Update: I tried pm2 garbage collection global.gc()
https://stackoverflow.com/questions/28522163/node-js-memory-leak-with-pm2

But unfortunately, it will reload the browser and relogin (Which is not I wanted)
Still seeking for memory leak solution.

**Comment by JoaoVitor2310** [comment]
> Update: I tried pm2 garbage collection global.gc() https://stackoverflow.com/questions/28522163/node-js-memory-leak-with-pm2
> 
> But unfortunately, it will reload the browser and relogin (Which is not I wanted) Still seeking for memory leak solution.

Any new ideas? I'm going through the same problem

**Comment by kkedia803** [comment]
Did you solve this issue??

**Comment by momokang** [comment]
Nope, I restart the web every 3-4 hours.

**Comment by icleitoncosta** [comment]
I am working on version 2, which includes some functions to save resources, a way to avoid storing all messages within the browser. Additionally, I will optimize cache usage and implement a method to avoid constant status synchronization, so we don't need to consume so many WhatsApp resources within the browser's DB store. Follow the process at:
https://github.com/wppconnect-team/wppconnect/issues/2302
