### ISSUE TITLE
folderNameToken not working when browser instance param is setted 

### ISSUE THREAD

**Issue by alexandre1921** [wppconnect-team/wppconnect#1881]
## Description

I'm running my code on WSL. Because of this, I need to use the Chrome instance installed on my Linux. So, I created a browser with Puppeteer and tried passing it as a parameter to the wppconnect create method. However, when I do that, the folderNameToken seems to be ignored. This issue appears to be related to the browser instance, because when I don't pass it, the correct folder path is used as expected.

## Environment

- **WPPConnect version(s):** 1.28.0
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome 117.0.5938.149
- **OS:** Windows 11 with WSL
- **Node version:** Node 18.17.1
- **WhatsApp version:** 2.2331.9
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Create an puppeteer instance
2. Create a client
3. Check if folder was created

## Your Code

```
async function start() {
      const browser = await puppeteer.launch({
	      executablePath: '/usr/bin/google-chrome',
      });
      
      return create({
	      session: '1',
	      browser,
	      folderNameToken: 'tokens/wppconnect',
      })
}

start();
```

**Comment by renat473** [comment]
I recommend not using wsl if necessary.

due to restrictions on browser and puppeteer execution
