### ISSUE TITLE
help in sendPttFromBase64 or is a really error? (InvalidMediaFileType)

### ISSUE THREAD

**Issue by Divino67** [wppconnect-team/wppconnect#1896]
## Description

When send a voice message on navigator chrome, or other, i use the navigator.mediaDevices.getUserMedia to record the audio, and then convert to base64 with mimetype audio/ogg. This is the code that does this:

```
startRecording() {
            if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
                console.error('getUserMedia não é suportado neste navegador.');
                return;
            }

            this.isRecording = true;
            let recordedChunks = [];

            navigator.mediaDevices.getUserMedia({audio: true})
                .then(stream => {
                    this.mediaRecorder = new MediaRecorder(stream);
                    this.mediaRecorder.addEventListener('dataavailable', event => {
                        if (event.data.size > 0) {
                            recordedChunks.push(event.data);
                        }
                    });
                    this.mediaRecorder.addEventListener('stop', () => {
                        const audioBlob = new Blob(recordedChunks, {type: 'audio/ogg'});

                        const fileReader = new FileReader();
                        fileReader.onloadend = () => {
                            this.audioRecord = fileReader.result
                        };
                        fileReader.readAsDataURL(audioBlob);
                    });
                    this.mediaRecorder.start();
                    this.isRecording = true;
                }).catch(error => {
                console.error('Erro ao acessar o dispositivo de áudio:', error);
                this.toast.error('É necessário ter algum microfone conectado!');
            });
        },
```
This code above assigns the fileReader.result to a property that is sent to the backend elsewhere, but its value is unchanged.

In the backend I have this method that tries to send the audio message in base64. However, every time it returns an error.

```
socket.on('send_voice_message', async datas => {
                if (this.client) {
                    await this.client.sendPttFromBase64(datas.chatId, datas.audio, 'audio').then(res => {
                        console.log(res);
                    }).catch(err => {
                        console.log(err);
                        socket.emit('error_msg', err.message)
                    })
                }
            });
```

This is the error:

InvalidMediaFileType: {"name":"InvalidMediaFileType","stack":"InvalidMediaFileType\n    at new i (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:40:637570)\n    at new u (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:51:463522)\n    at Object.<anonymous> (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:48:602093)\n    at Generator.next (<anonymous>)\n    at t (https://web.whatsapp.com/vendor1~app.be50aaad33253076fc3f.js:2:66483)\n    at s (https://web.whatsapp.com/vendor1~app.be50aaad33253076fc3f.js:2:66694)"}
                        at /home/r2-app/r2-whatsapp-api/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
                        at step (/home/r2-app/r2-whatsapp-api/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
                        at Object.next (/home/r2-app/r2-whatsapp-api/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
                        at fulfilled (/home/r2-app/r2-whatsapp-api/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
                        at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                        JS Stack: InvalidMediaFileType
                            at new i (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:40:637570)
                            at new u (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:51:463522)
                            at Object.<anonymous> (https://web.whatsapp.com/app.84e18bc8f4acb9a3ca56.js:48:602093)
                                at Generator.next (<anonymous>)
                                    at t (https://web.whatsapp.com/vendor1~app.be50aaad33253076fc3f.js:2:66483)
                                    at s (https://web.whatsapp.com/vendor1~app.be50aaad33253076fc3f.js:2:66694)
                                Function: function (_a) {
                                                                var to = _a.to, base64 = _a.base64, filename = _a.filename, caption = _a.caption, quotedMessageId = _a.quotedMessageId, messageId = _a.messageId;
                                                                return __awaiter(_this, void 0, void 0, function () {
                                                                    var result;
                                                                    var _b;
                                                                    return __generator(this, function (_c) {
                                                                        switch (_c.label) {
                                                                            case 0: return [4 /*yield*/, WPP.chat.sendFileMessage(to, base64, {
                                                                                    type: 'audio',
                                                                                    isPtt: true,
                                                                                    filename: filename,
                                                                                    caption: caption,
                                                                                    quotedMsg: quotedMessageId,
                                                                                    waitForAck: true,
                                                                                    messageId: messageId,
                                                                                })];
                                                                            case 1:
                                                                                result = _c.sent();
                                                                                _b = {
                                                                                    ack: result.ack,
                                                                                    id: result.id
                                                                                };
                                                                                return [4 /*yield*/, result.sendMsgResult];
                                                                            case 2: return [2 /*return*/, (_b.sendMsgResult = _c.sent(),
                                                                                    _b)];
                                                                        }
                                                                    });
                                                                });
                                                            }

## Environment

- **WPPConnect version(s):** 1.28.0
- **WA-JS version(s):** 2.26.1
- **Browser:** Chrome 115.0.5790.170
- **OS:** Linux Ubuntu 22.04
- **Node version:** Node 16.14.2
- **WhatsApp version:** 2.2331.9
- **MultiDevice (BETA):** yes

If anyone can help me fix it I would be very grateful.

**Comment by icleitoncosta** [comment]
Please, record your audio and convert to mp3, before send to wppconnect.

Example code:

audioRecorder.js
```
import moment from "moment/moment";

export class Recorder {
  constructor() {
    this.isRecording = false;
    this.recorder = "";
    this.getUserMediaStream = "";
    this.base64 = "";
    this.file;
    this.time_start = moment();
    this.time_end = moment();
  }
  //getters
  getData() {
    //var difference = moment(this.time_start).diff(this.time_end, 'seconds', true);
    const difference = moment(this.time_end).diff(this.time_start, "seconds");
    const data = { base64: this.base64, duration: difference, file: this.file };
    return data;
  }
  start() {
    this.time_start = moment();
    this.time_end = moment();
    const options = { audio: true, video: false };
    const that = this;
    navigator.mediaDevices.getUserMedia(options).then(function (stream) {
      that.getUserMediaStream = stream;
      that.recorder = new MediaRecorder(stream);
      that.recorder.blobs = [];
      that.recorder.ondataavailable = onRecordingReady;

      that.recorder.start();
      that.isRecording = true;
    });
    function onRecordingReady(e) {
      const chunks = [];
      chunks.push(e.data);
      const blob = new Blob(chunks, { type: "audio/mpeg-3" });
      that.file = new File([blob], "audio.mpeg", { type: "audio/mpeg" });

      const reader = new window.FileReader();
      reader.readAsDataURL(blob);
      reader.onloadend = function () {
        const base64 = reader.result;
        that.base64 = base64;
      };
    }
  }

  stop() {
    this.time_end = moment();
    this.isRecording = false;

    const audioTrack = this.getUserMediaStream.getAudioTracks()[0];
    audioTrack.stop();
    this.recorder.stop();
  }
}

```

On start record. call: this.Recorder().start();

On stop() 
```
this.recorder.stop();
        const obj = document.getElementById("buttomRecorderStartStop") as any;

        setTimeout(() => {
          const data_audio = this.recorder.getData();
        }, 500);
        return;
```

Please note that this code was created two years ago and is not done in the correct way, but it is functional and you can implement it in your solution.

I will keep this issue closed, feel free to reopen it if you have any further questions or concerns.
