### ISSUE TITLE
suporte ao @sparticuz/chromium

### ISSUE THREAD

**Issue by marcelocecin** [wppconnect-team/wppconnect#1922]
favor implementar a possibilidade de rodar em plataformas Serverless através do https://github.com/Sparticuz/chromium
exemplo de plataforma https://pipedream.com/blog/puppeteer-and-playwright/
https://github.com/PipedreamHQ/pipedream/blob/cbacd87f1ff3fbfac9b892bcabbbbb0aabaadb8d/packages/browsers/index.mjs

**Comment by RAKESHSUVIDYA** [comment]
debug: Emitting onInterfaceChange event (1 registered)
http:  Current state: SYNCING (CONNECTING)
debug: Emitting onInterfaceChange event (1 registered)
http:  Current state: SYNCING (CONNECTING)
info:  Auto close configured to 180s
http:  Checking phone is connected...
debug: Emitting onInterfaceChange event (1 registered)
http:  Current state: SYNCING (CONNECTING)
debug: Emitting onInterfaceChange event (1 registered)
http:  Current state: SYNCING (CONNECTING)
debug: Registering onStateChange event
debug: Emitting onInterfaceChange event (1 registered)
http:  Current state: SYNCING (SYNCING)

**Comment by icleitoncosta** [comment]
It is not possible to use serverless technologies, as some WhatsApp functions depend on continuous storage, this would crash WhatsApp itself.
