### ISSUE TITLE
QR Code Not Working

### ISSUE THREAD

**Issue by RAKESHSUVIDYA** [wppconnect-team/wppconnect#1926]
## Description

Device is not connecting. It shows failed after syncing status

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by RAKESHSUVIDYA** [comment]
Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

**Comment by RAKESHSUVIDYA** [comment]
error:    Unhandled Rejection: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
    at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
    at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:32:26)
    at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:91:26)
    at CdpCDPSession.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:78:33)
    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:211:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:128:16)
    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:370:20)

**Comment by icleitoncosta** [comment]
Hi, please past your complete code print in terminal.

**Comment by RAKESHSUVIDYA** [comment]
Unhandled Rejection: InvalidStateError: Failed to execute 'transaction' on
'IDBDatabase': The database connection is closing.
    at
***@***.***/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step
***@***.***/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next
***@***.***/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled
***@***.***/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
JS Stack: Error: Failed to execute 'transaction' on 'IDBDatabase': The
database connection is closing.
    at we.create (
https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:38839)
    at https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:30282
    at https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:15228
    at je (
https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:10440)
    at Ye (
https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:11197)
    at Be (
https://web.whatsapp.com/vendor1~app.4802d7adf05a55e9c1dc.js:7:11048)
Function: function (_a) {
                            var to = _a.to, content = _a.content, options =
_a.options;
                            return WPP.chat.sendTextMessage(to, content,
__assign(__assign({}, options), { waitForAck: true }));
                        }

**Comment by edgardmessias** [comment]
@RAKESHSUVIDYA , please, stop spamming all issues, I will block you if you continue

**Comment by RAKESHSUVIDYA** [comment]
I have no intation to do spamming here. I am facing this issues. 
**ERROR MSG:** Unhandled Rejection: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Please check

**Comment by icleitoncosta** [comment]
> I have no intation to do spamming here. I am facing this issues. **ERROR MSG:** Unhandled Rejection: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Please check

It is quite possible that this has to do with the processing capabilities of your machine. Try increasing the available resources (memory, processing power, etc.).
