### ISSUE TITLE
Adição do envio de mensagens em newsletter

### ISSUE THREAD

**Issue by Patrickph** [wppconnect-team/wppconnect#1984]
No Docs da Lib tem informações sobre a função newsletter porém em nenhuma parte é mencionado como fazer o envio de mensagens na newsletter ao tentar usar o sendText() simplesmente retorna um erro como se não existisse, caso já exista essa função por favor me informem como fazer pois na documentação não existe nada sobre e até meus do wapi.js não existem funções que mencionam a newsletter

**Comment by icleitoncosta** [comment]
Olá @Patrickph, para enviar mensagem para um canal é simples, é como enviar uma mensagem normal, apenas enviando para o chatId co canal. 

Ex:

`client.sendText('120363181195890069@newsletter', 'mensagem de teste');`

**Comment by Patrickph** [comment]
Já tentei enviar assim e não vai mas vou tentar novamente.

**Comment by icleitoncosta** [comment]
> Já tentei enviar assim e não vai mas vou tentar novamente.

Verifica se não está desatualizado seu projeto, testei literalmente agora para poder ver (se estiver usando o server, realmente não vai), mas apenas a LIb vai sim.

**Comment by Patrickph** [comment]
Provavelmente é isso, estou usando o WPPCONNECT-WA.JS no meu projeto, bom vou ver o que posso fazer, aliás feliz natal para você e toda equipe WPPCONNECT

**Comment by icleitoncosta** [comment]
> Provavelmente é isso, estou usando o WPPCONNECT-WA.JS no meu projeto, bom vou ver o que posso fazer, aliás feliz natal para você e toda equipe WPPCONNECT

Igualmente @Patrickph. Um ótimo natal e um feliz 2024!

Pode tentar colar o código que está usando lá no WAJS, que ai podemos auxiliar melhor.
Abraços!
