### ISSUE TITLE
Chats won't show. Blank page after connection

### ISSUE THREAD

**Issue by renandecarlo** [wppconnect-team/wppconnect#1987]
## Description

After successfully connecting, WhatsApp Web shows a blank page.
Tried with latest wppconnect@1.28.3, also tried with newest wa-js and wa-version. Same results.

## Environment

- **WPPConnect version(s):** 1.28.3
- **WA-JS version(s):** 2.28.0
- **Browser:** Chrome 120.0.6099.71
- **OS:** Windows 10
- **Node version:** v18.17.1
- **WhatsApp version:** 2.2347.x or 2.2353.56

## Your Code

```js
const wppconnect = require('@wppconnect-team/wppconnect');

(async () => {
	try {
		client = await wppconnect.create({ session: 'test', headless: false });
	} catch(e) {
		console.error(e);
	}
})()
```

## Additional context / Screenshot

![2023-12-11 18_28_17-Window](https://github.com/wppconnect-team/wppconnect/assets/6974980/be3b188e-0965-4c41-86e2-24ec97d3669c)

**Comment by linuxroy** [comment]
facing same issue..

**Comment by enjazadv** [comment]
facing same issue..

**Comment by renandecarlo** [comment]
It seems wppconnect **v1.28.3** and **v.1.28.4** use an incompatible WhatsApp version by default.
Setting `whatsappVersion: null` option to load latest WhatsApp version seems to fix it.

**Comment by renandecarlo** [comment]
The new release probably fixes this.
