### ISSUE TITLE
Uncaught Error: Could not load the "sharp" module using the darwin-arm64 runtime

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#2005]
## Description

When i upgrade to latest version in ubuntu / mac i get this error:

Uncaught Error: Could not load the "sharp" module using the darwin-arm64 runtime

**Comment by danielalves1** [comment]
- Check your node version
Now `sharp` needs node version >= 18.17.0

Ref.: https://github.com/lovell/sharp?tab=readme-ov-file#sharp

**Comment by roysG** [comment]
Thanks
