### ISSUE TITLE
Bug when run the app

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#2041]
## Environment

- **WPPConnect version(s):** Latest
- **WA-JS version(s):** Latest
- **Browser:** Chrome XX 
- **OS:** Linux / Mac
- **Node version:** Node 20.11.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Start the app with version 1.28.4 and you see errors

Error: Execution context was destroyed, most likely because of a navigation. at rewriteError (/Users/roysabah/www/msgto/server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:265:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext._evaluateInternal (/Users/roysabah/www/msgto/server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:219:60) at async DOMWorld.addScriptTag (/Users/roysabah/www/msgto/server/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:188:21) {stack: "Error: Execution context was destroyed, most likel…teer/lib/cjs/puppeteer/common/DOMWorld.js:188:21)", message: "Execution context was destroyed, most likely because of a navigation."

**Comment by roysG** [comment]
I disabled the headless modes and i see that it try many times to do an update but fail and stack

**Comment by dudanogueira** [comment]
Same here... this seems a wide error

**Comment by roysG** [comment]
In other library reversing is working

בתאריך יום ה׳, 25 בינו׳ 2024 ב-13:34 מאת Duda Nogueira <
***@***.***>:

**Comment by dudanogueira** [comment]
@roysG what do you mean? reversing to a lower version of wppconnect?

**Comment by Konomaster** [comment]
Run "npm update" on wppconnect's root folder. This will fix it, but im not sure for how much time.

**Comment by mendoncart** [comment]
I'm having the same problem.
Here are my [logs](https://pastebin.com/5AZJyqLD).

**Comment by pablogtab** [comment]
i downgraded to version @wppconnect-team/wppconnect@1.28.3
and it seems to work

**Comment by iampedrosilva** [comment]
> Run "npm update" on wppconnect's root folder. This will fix it, but im not sure for how much time.

Problem was resolved, but as said, we don't know for how long, all my back-end services that use the library suffered the same error.
What should we expect and a new update to fix this!

**Comment by altamirosantos** [comment]
Update version zap on init.
Ex.:

...  
headless: true,
      useChrome: true,
      whatsappVersion: "2.2404.2",
...

**Comment by Konomaster** [comment]
> Update version zap on init. Ex.:
> 
> ... headless: true, useChrome: true, whatsappVersion: "2.2404.2", ...

Which init? What file are you talking about?

**Comment by renat473** [comment]
FIX

Update version whatsapp versions https://wppconnect.io/whatsapp-versions/

Se você esta com problemas com WppConnect.

O problema que esta ocorrendo e devido a versão do WhatsApp Web que foi descontinuado e para resolver este problema basta trocar a versão do WhatsApp Web, você pode encontrar todas as versões disponível no seguinte endereço.

https://wppconnect.io/whatsapp-versions

OBS  1 : caso você esteja utilizando o server e não queria aguardar a atualização de troca de versão basta alterar o seguinte a arquivo.

node_modules/@wppconnect-team/wppconnect/dist/config/create-config.js

OBS 2 : Outros problemas que vem ocorrendo com erro de Sharp podem ser resolvidos com a atualização do Nodejs para versão 18.17.0 e após a atualização executar os comandos abaixo.

OBS 3 : Boa parte dos problemas que esta ocorrendo e devido estarem utilizando versões sem a atualização a meses.

OBS 4 : EM CASO DE DUVIDAS MANDE SUA DUVIDA NA CATEGORIA DO PROJETO QUE ESTA UTILIZANDO A CATEGORIA GERAL NÃO FOI FEITA PARA DÚVIDAS.

yarn add sharp
yarn add sharp --ignore-engines

**Comment by altamirosantos** [comment]
On your create session...

config = {
      session: <your sessionID>,
      headless: true,
      useChrome: true,
      whatsappVersion: "2.2404.1",
      puppeteerOptions: {
        userDataDir: `<your path sessionID>`,
      },
      browserArgs: [
        '--no-sandbox'
      ]
    };
  }

  wppconnect
    .create(config)
    .then((client: any) => start(client))
    .catch((erro: any) => {
      console.log(erro);
    });

**Comment by renat473** [comment]
@dudanogueira fiz a troca de versão do whatsapp web na lib e para o próximo build da imagem já ter a versão atualizada web atualizada.

**Comment by dudanogueira** [comment]
@renat473 tem algo que possamos fazer pra forçar esse build? 😬

**Comment by andredallacosta** [comment]
> On your create session...
> 
> config = { session: , headless: true, useChrome: true, whatsappVersion: "2.2404.1", puppeteerOptions: { userDataDir: `<your path sessionID>`, }, browserArgs: [ '--no-sandbox' ] }; }
> 
> wppconnect .create(config) .then((client: any) => start(client)) .catch((erro: any) => { console.log(erro); });

It worked for me, tnx!
