### ISSUE TITLE
Sending messages while the phone is disconnected

### ISSUE THREAD

**Issue by francisbreit** [wppconnect-team/wppconnect#205]
I am trying to create a way to send messages when the cell phone has been paired but has been temporarily disconnected. I tried it with guzzlehttp, but was unsuccessful. It would be a kind of queue to send messages when the cell phone reconnects again.

**Comment by gs-nasc** [comment]
Hello, you can also activate the offline option inside your whatsapp, with this option activated you can't more need of internet or phone to send and receive messages.

In your whatsapp: Setting->Connected Devices (or Whatsapp Web in Android Devices) -> Multiple Devices (activate this option)
