### ISSUE TITLE
Messages sometimes not send to contacts numbers

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#2066]
## Description

1. Try send msg to someone in the contact, the message will not get on the reciever.
2. Just in case he will send message to you then suddenly it will start sending him message
3. But after you restart the session again, same problem

Latest version

## Steps to Reproduce

1. Try send msg to someone in the contact, the message will not get on the reciever.
2. Just in case he will send message to you then suddenly it will start sending him message
3. But after you restart the session again, same problem

Tested on Node version: 20 and 21.6.1

**Comment by gekkedev** [comment]
To rule out a usage error, have you got any code for reproduction?
