### ISSUE TITLE
onMessage not getting the message of the user in macbook M1

### ISSUE THREAD

**Issue by roysG** [wppconnect-team/wppconnect#2072]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** 1.29.0
- **WA-JS version(s):**   2.28.1
- **Browser:** Chrome
- **OS:** Mac
- **Node version:**: 20.11.0
- **WhatsApp version:**  2.2404.5

## Steps to Reproduce

1. Send  mes from other device
2. The message got but the text in not found in any field

**Comment by roysG** [comment]
* For external number/ other country than the logged phone.

**Comment by icleitoncosta** [comment]
try: onAnyMessage, please.
