### ISSUE TITLE
WPPCOnnect fails without setting headless either true or new

### ISSUE THREAD

**Issue by ejike-nnodi** [wppconnect-team/wppconnect#2079]
**Is your feature request related to a problem? Please describe.**
While i was testing today i noticed that puppeteer-core wasn't starting, so i played a little bit with the headless parameter, i noticed that false doesnt work anymore. I think its related to the warning:
```

    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

```
and the article
https://developer.chrome.com/docs/chromium/new-headless

**Describe the solution you'd like**
I think we should set the parameter as new as default, or let users know in the documentation
I am not familiar with NodeJs, im not sure where that can be added.

Food for Thought

**Comment by icleitoncosta** [comment]
Hello, thank you for letting me know, I will run some tests later. I was waiting for new Chrome updates; unfortunately, in the new headless mode, Debian versions were failing to work, so I preferred to postpone this change for now.

**Comment by icleitoncosta** [comment]
> and the article https://developer.chrome.com/docs/chromium/new-headless
> 
> **Describe the solution you'd like** I think we should set the parameter as new as default, or let users know in the documentation I am not familiar with NodeJs, im not sure where that can be added.
> 
> Food for Thought

Please, could you put here the log that is occurring for you? The headless true is supposed to work regardless because when Puppeteer defaults to the new mode, true will automatically become 'new'.

I ran some tests, and it still works. I would like to understand more about the scenario that caused it to fail for you.
