### ISSUE TITLE
Mensagem não é exibida em novas versões do WhatsApp quando a mensagem possui botões 

### ISSUE THREAD

**Issue by mhanelia** [wppconnect-team/wppconnect#2080]
## Description

Ao enviar mensagem com botão, não exibe mensagem com os botões nas novas versões do WhatsApp

## Environment

- **WPPConnect version(s):** 1.29.0
- **WA-JS version(s):** 2.28.1
- **WhatsApp version:** 2.2409.2 e 2.2407.10
- **Plataforma:** Web, mobile e aplicativo PC

## Steps to Reproduce

1. Enviar mensagem com botões
2. Verificar em uma versão anterior do WhatsApp
3. Verificar em uma versão nova do WhatsApp

## Your Code

```
 await session.sendText(isValidNumber.id._serialized, content,  {
        useTemplateButtons: true, // False for legacy
        buttons: [
          {
            url: 'https://wppconnect.io/',
            text: 'WPPConnect Site'
          },
          {
            phoneNumber: '+55 11 22334455',
            text: 'Call me'
          },
          {
            id: 'your custom id 1',
            text: 'Some text'
          },
          {
            id: 'another id 2',
            text: 'Another text'
          }
        ],
        title: 'Title text', // Optional
        footer: 'Footer text' // Optional
      }); 
      return response.status(200).json({
        status: true,
        message: 'Sua mensagem foi enviada com sucesso.',
        status_code: 200
      });
```

## Additional context / Screenshot

Versão 2.2409.2
![image](https://github.com/wppconnect-team/wppconnect/assets/8427316/db9cbf2f-67ba-4eab-b4a6-2e73cdc22c1f)

Versão 2.2407.10
![image](https://github.com/wppconnect-team/wppconnect/assets/8427316/56793a1d-8b37-4b63-bd03-c71fc5490d0e)

**Comment by icleitoncosta** [comment]
Olá @mhanelia , os botões foram descontinuados, não tem como envia-los mais.
