### ISSUE TITLE
Working on local but not working on live host like replit or render

### ISSUE THREAD

**Issue by spysinc** [wppconnect-team/wppconnect#2129]
## Description
I just installed this code and it is working fine on localhost but when I tried to run on replit or render then it gave me errors.

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
4. [and so on...]

## Log Output

```
[32minfo[39m:     [sessionName:browser] Using browser folder '/var/task/tokens/sessionName'
[32minfo[39m:     [sessionName:browser] Initializing browser...
[33mwarn[39m:     [sessionName:browser] Chrome not found, using chromium
[31merror[39m:    [sessionName:browser] Error no open browser
[31merror[39m:    [sessionName:browser] Could not find Chrome (ver. 123.0.6312.86). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Error: Could not find Chrome (ver. 123.0.6312.86). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).  
```

## Your Code

```
const wppconnect = require('@wppconnect-team/wppconnect');

wppconnect.create({
    session: 'sessionName', //Pass the name of the client you want to start the bot
    catchQR: (base64Qrimg, asciiQR, attempts, urlCode) => {
        console.log('Number of attempts to read the qrcode: ', attempts);
        console.log('Terminal qrcode: ', asciiQR);
        console.log('base64 image string qrcode: ', base64Qrimg);
        console.log('urlCode (data-ref): ', urlCode);
    },
    statusFind: (statusSession, session) => {
        console.log('Status Session: ', statusSession);
        console.log('Session name: ', session);
    },
    headless: true, // Headless chrome
    devtools: false, // Open devtools by default
    useChrome: true, // If false will use Chromium instance
    debug: false, // Opens a debug session
    logQR: true, // Logs QR automatically in terminal
    browserWS: '', // If u want to use browserWSEndpoint
    browserArgs: [''], // Parameters to be added into the chrome browser instance
    puppeteerOptions: {}, // Will be passed to puppeteer.launch
    disableWelcome: false, // Option to disable the welcoming message which appears in the beginning
    updatesLog: true, // Logs info updates automatically in terminal
    autoClose: 60000, // Automatically closes the wppconnect only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
    tokenStore: 'file', // Define how work with tokens, that can be a custom interface
    folderNameToken: './tokens', //folder name when saving tokens
    sessionToken: {
        WABrowserId: '"UnXjH....."',
        WASecretBundle: '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
        WAToken1: '"0i8...."',
        WAToken2: '"1@lPpzwC...."',
    }
})
    .then((client) => start(client))
    .catch((error) => console.log(error));


function start(client) {
    client.onMessage((message) => {
        if (message.body === 'Hello') {
            client
                .sendText(message.from, 'Hello, how I may help you?')
                .then((result) => {
                    console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });
        }
    });
}
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Divino67** [comment]
You need to have Google Chrome installed on the server, you probably already have it on your local machine. Run the command:

google-chrome --version

to see if it is installed on the server.

**Comment by datafinderservice** [comment]
> You need to have Google Chrome installed on the server, you probably already have it on your local machine. Run the command:
> 
> google-chrome --version
> 
> to see if it is installed on the server.

On render or vercel, how to install Google Chrome if not installed. can you guide me regarding this?

**Comment by Haliq0841** [comment]
> ## Description
> I just installed this code and it is working fine on localhost but when I tried to run on replit or render then it gave me errors.
> 
> [Description of the bug, When Issue Happens]
> 
> ## Environment
> * **WPPConnect version(s):** X.Y.Z
> * **WA-JS version(s):** X.Y.Z
> * **Browser:** Chrome XX / Chromium XX
> * **OS:** Windows X / OSX X.Y.Z
> * **Node version:** Node XY
> * **WhatsApp version:** X.YYYY.ZZ
> * **MultiDevice (BETA):** yes/no
> 
> ## Steps to Reproduce
> 1. [First Step]
> 2. [Second Step]
> 3. [and so on...]
> 
> ## Log Output
> ```
> �[32minfo�[39m:     [sessionName:browser] Using browser folder '/var/task/tokens/sessionName'
> �[32minfo�[39m:     [sessionName:browser] Initializing browser...
> �[33mwarn�[39m:     [sessionName:browser] Chrome not found, using chromium
> �[31merror�[39m:    [sessionName:browser] Error no open browser
> �[31merror�[39m:    [sessionName:browser] Could not find Chrome (ver. 123.0.6312.86). This can occur if either
>  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
>  2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
> For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
> Error: Could not find Chrome (ver. 123.0.6312.86). This can occur if either
>  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
>  2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).  
> ```
> 
> ## Your Code
> ```
> const wppconnect = require('@wppconnect-team/wppconnect');
> 
> wppconnect.create({
>     session: 'sessionName', //Pass the name of the client you want to start the bot
>     catchQR: (base64Qrimg, asciiQR, attempts, urlCode) => {
>         console.log('Number of attempts to read the qrcode: ', attempts);
>         console.log('Terminal qrcode: ', asciiQR);
>         console.log('base64 image string qrcode: ', base64Qrimg);
>         console.log('urlCode (data-ref): ', urlCode);
>     },
>     statusFind: (statusSession, session) => {
>         console.log('Status Session: ', statusSession);
>         console.log('Session name: ', session);
>     },
>     headless: true, // Headless chrome
>     devtools: false, // Open devtools by default
>     useChrome: true, // If false will use Chromium instance
>     debug: false, // Opens a debug session
>     logQR: true, // Logs QR automatically in terminal
>     browserWS: '', // If u want to use browserWSEndpoint
>     browserArgs: [''], // Parameters to be added into the chrome browser instance
>     puppeteerOptions: {}, // Will be passed to puppeteer.launch
>     disableWelcome: false, // Option to disable the welcoming message which appears in the beginning
>     updatesLog: true, // Logs info updates automatically in terminal
>     autoClose: 60000, // Automatically closes the wppconnect only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
>     tokenStore: 'file', // Define how work with tokens, that can be a custom interface
>     folderNameToken: './tokens', //folder name when saving tokens
>     sessionToken: {
>         WABrowserId: '"UnXjH....."',
>         WASecretBundle: '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
>         WAToken1: '"0i8...."',
>         WAToken2: '"1@lPpzwC...."',
>     }
> })
>     .then((client) => start(client))
>     .catch((error) => console.log(error));
> 
> 
> function start(client) {
>     client.onMessage((message) => {
>         if (message.body === 'Hello') {
>             client
>                 .sendText(message.from, 'Hello, how I may help you?')
>                 .then((result) => {
>                     console.log('Result: ', result); //return object success
>                 })
>                 .catch((erro) => {
>                     console.error('Error when sending: ', erro); //return object error
>                 });
>         }
>     });
> }
> ```
> 
> ## Additional context / Screenshot
> Add any other context about the problem here. If applicable, add screenshots to help explain.

I am also experiencing the same problem, can anyone provide an example of using WPPconnect repositories in replit?

**Comment by icleitoncosta** [comment]
Vercel is a frontend product; there are several issues with using Puppeteer on it. You can manage to use it, but it's quite complex. Consider using a better platform like Railways, DigitalOcean, Contabo, etc.
