### ISSUE TITLE
Evento onAck não está sendo disparado ao realizar envios pela função sendPtt

### ISSUE THREAD

**Issue by igorgazoni** [wppconnect-team/wppconnect#213]
## Description

Evento onAck não está sendo disparado ao realizar envios pela função sendPtt

## Environment

Wppconnect version 1.5.0

## Steps to Reproduce

1. Colocar um break point (debug) no evento onAck
2. Realizar um envio de audio pelo sendPtt
3. Observar que após o envio pelo sendPtt não será chamado onAck (não irá entrar no break point)

## Additional context / Screenshot

Problema começou a ocorrer após a atualização para release 1.5.0.

**Comment by edgardmessias** [comment]
Eu realizei uns testes e está tudo normal, código que usei:

```ts
  client.onAck((ack) => console.log('ACK:', ack));
  await client.sendPtt('<number>@c.us', 'test.mp3');
```

**Comment by igorgazoni** [comment]
realmente. refiz meu código utilizando seu exemplo e funcionou. Obrigado.
Chamado Finalizado! OK
