### ISSUE TITLE
Enviar um sticker mencionando uma mensagem

### ISSUE THREAD

**Issue by deivinni** [wppconnect-team/wppconnect#2150]
Recentemente estive procurando em toda a documentação, por maneiras para realizar está ação, mas não consegui encontrar nada sobre.

Penso que seria interessante adicionarem essa opção para aumentar ainda mais a usabilidade da biblioteca.

Um exemplo de como seria o seu uso (utilizando como base a função `reply`):
```js
await client.sendImageAsSticker(
    '000000000000@c.us',
    './image.jpg',
    message.id.toString()
);
```
O mesmo seria para os stickers em Gif (`sendImageAsStickerGif`).

**Comment by icleitoncosta** [comment]
Implemented: 
```
 client.sendImageAsSticker('000000000000@c.us', 'base64....', {
     quotedMsg: 'msgId',
 });
```
