### ISSUE TITLE
Whatsapp Channel Feature

### ISSUE THREAD

**Issue by SajjadAhmad904** [wppconnect-team/wppconnect#2151]
Hi ,

Is there any update or information about the WhatsApp channel feature? I'm looking forward to your response.

Thanks,
Sajjad

**Comment by icleitoncosta** [comment]
> Hi ,
> 
> Is there any update or information about the WhatsApp channel feature? I'm looking forward to your response.
> 
> Thanks, Sajjad

The channels is the newsletter, can you manage by https://wppconnect.io/wppconnect/classes/Whatsapp.html#createNewsletter
