### ISSUE TITLE
Erro ao adicionar participantes

### ISSUE THREAD

**Issue by ch4rliedev** [wppconnect-team/wppconnect#2152]
## Description

Ao adicionar um participante em um grupo que ele saiu recentemente, o wppconnect retorna o código 408, mas a mensagem dele é "erro desconhecido", impossibilitando que os desenvolvedores saibam qual especificamente é o erro.

## Environment

- **WPPConnect version(s):** 1.30.1
- **WA-JS version(s):** 3.1.1
- **Browser:** Chrome 123.0.6312.122
- **OS:** Windows 10 e Linux
- **Node version:** 20.12.0
- **WhatsApp version:** 2.3000.1012840629-alpha e 2.2412.50
- **MultiDevice (BETA):** Sim

## Steps to Reproduce

1º - Use o `client.addParticipant()` com qualquer grupo e número que tenha saído recentemente.

## Log Output

![a](https://github.com/wppconnect-team/wppconnect/assets/88893508/1a9ecb84-b57e-4a65-b5e4-1acd2dce7d66)

## Your Code

`await client.addParticipant(groupId, mentionedUser);`

**Comment by icleitoncosta** [comment]
Corrigido
