### ISSUE TITLE
WAPI.isLoggedIn return false

### ISSUE THREAD

**Issue by ono77** [wppconnect-team/wppconnect#2155]
In last WAweb version the function "WAPI.isLoggedIn()" always return False

The cause seems that "WPP.whatsapp.ContactStore.checksum" is undefined 

WhatsappWeb version: 2.3000.1013005935
WPP.version: 3.1.1

**Comment by postguruji** [comment]
Error checking number status: Error: WAPI is not defined
0|index  |     at /home/xxxx-zone-a/htdocs/xxxx.in/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
0|index  |     at step (/home/xxxx-zone-a/htdocs/xxxx.in/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
0|index  |     at Object.next (/home/xxxxx-zone-a/htdocs/xxxxx.in/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
0|index  |     at fulfilled (/home/xxxxx/htdocs/zone-a.xxxxx.in/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
0|index  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by icleitoncosta** [comment]
Please, use `client.isAuthenticated()`
