### ISSUE TITLE
Request for adding new Feature :: link with mobile number so don't want to connect with Qr Code 

### ISSUE THREAD

**Issue by tls-jil** [wppconnect-team/wppconnect#2166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by icleitoncosta** [comment]
Use:
```
create({
    session: 'sessionName',
    phoneNumber: '5521999999999',
    catchLinkCode((code) => console.log(code));
})
```

**Comment by jaygent** [comment]
> Use:
> 
> ```
> create({
>     session: 'sessionName',
>     phoneNumber: '5521999999999',
>     catchLinkCode((code) => console.log(code));
> })
> ```

not work 
catchLinkCode((code) => console.log(code));
