### ISSUE TITLE
Error open browser

### ISSUE THREAD

**Issue by megustalol** [wppconnect-team/wppconnect#2167]
## Description
Esse erro acontece algumas vezes durante o dia aqui, apago a pasta tokens e leio qr de novo resolve temporariamente

1|bot  | error:    [bot:browser] Failed to launch the browser process! undefined

## Environment

- **WPPConnect version(s):** 1.30.2
- **WA-JS version(s):** 3.2.3
- **Browser:** Chrome XX / Chromium XX
- **Node version:** 18.17.0
- **WhatsApp version:** 2.2412.50

## Log Output

error:    [bot:browser] Error no open browser
1|bot  | error:    [bot:browser] Failed to launch the browser process! undefined
1|bot  | [2212843:2212843:0502/185348.353180:ERROR:process_singleton_posix.cc(335)] Failed to create /root/bot/tokensm/bot/SingletonLock: File exists (17)
1|bot  | [2212843:2212843:0502/185348.353846:ERROR:chrome_main_delegate.cc(597)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
1|bot  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
1|bot  | Error: Failed to launch the browser process! undefined
1|bot  | [2212843:2212843:0502/185348.353180:ERROR:process_singleton_posix.cc(335)] Failed to create /root/bot/tokensm/bot/SingletonLock: File exists (17)
1|bot  | [2212843:2212843:0502/185348.353846:ERROR:chrome_main_delegate.cc(597)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
1|bot  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
1|bot  |     at ChildProcess.onClose (/root/bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
1|bot  |     at ChildProcess.emit (node:events:526:35)
1|bot  |     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
If relevant, paste all of your Log Output
```

**Comment by icleitoncosta** [comment]
Qual o sistema operacional que está utilizando?

**Comment by megustalol** [comment]
ubuntu 24.04

**Comment by icleitoncosta** [comment]
Olá, atualiza o projeto, e testa por favor. Fiz uma mudança e melhorei o tempo de start inicial.

**Comment by fernandoantoniodantas** [comment]
Não está funcionando no windows.

**Comment by fernandoantoniodantas** [comment]
Removi e reinstalei. Agora está ok.  Windows é tenso. Obrigado.
