### ISSUE TITLE
listChats Return Empty Array

### ISSUE THREAD

**Issue by jaisanas** [wppconnect-team/wppconnect#2175]
## Description

invoke function `const chats = await client.listChats();` return empty array

## Environment

- **WPPConnect version(s):** 1.30.3
- **Node version:** Node 0.13.1
- **MultiDevice (BETA):**no

## Steps to Reproduce

1. scan qr code
2. catch created client 
3.  log the result

## Log Output

```
[]
```

## Your Code

```
const wppconnect = require("@wppconnect-team/wppconnect");
wppconnect
  .create()
  .then(async (client) => {
    console.log(client);
    console.log("****************************");
    const chats = await client.listChats();
    console.log(chats);
    console.log("****************************");
  })
  .catch((error) => console.log(error));
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by icleitoncosta** [comment]
Please update the entire project, wppconnect, wa-js, and wa-version.

We made some changes. Previously, the listChats function did not return anything because, during synchronization, WhatsApp paused the return of chats through this function. Now it returns normally.
