### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by manish-snappe** [wppconnect-team/wppconnect#2178]
## Description

Getting "Failed to authenticate" error while scanning QR Code

## Environment

Windows

- **WPPConnect version(s):** 1.30.3
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome Version 124.0.6367.201 (Official Build) (64-bit)
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Start A New Scan
2. Scan the QR code generated
3. The WhatsApp login starts and gets stuck
4. On server side the browser closes with the Failed to Authenticate error. 

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by manish-snappe** [comment]
This is specifically happening when the browser is on a Virtual machine. In fact, with the wppconnect also, if I open the browser and scan directly, authentication failed is coming. Are we aware of this change done by WhatsApp where login on Virtual Machines (under VPN) are failing?

**Comment by icleitoncosta** [comment]
Aware of the login issue? In this case, is this virtual machine in a different location from your native IP? This has been happening a lot in India, and it is spreading to Central and South American countries. You need to use a local IP, even if you use a VPN on your machine.

> This is specifically happening when the browser is on a Virtual machine. In fact, with the wppconnect also, if I open the browser and scan directly, authentication failed is coming. Are we aware of this change done by WhatsApp where login on Virtual Machines (under VPN) are failing?
