### ISSUE TITLE
The function addOrRemoveLabels of Whatsapp is no working

### ISSUE THREAD

**Issue by kevin-guerrero808** [wppconnect-team/wppconnect#2185]
## Description

The function addOrRemoveLabels of Whatsapp is no working that is to say it don't add labels to chats in whatsapp and don't say anything in the response.

Other important thing is that the documentation say it receives two params chatIds and options as strings but the example display that it need to arrays

#### addOrRemoveLabels
`addOrRemoveLabels(chatIds, options): Promise<void>`

Add or delete label of chatId

##### Parameters

- **chatIds**: string
ChatIds

- **options:** string
options to remove or add

##### Returns Promise<void>

**Example**
```
client.addOrRemoveLabels(['[number]@c.us','[number]@c.us'],
[{labelId:'76', type:'add'},{labelId:'75', type:'remove'}]);
//or
```

## Environment

- **WPPConnect version(s):** ^1.30.3
- **Browser:** Chrome 125.0.6422.77
- **OS:** Windows 11
- **Node version:** Node 20.13.0
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** no

## My code example

```
client.addOrRemoveLabels([message.from], [{labelId:"Pendiente", type:'add'}]).then(response => {
  console.log('Labels added successfully:', response);
}).catch(error => {
  console.error('Error adding labels:', error);
});
```

The response generated is empty

## Expected result

The function must say the correct params and types and the result is to see the labels applied to the chats

**Comment by icleitoncosta** [comment]
Hi @kevin-guerrero808 you can get the labels id with `client.getAllLabels()`
And pass the id for function that way:

I will fix the docs

```
{
  "chatIds": [
    "5521[number_replace]@c.us"
  ],
  "options": [
    {
      "labelId": "20",
      "type": "add"
    },
    {
      "labelId": "17",
      "type": "remove"
    }
  ]
}
```

**Comment by kevin-guerrero808** [comment]
Hello @icleitoncosta! I found that I can use client.addOrRemoveLabels with two array arguments, `[<chatNumber>]` and `[{labelId: <id>, type: <add|remove>]` and it works, althouth I set ts-ignore becuase the typescript definition expect two strings as arguments.

### Code example
```
// @ts-ignore
client.addOrRemoveLabels([`${message.from}`],[{labelId:'12', type:'add'}]);
```

I hope that you update the typescript definition and documentation parameters

Thanks!
