### ISSUE TITLE
Preciso da ajuda para publicar o meu projeto.

### ISSUE THREAD

**Issue by Mafealno** [wppconnect-team/wppconnect#2186]
Olá, 

Eu construí uma aplicação baseada no wppconnect LIB e estou com dificuldade para publicar ela em algum servidor.

Eu inicialmente tentei no Heroku e Netlify porém ambos acusam a falta do Chrome no serviço e mesmo eu ativando plugins que instalariam o Chrome no build da aplicação o erro permanece. Depois tentei pelo AWS. Nele criei uma maquina baseada em Ubuntu, instalei o node, clonei o projeto e instalei a dependências e dei `npm start`. O projeto muito tempo subindo e não chega nem a gerar o QR code pois a conexão via SSH na maquina cai antes. Após pesquisar e navegar bastante aqui nas issues eu vi um sugestão de usar serviços de API como Railway. Assim fiz, configurei o projeto na ferramenta e mandei dar build. O projeto subiu, consegui gerar o QR code, conectei e sucesso. Porém alguns minutos depois de conectado, o build no Railway da erro de `Build timed out` pois, acredito eu, que o Railway ache que a aplicação estando de pé e funcionando, está ainda buildando e da erro de timeout.

Gostaria de uma ajuda, sugestão, encaminhamento de onde e como posso publicar a aplicação.

Atualmente quero apenas publicar em algum lugar para ter ideia de como ela ficará online, disponível por alguns poucos dias.

Desde já agradeço e vou seguir tentando.

**Comment by renat473** [comment]
Olá,

Os serviços como Heroku e Netlify , a aplicação somente fica disponível sobre demanda e assim impossibiltando a utilização de serviço que sempre precisa esta ativa. Para instâncias AWS EC2 se faz necessário que a instância tenha no mínimo 6GB de RAM com 4VCPU e assim você não vai ter problemas em gerar QRCODE, sobre o Railway ele não permite que tenha serviços de whatsapp pois não autorizado por eles.

**Comment by Mafealno** [comment]
Voce teria alguma outra solução de publicação que não seja fosse o AWS pois lá, uma máquina nos moldes que você descreveu, está ficando cerca de 0,39 USD por hora.

Desde já eu agradeço
