### ISSUE TITLE
Getting error After install wppconnect in window System

### ISSUE THREAD

**Issue by tls-jil** [wppconnect-team/wppconnect#2192]
## Description

Hello,

i have already use that package in my ubuntu system 

for now I install that package on my window system after that while create the client I get an following error

![image](https://github.com/wppconnect-team/wppconnect/assets/119101682/153720ba-35ba-49db-b475-5319593e4f74)
 
 
 Please Guide me

## Environment

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by tls-jil** [comment]
the same code on my ubuntu system is worked

**Comment by gekkedev** [comment]
I admit it's not smooth, I ran into this issue as well, but right below the lines in your screenshot are copy&paste-ready instructions on how to install sharp: `yarn add sharp --ignore-engines`

**Comment by icleitoncosta** [comment]
Hi, you can ugrade your npm version or upgrade yarn version.

Ex: 
`npm install -g npm@latest`
`npm cache clean -f`
