### ISSUE TITLE
WPP.chat.getMessages Issue 

### ISSUE THREAD

**Issue by Souhaibahar** [wppconnect-team/wppconnect#2193]
## Description

When i try to get chat messages , it throws an error PuppeteerSharp.EvaluationFailedException
and only solved if i opened new browser . 
This dosen't happen all the times
## Environment

- **WPPConnect version(s):** 3.2.4
- **Browser:** Chrome/120.0.0.0
- **OS:** Windows 10

## Steps to Reproduce

1. I request WPP.chat.getMessages for a contact in whatsapp web
2. It shows me an error 
3. When i refresh the browser, whatsapp ask to scan QR, i scan qr , i get chats , but again  WPP.chat.getMessages  returns error
4. And this stays forever , except if closed that browser and open new one , and scan qr again and all works fine then

## Log Output

PuppeteerSharp.EvaluationFailedException: Evaluation failed: TypeError: (0 , s.msgFindQuery) is not a function     at t.getMessages (__puppeteer_evaluation_script__:2:145326)     at __puppeteer_evaluation_script__:2:51    at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ExecutionContext.cs:line 223    at PuppeteerSharp.ExecutionContext.EvaluateFunctionInternalAsync(Boolean returnByValue, String script, Object[] args) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ExecutionContext.cs:line 189    at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ExecutionContext.cs:line 176    at PuppeteerSharp.IsolatedWorld.EvaluateFunctionAsync[T](String script, Object[] args) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/IsolatedWorld.cs:line 214    at WhatsappServer.WhatsappInstance.GetChatMessages(String contactId, Int32 count) in /src/WhatsappServer/WhatsappInstance.cs:line 354    at WhatsappServer.Controllers.ApiController.GetConversationMessages(String user, String contactId, Int32 count) in /src/WhatsappServer/Controllers/ApiController.cs:line 158

 public async Task<List<WhatsappMessage>> GetChatMessages(string contactId, int count) {
            var messages = await Page.EvaluateFunctionAsync<List<WhatsappMessage>>(@"async () => {                    
                      let result = await WPP.chat.getMessages('CONTACT_ID@c.us', { count: _COUNT_ });

                      const finalResult = result.map((item) => {                       
                        let newItem = {};
                        newItem = item.attributes;
                        
                        let lastMessageId = item.id._serialized;
                        newItem.id = lastMessageId;
                        newItem.fromMe = item.id.fromMe;
                        
                        if (item.quotedStanzaID){
                            let quotedMessageId = item.quotedMsgId._serialized;
                            newItem.quotedMessageId = quotedMessageId;
                        }
                        
                        return newItem;
                      });

                      return JSON.parse(JSON.stringify(finalResult));
                    }
}

**Comment by icleitoncosta** [comment]
Hello, how many messages have you tried to return when this error occurs?

**Comment by Souhaibahar** [comment]
200 message from each chat

**Comment by ethan2cl** [comment]
I encountered the same problem, using version 2.3000.1014014368-alpha，May I ask if you have resolved it
