### ISSUE TITLE
message reply method not working as expected

### ISSUE THREAD

**Issue by gekkedev** [wppconnect-team/wppconnect#2198]
## Description

Replying to a message only works in one way for me, using the deprecated `client.reply()` API. The messages appear as regular messages but are not flagged as replies.
For the new way to reply, the API docs say I should use the ID parameter, but there is also `t` and both seem to work. What is the difference between them?

There is a possibility that I just do not understand how I'm supposed to implement it without using the deprecated method.

## Environment

- **WPPConnect version(s):** 1.30.3
- **WA-JS version(s):** 3.3.0
- **Browser:** chrome-launcher@^0.15.2 / chromium-bidi@0.5.19
- **OS:** Windows 11
- **Node version:** Node v18.17.1
- **WhatsApp version:** 2.2411.x
- **MultiDevice (BETA):** no?

## Steps to Reproduce

1. Receive a simple text
2. Send a text reply to it

## Log Output
None, it does not throw an error, just does not work as expected. The messages are just sent as regular messages.

## Your Code
```
    client.reply(message.chatId, "my reply", message.id) // works
    client.reply(message.chatId, "my reply", message.t) // works

    //does not work
    return client.sendText(message.from, "my reply", {
      quotedMsgObj: message,
    });
    //does not work
    return client.sendText(message.from, "my reply", {
      quotedMsgId: message.t
    });
    //does not work
    return client.sendText(message.from, "my reply", {
      quotedMsgId: message.id
    });
```

**Comment by icleitoncosta** [comment]
> ## Description
> Replying to a message only works in one way for me, using the deprecated `client.reply()` API. The messages appear as regular messages but are not flagged as replies. For the new way to reply, the API docs say I should use the ID parameter, but there is also `t` and both seem to work. What is the difference between them?
> 
> There is a possibility that I just do not understand how I'm supposed to implement it without using the deprecated method.
> 
> ## Environment
> * **WPPConnect version(s):** 1.30.3
> * **WA-JS version(s):** 3.3.0
> * **Browser:** chrome-launcher@^0.15.2 / chromium-bidi@0.5.19
> * **OS:** Windows 11
> * **Node version:** Node v18.17.1
> * **WhatsApp version:** 2.2411.x
> * **MultiDevice (BETA):** no?
> 
> ## Steps to Reproduce
> 1. Receive a simple text
> 2. Send a text reply to it
> 
> ## Log Output
> None, it does not throw an error, just does not work as expected. The messages are just sent as regular messages.
> 
> ## Your Code
> ```
>     client.reply(message.chatId, "my reply", message.id) // works
>     client.reply(message.chatId, "my reply", message.t) // works
> 
>     //does not work
>     return client.sendText(message.from, "my reply", {
>       quotedMsgObj: message,
>     });
>     //does not work
>     return client.sendText(message.from, "my reply", {
>       quotedMsgId: message.t
>     });
>     //does not work
>     return client.sendText(message.from, "my reply", {
>       quotedMsgId: message.id
>     });
> ```

Hi, use:
```
  // A message with reply
 client.sendText('<number>@c.us', 'A simple message', {
  quotedMsg: 'true_...@c.us_3EB01DE65ACC6_out'
 });
```

**Comment by gekkedev** [comment]
So I need to supply the right value to `quotedMsg`? I thought I had done that; I took the ID property of the incoming message. Is this the wrong field? The one I used is `id` which has a string value like ` id: 'false_[redacted phone number]@c.us_C1F[...]58'`.
Once I understand how the non-deprecated approach works I can volunteer to amend an example into the documentation or add more JSDoc info.

**Comment by icleitoncosta** [comment]
> So I need to supply the right value to `quotedMsg`? I thought I had done that; I took the ID property of the incoming message. Is this the wrong field? The one I used is `id` which has a string value like ` 'false_[redacted phone number]@c.us_C1F[...]58'`. Once I understand how the non-deprecated approach works I can volunteer to amend an example into the documentation or add more JSDoc info.

Yes, exactly that way, you need to pass the id parameter. Regarding the documentation, I have already made a PR, but I am here analyzing other issues and fixing them to go along.

**Comment by gekkedev** [comment]
Your example worked for me when using the ID property:
```js
client.sendText(message.chatId, "my reply", { quotedMsg: message.id })
```
Obrigado.

I also tried
```js
client.sendText(message.chatId, "my reply", { quotedMsg: message })
```
which I thought should have worked according to the accepted types of `quotedMsg` where one accepted type is `[MsgModel](https://wppconnect.io/wa-js/classes/whatsapp.MsgModel.html)` (which I can see [here](https://github.com/wppconnect-team/wa-js/blob/a29b54fb862f3d085fd903ab3e30a65e547da87a/src/chat/functions/prepareRawMessage.ts#L183) is handled but it seems that the message object is not an instance of that WA.JS message class).
It yielded this error:
```js
Error when sending predefined query:  Error: Invalid quotedMsg
    at [...]\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:107:31
    at step ([...]\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:49:23)
    at Object.next ([...]\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:30:53)
    at fulfilled ([...]\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:21:58)
JS Stack: Error: Invalid quotedMsg
    at t.prepareRawMessage ([...]\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:174499)
    at async t.sendRawMessage ([...]\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:187654)
    at async t.sendTextMessage ([...]\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:191842)
    at async pptr:evaluate;C%3A%5C[...]%5Cnode_modules%5C%40wppconnect-team%5Cwppconnect%5Cdist%5Capi%5Chelpers%5Cevaluate-and-return.js%3A99%3A56:56:26
Function: function (_a) {
                            var to = _a.to, content = _a.content, options = _a.options;
                            return WPP.chat.sendTextMessage(to, content, __assign(__assign({}, options), { waitForAck: true }));
                        } {
  code: 'invalid_quoted_msg',
  quotedMsg: {}
}
```
created a PR to adjust the docs: #2265
