### ISSUE TITLE
`wapi.js injected` several times

### ISSUE THREAD

**Issue by renandecarlo** [wppconnect-team/wppconnect#2206]
## Description

It seems the current default wpp version 2.3000.1013232587-alpha causes the wapi.js to be injected several times at the first sync, leading to error in sent messages. After a restart, it works fine.

**It seems to be fixed by updating the wpp version to newer versions, or using `whatsappVersion: null`** 

ALSO: It seems wa-version is no longer generating main and beta wpp versions, just alpha ones

## Environment

- **WPPConnect version(s):** 1.31.0
- **WA-JS version(s):** 3.3.1
- **Browser:** Chrome 125
- **OS:** Windows 10
- **Node version:** Node 18
- **WhatsApp version:** 2.3000.1013232587-alpha

**Comment by Saifallak** [comment]
+1

**Comment by sandro-salles** [comment]
+1

**Comment by sandro-salles** [comment]
@renandecarlo still having issues on Ubuntu 22.04, even after setting that version manually.

**Environment**
WPPConnect version(s): 1.31.0
WA-JS version(s): 3.3.1
Browser: Chrome 125.0.6422.141
OS: Ubuntu 22.04
Node version: v18.19.1
WhatsApp version: 2.3000.1014090025-alpha

**Puppeteer versions:**
"puppeteer": "^22.10.0",
"puppeteer-extra": "^3.3.6",
"puppeteer-extra-plugin-stealth": "^2.11.2",
"puppeteer-extra-plugin-user-data-dir": "^2.4.1",
"puppeteer-extra-plugin-user-preferences": "^2.4.1",

![WhatsApp Image 2024-06-11 at 10 02 59](https://github.com/wppconnect-team/wppconnect/assets/1104617/8362836b-eb88-4ac9-b4fe-a0e5a7e64902)


Anyone?

**Comment by sandro-salles** [comment]
@renandecarlo already did that.. multiple times. no help... 

Using headless false, i can see that the instance is in fact authenticated:

![WhatsApp Image 2024-06-11 at 10 12 11](https://github.com/wppconnect-team/wppconnect/assets/1104617/6f9aa26f-8221-411d-a526-a9eeb815abdc)

Bu the process hangs for some time as **_Waiting page load_** and then i can see some exceptions in the console:

![WhatsApp Image 2024-06-11 at 10 11 28](https://github.com/wppconnect-team/wppconnect/assets/1104617/8b053d16-376a-4496-a4ea-445fdabc3d37)

**Comment by renandecarlo** [comment]
@sandro-salles i'm not sure then, maybe try an older version like `2.3000.1013710920-alpha` or `whatsappVersion: null`
It works for me with a bare minimum wppconnect instance on Windows 10

````js
const wppconnect = require('@wppconnect-team/wppconnect');


(async () => {
	try {
		wppconnect.defaultLogger.level = 'silly';

		const client = await wppconnect.create({
			session: 'wpp-session', 
			headless: false, 
			whatsappVersion: '2.3000.1013710920-alpha',
		});
	} catch(e) {
		console.error('-> Não foi possível inicializar o Whatsapp Web', e);
	}
})()````

![2024-06-11 10_46_14-Window](https://github.com/wppconnect-team/wppconnect/assets/6974980/c756ad29-aacf-4953-8ba7-794eb4e47f40)

**Comment by ademirMess** [comment]
+1

**Comment by gekkedev** [comment]
@Saifallak @sandro-salles @ademirMess if you want to say "plus 1" you can just react with a thumbs up. GitHub even hides repetitive replies.

**Comment by icleitoncosta** [comment]
https://github.com/wppconnect-team/wppconnect/pull/2213

Please, test this PR

**Comment by icleitoncosta** [comment]
Hey, please test this PR:
https://github.com/wppconnect-team/wppconnect/pull/2215
