### ISSUE TITLE
Constant for the maximum message length

### ISSUE THREAD

**Issue by gekkedev** [wppconnect-team/wppconnect#2234]
**Is your feature request related to a problem? Please describe.**
During development, a developer might want to send a message that exceeds the maximum length. There is a given length limit [in the documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#text-object).

**Describe the solution you'd like**
Could we add this as a constant? This saves developers some research time and lets them react to future changes to this limit without changing code.

**Describe alternatives you've considered**
Manually hardcoding it.

**Example**
```js
//WPPConnect source code
export const MAX_MESSAGE_LENGH: number = 4096;

//bot file
const { MAX_MESSAGE_LENGH } = require("@wppconnect-team/wppconnect")
```

**Comment by icleitoncosta** [comment]
In WhatsApp, the character limit isn't 4096 characters. I've tested with up to 9000 characters. It's possible to export a max length for this, but it's necessary to discover this limit.
