### ISSUE TITLE
Default device name

### ISSUE THREAD

**Issue by gekkedev** [wppconnect-team/wppconnect#2237]
As documented in the code, the device name of the *WhatsApp Web* instance gets set to `"WPPConnect"`:
https://github.com/wppconnect-team/wppconnect/blob/af74e7c42434fc71665725f281cabee28c07e61a/src/config/create-config.ts#L143
Won't this trigger bot detection far more often and should therefore be discouraged to avoid bans?

I would suggest picking a random user agent from a predefined list of believable user agents. Would you be open to a PR for this?

**Comment by icleitoncosta** [comment]
Hello, there are no cases related to banning using this custom parameter. WhatsApp uses other methods to identify bans, primarily detecting browser managers (which WPP already protects against) and detecting spam (which depends on the user).
