### ISSUE TITLE
Pre-evaluated boolean on message object for related mentions

### ISSUE THREAD

**Issue by gekkedev** [wppconnect-team/wppconnect#2241]
**Is your feature request related to a problem? Please describe.**
I tried to check if a message mentions my account and ended up implementing this:
```js
let myNumber
create(createOptions).then(client => {
  client.getWid().then(number => myNumber = number )

  client.onMessage(async (message) => {
    const wasMentioned = message.mentionedJidList.includes(myNumber)
    if (wasMentioned) console.log("I was mentioned! 😊")
  })
}
```

**Describe the solution you'd like**
Attach a new boolean like `mentionsMe` to message objects (text & image type only) which stores the result of the pre-evaluation.
```js
create(createOptions).then(client => {
  client.onMessage(async (message) => {
    if (message.mensionsMe) console.log("I was mentioned! 😊")
  })
}
```

**Describe alternatives you've considered**
Implemented it by myself.

**Additional context**
I'm willing to create a PR for this if the maintainers are interested in this feature.
Otherwise, would you accept this if I create a PR to add it to the documentation/examples?

**Comment by icleitoncosta** [comment]
Hey, so, it's not something we prefer to use natively within WPP, because it's something simple to implement in standard code, we always prefer to use as close as possible to what WhatsApp Web provides us, mainly to facilitate maintenance in case something changes.
