### ISSUE TITLE
Date label in Whatsapp Web appears in Portuguese

### ISSUE THREAD

**Issue by gekkedev** [wppconnect-team/wppconnect#2249]
## Description

In my English WhatsApp instance (that is the user language I chose), Sexta-Feira is the only word that isn't English.
![image](https://github.com/wppconnect-team/wppconnect/assets/17025257/07c449ca-c4e0-4225-8fa6-e446c3876bd7)

chat list also says "domingo":
![image](https://github.com/wppconnect-team/wppconnect/assets/17025257/88a73078-2fbd-4b66-a8c9-049c4fb1ecde)

## Environment

- **WPPConnect version(s):** 1.32.3
- **WA-JS version(s):** 3.4.1
- **Browser:** Chrome 126
- **OS:** Windows 11
- **Node version:** Node 18
- **WhatsApp version:** 2.3000.1013991265
- **MultiDevice (BETA):** no?

## Steps to Reproduce

Open WhatsApp web, make sure you open an older chat with messages not labeled as "today".

## Additional context / Screenshot
not high priority IMHO 😄

**Comment by icleitoncosta** [comment]
Fixed injecting the versions after  2.3000.x
