### ISSUE TITLE
Quando a lista é respondida nada é retornado no onMessage.

### ISSUE THREAD

**Issue by MatheusScarpim** [wppconnect-team/wppconnect#2252]
## Description
Logo após enviar uma lista, eu a respondo, mas o onMessage não me retorna nada.

## Environment

- **WPPConnect version(s):** 1.32.3
- **WA-JS version(s):** 3.4.1
- **Browser:** Chromium 
- **OS:** Docker
- **Node version:** Node 20.9.0
- **WhatsApp version:** 2.3000.10139x
- **MultiDevice (BETA):**  No

**Comment by gekkedev** [comment]
tens um code snippet?

**Comment by icleitoncosta** [comment]
The lists normally reach the response in the library, here is an example of how you can receive the response:
``` 
wppconnect
  .create({
    headless: false,
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    console.log(message);
  });
}
```

**Comment by willpexeroo** [comment]
@icleitoncosta, isso só funciona para chats @c.us, se voce tentar com chat @lid e ele responder uma mensagem sua como 'resposta' nada é capturado.
