### ISSUE TITLE
TypeError: client.createtProduct is not a function

### ISSUE THREAD

**Issue by Bayyn** [wppconnect-team/wppconnect#2270]
## Description

Whenever you create a product, this error is returned by promise.

## Environment

WPPConnect version(s): 1.32.3
WA-JS version(s): 3.4.1
Browser: Chrome 126
OS: macOS 14.1.1
Node version: Node 18
WhatsApp version: 2.3000.1013991265
MultiDevice (BETA): no?

## Steps to Reproduce

[First Step]
Connect on whatsapp by wpp connect

[Second Step]
Use the method client.createtProduct() to create a product to an already verified number that exists.

[and so on...]
I see the error happen and fall into the promise catch

## Log Output

```
If relevant, paste all of your Log Output
```

error:    Unhandled Rejection: TypeError: client.createtProduct is not a function
    at EventEmitter.<anonymous> (/Users/x/wpconnect/test.js:74:14)
    at EventEmitter.emit (node:events:518:28)
    at /Users/x/wpconnect/node_modules/@wppconnect-team/wppconnect/dist/api/layers/listener.layer.js:154:87

```
client.createtProduct(
        "Product name",
        "base64:img",
        "product description",
        "89.90",
        true,
        "https://wppconnect.io",
        "AKA001"
      );
```

**Comment by icleitoncosta** [comment]
Tried you use client.createProduct intead of createtProduct?

**Comment by Bayyn** [comment]
> Tried you use client.createProduct intead of createtProduct?

Sorry, https://wppconnect.io/wppconnect/classes/Whatsapp.html#createProduct
I copied it from here, I didn't pay attention.
