### ISSUE TITLE
@icleitoncosta

### ISSUE THREAD

**Issue by Alababdiy** [wppconnect-team/wppconnect#2297]
@icleitoncosta 
still now working

_Originally posted by @Alababdiy in https://github.com/wppconnect-team/wppconnect/issues/2042#issuecomment-2259178198_

**Comment by icleitoncosta** [comment]
Hi! What does not work?

**Comment by icleitoncosta** [comment]
> @icleitoncosta TypeError: client.forwardMessages is not a function

Remove 's' from final function name

https://wppconnect.io/wppconnect/classes/Whatsapp.html#forwardMessage
