### ISSUE TITLE
Implementar na função REPLY o envio de MÍDIAS

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#230]
Seria muito bacana se no REPLY pudesse usar as funções de envio de mídia que já temos hoje.

Algo como:

async function newReply(client, whatsapp, content, caption, id_message) {
    await client.reply(
        whatsapp,
        file('URL_TO_FILE')', 
        "caption aqui",
        id_message.toString()
    ) .catch(err=> console.log(err)) ;
}

Desta forma poderíamos passar no CONTENT um URL de um arquivo, igual no sendFile, etc.

**Comment by mvac1991** [comment]
@edgardmessias fechou a ISSUE também e não escreveu nada, o que houve?

**Comment by edgardmessias** [comment]
Isso será implementado na V2 da lib, mas caso queira implementar antes, sinta-se livre em fazer PR
