### ISSUE TITLE
 Is there any function for load chat message with paginate ?

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#231]
Is there any   function for load chat message with paginate ?

loadAndGetAllMessagesInChat  with paginate  ?

**Comment by tomsilva** [comment]
Hiii, the funciona is loadEarlierMessages , this loadAndGetAllMessagesInChat  function charge asll message...

**Comment by Lucipher** [comment]
> Hiii, the funciona is loadEarlierMessages , this loadAndGetAllMessagesInChat function charge asll message...

Well noted with thanks!
