### ISSUE TITLE
Delete messages for all participants in a group

### ISSUE THREAD

**Issue by hugoruizsanchez** [wppconnect-team/wppconnect#2312]
I'm interested in having the API delete messages for everyone in a group.  In the Swagger documentation, delete-message doesn't seem to introduce options for this. Is there really no way to achieve it? I'm on the latest version 2.6.0,

![image](https://github.com/user-attachments/assets/41c09551-a3af-4c9f-9094-802ceb6657bc)

The only options available are to delete it locally

**Comment by icleitoncosta** [comment]
Hi @hugoruizsanchez , yeah, it is possible

See payload:
```
{
  "phone": "1203630@g.us",
  "isGroup": true,
  "messageId": "messageId@g.us_3EB0434B37A6561@c.us",
  "deleteMediaInDevice": true
}
```

**Comment by icleitoncosta** [comment]
I will improov docs on Swagger server
