### ISSUE TITLE
Erro - create (phoneNumber) codigo conexao -celular  - Não retorna o codigo lib fica aguardando infinitamente  o codigo

### ISSUE THREAD

**Issue by jaderesp** [wppconnect-team/wppconnect#2313]
## Description

[Ao inicializar a lib (sessao) create informando o paramentro config.phoneNumber (gerar codigo de conexão via celular) a lib executa a função para geração do codigo, porém o codigo nunca é gerado, ao debugar a função WPP.conn.genLinkDeviceCodeForPhoneNumber(), é exibido um erro incomum (try catch), e o codigo não é retornado o que a Promise da função nunca é resolvida nem retornada.]
![Screenshot_167](https://github.com/user-attachments/assets/5db78c37-5ccf-420b-abfc-8f1cbb388454)
![Screenshot_165](https://github.com/user-attachments/assets/9ae400ae-5966-4183-aae6-a8af73e50003)
![Screenshot_154](https://github.com/user-attachments/assets/fb1acdd8-6a45-4395-9187-42205553b0f6)

**Comment by icleitoncosta** [comment]
Ola @jaderesp 

Testei a função e está funcionando normalmente, verifique a sua função create, segue exemplo da forma correta.

```
wppconnect
  .create({
    session: 'sessionName',
    phoneNumber: '5521999999999',
    logQR: true,
    catchLinkCode: (str) => { 
      console.log('Vamos ao codigo');
      console.log(str);
    }
  })
  .then((client) => start(client))
  .catch((error) => {
    console.log(error);
  });
```
