### ISSUE TITLE
Na função ONSTATECHANGE alguns clients mostram UNPAIRED o tempo inteiro

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#232]
Isso acontece com alguns clients, já fiz vários testes de instabilidade mas ainda não consegui encontrar um motivo lógico que está causando isso.

Mesmo o client estando conectado, sem encerrar as sessões no celular, o WPP Connect mostra UNPAIRED:

![image](https://user-images.githubusercontent.com/35501007/119844022-73380380-bede-11eb-9c1e-d2791f62417a.png)

Estou a vários dias tentando descobrir a causa do problema mas sem sucesso.

**Comment by mvac1991** [comment]
Veja que os disparos em massa são realizados e mesmo durante os envios o WPPConnect mostra que o celular foi desemparelhado, e não foi.

![image](https://user-images.githubusercontent.com/35501007/120074469-6d275b80-c073-11eb-9e21-424d457db5c4.png)

**Comment by edgardmessias** [comment]
Foram feitas algumas alterações no servidor, abrir nova issue caso continue
