### ISSUE TITLE
Interactive messages

### ISSUE THREAD

**Issue by phillipnunes** [wppconnect-team/wppconnect#2327]
Is it possible to send interactive messages using this library? Like a menu with options? Here is what I mean:
https://developers.facebook.com/blog/post/2022/11/21/sending-interactive-messages/

![image](https://github.com/user-attachments/assets/a0e32306-8582-4645-88e0-7371e39f8c35)

Thanks for the support!

**Comment by icleitoncosta** [comment]
Can you use listMessage

**Comment by phillipnunes** [comment]
> Can you use listMessage

This one @icleitoncosta ?
https://wppconnect.io/wppconnect/classes/Whatsapp.html#sendListMessage

**Comment by icleitoncosta** [comment]
> > Can you use listMessage
> 
> 
> 
> This one @icleitoncosta ?
> 
> https://wppconnect.io/wppconnect/classes/Whatsapp.html#sendListMessage

Yeah, is it

But in the next release of wppconnect, buttons are back, and you can use that

**Comment by phillipnunes** [comment]
Ok, thanks @icleitoncosta
