### ISSUE TITLE
How return the QR code to the frontend?

### ISSUE THREAD

**Issue by phillipnunes** [wppconnect-team/wppconnect#2330]
I'm not sure if here is the best place for technical questions, so please, let me know.

I have this code inside my backend in Nest.js, it comes from the documentation.
I don't want to generate the image in the backend, I want to return the QR Code (likely the image content inside the matches variable or imageBuffer variable) to the frontend, but turns out this function doesn't respond to anything until you scan the QR code generated.

So, how can I return the QR Code data to the frontend application? What am I missing here, do I have to use another method, or what? 
Thanks for any help, I am more of a frontend guy.

```ts
import { Injectable } from '@nestjs/common';
import { CreateSession } from '../dtos/whatsapp';
import { create } from '@wppconnect-team/wppconnect';

@Injectable()
export class WhatsappService {
  constructor() {}

  async createSession(data: CreateSession) {
    try {
      const client = await create({
        session: 'sessionName',
        catchQR: (base64Qr, asciiQR) => {
          console.log(asciiQR);
          const matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
            response = {};

          if (matches.length !== 3) {
            return new Error('Invalid input string');
          }

          response.type = matches[1];
          response.data = new Buffer.from(matches[2], 'base64');

          const imageBuffer = response;
          // require('fs').writeFile(
          //   'out.png',
          //   imageBuffer['data'],
          //   'binary',
          //   function (err) {
          //     if (err != null) {
          //       console.log(err);
          //     }
          //   },
          // );
        },
        logQR: false,
      });

      start(client);
    } catch (error) {
      console.log(error);
    }

    function start(client) {
      client.onMessage((message) => {
        if (message.body === 'Hi' && message.isGroupMsg === false) {
          client
            .sendText(message.from, 'Welcome to Wppconnect')
            .then((result) => console.log('Result', result))
            .catch((error) => {
              console.error('Error when sending: ', error); //return error object
            });
        }
      });
    }
  }
}

```

**Comment by ethan2cl** [comment]
You can use Object to save the client, where the key is the phone number and the value is the client. After creating the client, save it and bind an "info" attribute to it. In the CatchQR method, bind the urlCode to the client. info. urlCode, and when the frontend requests it, simply provide the client. info. urlCode to the frontend. It should also be feasible to put it into Redis.

**Comment by ethan2cl** [comment]
You can use Object to save the client, where the key is the phone number and the value is the client. After creating the client, save it and bind an "info" attribute to it. In the CatchQR method, bind the urlCode to the client. info. urlCode, and when the frontend requests it, simply provide the client. info. urlCode to the frontend. It should also be feasible to put it into Redis.

**Comment by thf4** [comment]
@phillipnunes  just use next() function in nestjs controller to return a object of res. You can following examples inside the project like this passing res to your function like this:


```
  @Post('create-session')
  async login(
    @Req() req: Request, @Res() res: Response, @Body() payload: CreateSessionDto, @Next() next: NextFunction
  ): Promise<any> {
    await this.loginUseCase.execute(req, res, payload);
    next();
  }
```
Service: Inside catchQR:
````
qrCode = qrCode.replace('data:image/png;base64,', '');

    if (res && !res.headersSent) {
      res.status(200).json({
        status: 'QRCODE',
        qrcode: qrCode,
        urlcode: urlCode,
      });
    }
````

**Comment by phillipnunes** [comment]
Thanks @thf4 , your suggestion just solved my issue. I appreciate it.
