### ISSUE TITLE
Como obter meu proprio numero? How to get my own number?

### ISSUE THREAD

**Issue by willpexeroo** [wppconnect-team/wppconnect#2391]
PT
O client.getMe() nao está mais disponível e o getHostDevice nao retorna o parâmetro Phone conforme descrito aqui:
[](https://wppconnect.io/wppconnect/interfaces/HostDevice.html)

Alguem sabe como faço para obter o meu próprio número de telefone ou o id de chat associado a conta do whatsapp que iniciou a sessão?
 
 
 --
 ENG
 client.getMe() is no longer available and getHostDevice does not return the Phone parameter as described here:
[](https://wppconnect.io/wppconnect/interfaces/HostDevice.html)

Does anyone know how I can get my own phone number or the chat id associated with the WhatsApp account that initiated the session?

**Comment by icleitoncosta** [comment]
You can use `client.getWid()`
