### ISSUE TITLE
onMessage nao monitora mensagens citadas corretamente

### ISSUE THREAD

**Issue by willpexeroo** [wppconnect-team/wppconnect#2392]
onMessage nao consegue enxergar mensagens citadas se forem de chats @lid, apenas chats @c.us sao monitorados.

Já tentei de tudo e nada resolve.

**Comment by willpexeroo** [comment]
Claro, como consigo te ajudar nisso?

**Comment by icleitoncosta** [comment]
> Claro, como consigo te ajudar nisso?

Por favor, me chama dentro do grupo do whatsapp, Cleiton

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/2a40d0126c6c4f16ae27add91f4fc7d1263073af
