### ISSUE TITLE
getProfilePicFromServer() não retorna dados

### ISSUE THREAD

**Issue by leonardokatayama** [wppconnect-team/wppconnect#240]
## Description

Realizando alguns testes verifique que getProfilePicFromServer() não retorna os dados quando o chatId não esta ativo em uma conversa.

Para reproduzir:
- getAllContacts(), peguei um dos contatos que ainda não estava com o chat aberto. 
- Passei o chatId para o getProfilePicFromServer(chatID), não retornou a imagem, quando olho no celular esse mesmo contato possui imagem, quando vou em nova conversa.

Inclusive a o getAllContacts devolve o profilePicThumbObj preenchido apenas das conversas em aberto também.
A necessidade seria preencher a lista de contatos para abrir uma nova conversa e aparecer a foto.

Segue alguns prints
<img width="1433" alt="Screen Shot 2021-06-01 at 10 30 47" src="https://user-images.githubusercontent.com/8225114/120332145-d5b94700-c2c4-11eb-83ff-48f649e5cdf9.png">
<img width="1433" alt="Screen Shot 2021-06-01 at 10 30 59" src="https://user-images.githubusercontent.com/8225114/120332169-dbaf2800-c2c4-11eb-8eb0-a79cf2eb88a5.png">
<img width="1435" alt="Screen Shot 2021-06-01 at 10 32 33" src="https://user-images.githubusercontent.com/8225114/120332198-e10c7280-c2c4-11eb-9932-c7400f373950.png">
<img width="1433" alt="Screen Shot 2021-06-01 at 10 33 04" src="https://user-images.githubusercontent.com/8225114/120332208-e49ff980-c2c4-11eb-82b0-3213aab50369.png">
![WhatsApp Image 2021-06-01 at 10 26 45 (1)](https://user-images.githubusercontent.com/8225114/120332260-f2557f00-c2c4-11eb-8128-c41b6f5dbee2.jpeg)
![WhatsApp Image 2021-06-01 at 10 26 45](https://user-images.githubusercontent.com/8225114/120332270-f386ac00-c2c4-11eb-9b42-397c02c016f2.jpeg)

O contato Renan Alves possui foto, porém não retorna pois não esta ativo como conversa.
Já o contato (ATIVO) LEONARDO YOSHITERO KATAYAMA, possui foto e retorna conforme esperado, pois esse tem uma conversa ativa.

Complementando, acabei de verificar que quando arquiva a conversa, o server deixa de devolver o profilePicThumbObj também. Dessa forma conversas arquivadas também não vem a foto.

## Environment

- **Wppconnect version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

**Comment by edgardmessias** [comment]
Resolvido na versão 1.7
