### ISSUE TITLE
addNewLabel not creating a new label

### ISSUE THREAD

**Issue by ImPedro29** [wppconnect-team/wppconnect#2400]
## Description
The function addNewLabels it's just not creating the new label

## Environment

- **WPPConnect version(s):** 1.35.0
- **WA-JS version(s):** 3.12.1
- **Browser:** Chrome XX / Chromium XX
- **OS:** OSX 15.0.1
- **Node version:** Node 20.
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Just call addNewLabel 
2. Check label on business whatsapp

## Log Output
No error logs

## Your Code

Available on: https://github.com/billbarsch/myzap/blob/myzap2.0/functions/WPPConnect/business.js
```
    static async addNewLabel(req, res) {

        try {
            let data = await Sessions.getClient(req.body.session)
            let response = await data.client.addNewLabel(req.body.name)

            res.status(200).json({
                "result": 200,
                "token": response
            })

        } catch (error) {

            logger.error(`Error on getClientTokenBrowser: ${error?.message}`)

            res.status(400).json({
                response: false,
                data: error?.message
            });
        }

    }
```

**Comment by icleitoncosta** [comment]
Update your whatsappVersion and test again
