### ISSUE TITLE
how i can send message to channel ?

### ISSUE THREAD

**Issue by appujet** [wppconnect-team/wppconnect#2421]

**Comment by icleitoncosta** [comment]
```
client.sendText('<number>@newsletter, 'A simple message');
```

**Comment by jamesxt94kode** [comment]
sorry, how i can get the id from a previously newsletter created on app? @icleitoncosta

**Comment by icleitoncosta** [comment]
> sorry, how i can get the id from a previously newsletter created on app? @icleitoncosta 

Open the chat in whatsappp and  `WPP.chat.getActiveChat`

**Comment by jamesxt-94** [comment]
not working send to newsletter, in last version
