### ISSUE TITLE
Erro na função / Function error: *removeParticipant

### ISSUE THREAD

**Issue by ikarofsouza** [wppconnect-team/wppconnect#256]
Estou tentando remover alguns participantes usando a função *removeParticipant, não dá erro nenhum... Quando vou olhar o response da função, o resultado é **false*.

Código:
await client.removeParticipant(id_grupo, contato);

---------------------------------------------------------------------------------------

I'm trying to remove some participants using the *removeParticipant function, it doesn't give any error... When I look at the function's response, the result is **false*.

Code: 
await client.removeParticipant(id_grupo, contato);

![Sem Título-1](https://user-images.githubusercontent.com/48399495/121592397-8a283b00-ca32-11eb-8b31-ac37fc476911.png)

**Comment by edgardmessias** [comment]
Olá, eu revisei o código, e ele responderá false para quando o contato não estiver mais no grupo.
