### ISSUE TITLE
Melhorias na importação de conversas

### ISSUE THREAD

**Issue by devpremium** [wppconnect-team/wppconnect#282]
Problema da função loadEarlierMessages: Começa a partir da vigésima mensagem e não da ultima mensagem enviada/recebida e não possibilita voltar ao inicio caso ocorra algum erro.

Problema da função loadAndGetAllMessagesInChat: Impossibilita o uso de outras funções enquanto esta sendo utilizado.

Gostaria que a função loadEarlierMessages (ou uma nova função) recebesse o parâmetro (id da mensagem) de onde começar a carregar as mensagens no chat, assim possibilitando gerar intervalos no carregamento ou no caso de uma desconexão do aparelho (desconexão do sistema), carregar apenas as ultimas mensagens que ainda não foram gravadas, assim evitando que precise rodar a função loadAndGetAllMessagesInChat para pegar apenas as mensagens trocadas durante essa desconexão, alem disso essa nova função iria possibilitar a importação por partes ao invés de importar tudo de uma vez.

**Comment by tomsilva** [comment]
Opa, eu estive testando essas duas funcoes, e as duas estao funcionando 
o loadEarlierMessages = server para vc carregar as mensagens anterioes tipo paginacao, no whatsapp web e a funcao de quando vc clica em um chat ele vai abrir mensagens limitadas e quando vc rola com o scroll ele vai carregando .... 

loadAndGetAllMessagesInChat = essa funcao faz o que vc diz, ela carrega todo o chat isso demora mais ....

**Comment by devpremium** [comment]
Entao @tomsilva mas as duas tem pequenos ploblemas que relatei ali por isso solicitei uma nova função, a loadAndGetAllMessagesInChat é otima para pequenos chats.

**Comment by edgardmessias** [comment]
Agora com a função nova [getMessages](https://wppconnect-team.github.io/wppconnect/classes/whatsapp.html#getmessages) acredito que vá ajudar a todos em vários casos.

Ainda é preciso melhorar a parte de serialização, que inclui muitos dados redundantes a toa, fazendo isso demorar a carregar como um todo.
