### ISSUE TITLE
Reduzir a quantidade de informações no retorno das mensagens

### ISSUE THREAD

**Issue by devpremium** [wppconnect-team/wppconnect#289]
Remover informações que se repete no retorno das funções de get messages, tais como informações do contato, links de imagem de perfil, id do chat (pois se estou fazendo a requisição já tenho o id), ou no caso de mensagens de grupos remover as informações de participante, e outras coisas que se repetem assim deixando o retorno mais leve e fácil de implementar pois vai ter só o necessário.
Assim se precisar de alguma informação a respeito do contato ou grupo usar a função para receber essas informações referentes ao chat e remove-las do retorno da mensagem.

**Comment by edgardmessias** [comment]
@devpremium , na versão 1.7.3 reduzi um monte de dados enviados, poderia validar e ver mais pontos que seriam interessantes para realizar a redução?

**Comment by edgardmessias** [comment]
Acredito que a redução feita até agora vá ajudar.

Caso veja que tenha mais informações interessantes para remover, reabrir esse ticket
