### ISSUE TITLE
Implementar Thumbnail ampliada em SendLinkPreview

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#298]
Quando enviamos um link do Youtube por mensagem, aparece uma Thumbnail diferente, um pouco mais ampliada, com opção de dar play no vídeo (caso seja do Youtube ou Facebook)

![image](https://user-images.githubusercontent.com/35501007/124501983-ef085400-dd98-11eb-8a19-c4b050e9d953.png)

Gostaria que implementassem essa opção também no WPP.

**Comment by moskoweb** [comment]
@edgardmessias se não me engano seria preciso digitar o texto com o link e dar um tempo para o WhatsApp gera a thumbnail maior para depois enviar a mensagem.

**Comment by GMUNDI** [comment]
O facebook tem uma função de depuração que gera/atualiza a miniatura e as info para gerar o thum, talvez possa ser uma opção criar um processo parecido:
https://developers.facebook.com/tools/debug/

**Comment by edgardmessias** [comment]
Conforme conversado no Discord, a miniatura grande só ocorre quando a página em questão tem vídeo como principal ponto de exibição

**Comment by mvac1991** [comment]
> Conforme conversado no Discord, a miniatura grande só ocorre quando a página em questão tem vídeo como principal ponto de exibição

@edgardmessias , conforme conversado no WhatsApp, não, não acontece só com vídeo.

A thumbnail ampliada aparece tanto com IMAGEM quanto com VÍDEO.

Exemplo disso é um post no INSTAGRAM que havia enviado pra vc na época que estávamos falando sobre isso JULHO de 2021

E é como o @moskoweb disse acima, no WhatsApp Web precisa colar o link no campo de digitar mensagem e aguardar alguns segundos pra aparecer as info. Ao enviar, aparece como ampliada, do jeito que havia pedido a vc que implementasse na LIB.

**Comment by mvac1991** [comment]
@edgardmessias só quero saber se é possível implementar na LIB.

**Comment by edgardmessias** [comment]
@mvac1991 , eu já te falei isso várias e várias vezes, o recurso disponível no WhatsApp WEB não permite isso.

Existem outros pontos mais importantes que eu quero ver no momento, então estou fazendo uma limpa nas issues.

Sinta-se livre em fazer um PR com o recurso solicitado caso você consiga desenvolve-lo

**Comment by mvac1991** [comment]
> @mvac1991 , eu já te falei isso várias e várias vezes, o recurso disponível no WhatsApp WEB não permite isso.
> 
> Existem outros pontos mais importantes que eu quero ver no momento, então estou fazendo uma limpa nas issues.
> 
> Sinta-se livre em fazer um PR com o recurso solicitado caso você consiga desenvolve-lo

Então é mais fácil vc escrever assim na ISSUE que quer "limpar":

"Estou fechando a ISSUE pq estou fazendo uma limpa e tenho outras ISSUES que julgo ser mais importante".

Melhor do que colocar uma justificativas que não faz sentido.
