### ISSUE TITLE
Implementar função "sendCallNotification"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#300]
Basicamente a função "sendCallNotification" iria dar apenas 1 TOQUE por ligação (poderiamos optar por VÍDEO ou VOZ) e encerrar a ligação.

Só pra mostrar uma notificação para o destinatário => "1 ligação de voz perdida", isso ajuda em nossas estratégias de marketing.

**Comment by mvac1991** [comment]
Pq foi fechado?

**Comment by edgardmessias** [comment]
Pois é um recurso impossível de implementar no momento
