### ISSUE TITLE
Metodo getallchatwhitmessages nao vem a url do da fotoperfil do contato

### ISSUE THREAD

**Issue by tomsilva** [wppconnect-team/wppconnect#308]
**Is your feature request related to a problem? Please describe.**
Pelo que vi no front antes tinha esse objeto no retorno nas ultimas atualizacoes parece que foi retirado

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edgardmessias** [comment]
Esse recurso será descontinuado em favor de chamada de pegar a URL individualmente, pois é um recurso caro em termos de processamento para ser chamado todas as vezes
