### ISSUE TITLE
Quando uso o downloadMedia 3 vezes na quarta ele da erro e fecha o wppconnect

### ISSUE THREAD

**Issue by devpremium** [wppconnect-team/wppconnect#309]
## Description
Quando uso a função downloadMedia 3 passando ids diferentes na quarta ele da erro e fecha o wppconnect

## Environment

- **Wppconnect version(s):** Ultima
- **Browser:** Chrome 87
- **OS:** Debian 10
- **Node version:** v16.4.0

![image](https://user-images.githubusercontent.com/52453013/124822413-3d0e8a80-df46-11eb-959d-b42d5ea4a555.png)

**Comment by devpremium** [comment]
Na verdade o bug acontece quando tento fazer um download de uma imagem que não esta disponivel

**Comment by edgardmessias** [comment]
Na versão 1.8.2 melhorei a mensagem de erro e a possibilidade de tratamento de erro.

Ou seja, se você capturar o erro com um `.catch` ou `try ... await ... catch`, você poderá verificar qual foi a mensagem de erro.

Nessa versão que você mostrou, provavelmente o `object Object` é:
```js
{
      error: true,
      code: 'media_not_found',
      message: 'Media not found',
}
```
