### ISSUE TITLE
Erro: "Evaluation failed"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#314]
Mesmo tendo colocado TRYCATCH em todos os eventos da LIB, percebo que, quando o browser do client é encerrado a LIB ainda continua operando. E quando isso acontece, esse erro mata minha aplicação node, derrubando todo os outros usuários:

![image](https://user-images.githubusercontent.com/35501007/125007160-0a43bf80-e036-11eb-9ef0-d8a9574cf4bb.png)

Gostaria de saber o que posso fazer pra melhorar isso, pois como dito acima, mesmo colocando TRYCATCH em tudo, o erro da LIB as vezes não cai no meu CATCH.

**Comment by edgardmessias** [comment]
versão v1.8.6 resolveu esse tipo de problema
