### ISSUE TITLE
mobile logout token will not be auto deleted

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#316]
1. mobile logout token will not be auto deleted 
2, mobile relogin other bowser the token will be deleted and the status still inchat

**Comment by leobevi** [comment]
I think you have to control this in the client.onStateChange event
When logged out you close the client, this way it won't generate your error.

 client.onStateChange( async (state) => {
              if(state == 'UNPAIRED'){
                client.close();
            }
      
    });

**Comment by edgardmessias** [comment]
@Lucipher , could you provide a short example of code to reproduce?

**Comment by Lucipher** [comment]
After update version to 1.8.1 it works

**Comment by Lucipher** [comment]
version 1.8.5 not work
![image](https://user-images.githubusercontent.com/1323545/126307578-4bb1d262-45d0-4dec-9969-d69832a776d9.png)

token not delete
![image](https://user-images.githubusercontent.com/1323545/126307674-3ff76eeb-c0b2-4512-8e02-e29b9d58592d.png)

**Comment by Lucipher** [comment]
@edgardmessias

**Comment by Lucipher** [comment]
![image](https://user-images.githubusercontent.com/1323545/126446784-084ba806-e9c7-4633-a639-a773d3ec5d1f.png)
