### ISSUE TITLE
Erro ao enviar áudio M4A

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#329]
Gostaria que liberassem M4A nos envios da LIB, tanto em sendFile, sendAudio e sendPtt, pois está retornando este erro.
![image](https://user-images.githubusercontent.com/35501007/125868556-33930f60-79b9-48cc-9164-1d335313a64b.png)

Se puderem permitir todos os formatos de áudio, evita que tenhamos problemas futuros com outros modelos.

Ou também pensar na possibilidade de implementar algo que já converta o áudio em um formato permitido, etc

**Comment by leobevi** [comment]
Salve!!
Não vejo este problema como um bug. Creio que para envio via link este repositório onde está o arquivo deva dar permissão de acesso à LIB para que ela faça o download e envie. Quanto a conversão existe um método de envio como base64 onde você mesmo pode converter e enviar seus arquivos.
