### ISSUE TITLE
Função "sendMessageOptions" retorna MESSAGE.ID inválido no evento ONMESSAGE

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#366]
Estou usando esta função para enviar botões e funciona. Porém, quando o usuário CLICA no button ele retorna um MESSAGE.ID inválido no evento ONMESSAGE, meu código está assim:

![image](https://user-images.githubusercontent.com/35501007/127237958-50b79a00-516f-4bf5-8997-4345a9b43179.png)

**Comment by edgardmessias** [comment]
Não consegui reproduzir esse problema.

**Comment by lepokoloko** [comment]
alguem tem um exemplo que como consigo enviar os botoes de forma dinamica, vindo de um arquivo externo ou um banco de dados, ou seja, em alguns casos, podem haver 2 botoes, 3 botoes, 4botoes etc...
