### ISSUE TITLE
Erro com checkNumberStatus - versão 1.8.9

### ISSUE THREAD

**Issue by leobevi** [wppconnect-team/wppconnect#372]
Quando utilizada a função com um número inválido retorna  TypeError: Cannot read property 'wid' of null

![checknumber](https://user-images.githubusercontent.com/17435878/127414183-410296f3-ce9b-44ad-9ddd-6556cd424e86.jpg)

Percebe-se também que independente do resultado ele sempre trará valor verdadeiro para canReceiveMessage, se um numero válido bloqueado neste caso enviaria da mesma forma?

**Comment by Sulivan1999** [comment]
Também estou a aguardar uma correção para este mesmo erro. @edgardmessias

**Comment by edgardmessias** [comment]
Bom dia, hoje sai a correção
