### ISSUE TITLE
error after autocloseCalled when set autoClose = 60000

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#373]
error after autocloseCalled when set autoClose = 60000

![image](https://user-images.githubusercontent.com/1323545/127450317-f25c4aa9-d5d5-41bc-b441-70fce8c76c2b.png)

**Comment by Lucipher** [comment]
![image](https://user-images.githubusercontent.com/1323545/127731777-b40d665a-52b8-4664-b360-04775b55d0fd.png)
after throw the error it cause  process exit

**Comment by Lucipher** [comment]
@edgardmessias

**Comment by edgardmessias** [comment]
@Lucipher , what you think is wrong?

You must use `catch` to check the error and execute a correct treatment for that.

The objective of `create` is create a client, but if it is not connected after auto close, `create` will generate an error

**Comment by Lucipher** [comment]
@edgardmessias 

I try catch the error when  create a client but the  process exit first

**Comment by edgardmessias** [comment]
@Lucipher , I checked it and is working fine.

Could you show us how you are trying?

**Comment by moskoweb** [comment]
The "close" method is not working yet.
