### ISSUE TITLE
SENDFILE e SENDTEXT retornam "TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#378]
As duas funções estão retornando o mesmo erro.
![image](https://user-images.githubusercontent.com/35501007/127703224-f705b951-bbb4-4976-828d-9de393bd9851.png)

**Comment by edgardmessias** [comment]
Certo, o print é bonito, mas não fala como você gerou o erro, rsrsrs

**Comment by mvac1991** [comment]
> Certo, o print é bonito, mas não fala como você gerou o erro, rsrsrs

O código do send_video
![image](https://user-images.githubusercontent.com/35501007/127703535-0bba2ac8-d0b6-4a39-b50e-bbdf5072f5dd.png)

O código do send_text
![image](https://user-images.githubusercontent.com/35501007/127703585-a06f7f33-d652-4b4b-90fb-fb10a4db91ec.png)

**Comment by claudioscarpafilho** [comment]
No parametro to_whatsapp você está enviando: "5511999999999@c;.us"? ou somente "5511999999999"?
