### ISSUE TITLE
Erro nas funções 'sendFile' e 'sendPtt';

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#379]
## Description

Erro na função sendFile:
![image](https://user-images.githubusercontent.com/35501007/127727658-44be0562-5d57-4655-ac0c-fba6ce389941.png)

Erro na função sendPtt:
![image](https://user-images.githubusercontent.com/35501007/127727672-52b01b33-f302-4610-a591-62d3693f0c04.png)

## Environment

- **Wppconnect version(s):** **1.8.10**
- **Browser:** **Chrome 7.6.0**
- **OS:** **LINUX CENTOS**
- **Node version:** **v15.11.0**

## Steps to Reproduce

SENDPTT
1. Erro ao chamar await client.sendPtt (to_whatsapp, url_file, 'audio.ogg')
2. to_whatsapp é substituido por '554499994444@c.us', url_file é substituido por 'https://site.com/audio.mp3'
![image](https://user-images.githubusercontent.com/35501007/127727776-0c7766ce-fbe3-4c13-8686-500d7e968a53.png)

SENDFILE
1. await client.sendFile (to_whatsapp, url_file, 'video.mp4', caption) 
2. to_whatsapp é substituido por '554499994444@c.us', url_file é substituido por 'https://site.com/audio.mp3' e caption  é substituido por 'texto qualquer';
![image](https://user-images.githubusercontent.com/35501007/127727844-3b604fc2-670a-4fba-a233-02e99d43163d.png)

## Log Output
Erro no evento: 'send_image > client.sendFile'. Erro 52 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|App    | Erro no evento: 'record_audio > client.sendPtt'. Erro 55 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|App    | Erro no evento: 'send_pdf > client.sendFile'. Erro 56 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|App    | Erro no evento: 'record_audio > client.sendPtt'. Erro 55 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at runMicrotasks (<anonymous>)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|App    | Erro no evento: 'send_video > delay'. Erro 53 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Mostlikely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at runMicrotasks (<anonymous>)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
0|App    | Erro no evento: 'record_audio > client.sendPtt'. Erro 55 ->  Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|App    |     at CDPSession.send (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
0|App    |     at ExecutionContext._evaluateInternal (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
0|App    |     at ExecutionContext.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
0|App    |     at DOMWorld.evaluate (/home/zapmutacao/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
0|App    |     at runMicrotasks (<anonymous>)
0|App    |     at processTicksAndRejections (node:internal/process/task_queues:94:5)

If relevant, paste all of your Log Output
```

## Your Code
async function record_audio(client, to_whatsapp, url_file, timeWait) {
    if (url_file!="" && url_file!="null" && url_file!="undefined") {
        try {
            await delay(timeWait)   
        } catch (error) {
            console.log("Erro no evento: 'record_audio > delay. Erro 43 -> ", error) 
        }
        try {
            await client.sendPtt (to_whatsapp, url_file, 'audio.ogg')    
        } catch (error) {
            console.log("Erro no evento: 'record_audio > client.sendPtt'. Erro 55 -> ", error) 
        }
    } else {
        console.log("Erro ao GRAVAR ÁUDIO -> " + url_file)
    }
}

async function send_video(client, to_whatsapp, url_file, caption, timeWait) {
    if (url_file!="" && url_file!="null" && url_file!="undefined") {
        try {
            await delay(timeWait)   
        } catch (error) {
            console.log("Erro no evento: 'send_video > delay. Erro 41 -> ", error) 
        }
        try {
            await client.sendFile (to_whatsapp, url_file, 'video.mp4', caption) 
        } catch (error) {
            console.log("Erro no evento: 'send_video > delay'. Erro 53 -> ", error) 
        }
    } else {
        console.log("Erro ao enviar VÍDEO -> " + url_file)
    }
}
```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Fiz testes aqui e está funcionando normal.

O erro por você relatado está ocorrendo por causa que o browser está fechado
