### ISSUE TITLE
Erro de Propriedade

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect#389]
No WppConnect Server retorna erro ao chamar essa função por:

```Cannot read property 'isGroup' of undefined```

https://github.com/wppconnect-team/wppconnect/blob/33803b7723f8dc48d3fc3dc1fa90e5a042c5a424/src/lib/wapi/functions/get-group-invite-link.js#L20

**Comment by edgardmessias** [comment]
Não estou mais aceitando issues sem o devido preencimento, POR FAVOR, o texto no issue não está lá a toa, isso facilita o entendimento do problema e quais os passos para resolve-lo.

![image](https://user-images.githubusercontent.com/1530997/127928300-c1ab13ba-73cd-4407-9549-063b51d5e6f3.png)

Partes em vermelho é para mander, partes em azul para preencher corretamente.
