### ISSUE TITLE
Error getGroupInviteLink

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect#394]
## Description
Quando tenta recuperar a URL de Convite do Grupo está retornando erro.

## Environment

- **Wppconnect version(s): 1.8.10**
- **Browser: Chromium**
- **OS: OSX 15.0** [e.g. OSX 10.13.4, Windows 10]
- **Node version: v16.2.0** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. Criar um novo grupo
2. Pegar o ID do Grupo
3. Solicitar Link de Convite do Grupo

## Log Output
WPPConnect Server Erro
```
{
  message: 'Error on get group invite link',
  level: 'error',
  timestamp: '2021-08-04T02:10:41.054Z'
}
```

## Your Code
```
result = await req.client.createGroup(name, contactToArray(participants));
inviteLink = await req.client.getGroupInviteLink(result.gid.user);
```

**Comment by edgardmessias** [comment]
Versão beta ou normal?
