### ISSUE TITLE
Imagem dos contatos

### ISSUE THREAD

**Issue by casantos10** [wppconnect-team/wppconnect#410]
É normal não carregar a imagem de todos os contatos ? No meu caso carrega apenas os 17 primeiros.

**Comment by devpremium** [comment]
Qual função você esta usando?

**Comment by casantos10** [comment]
Uso a getAllChats para pegar só os contatos com conversas. E nela vem a propriedade contact com o profilePicThumbObj de onde eu pego a url da imagem. Mas não vem para todos os contatos, apenas para os 17, no máximo 20 primeiros.

**Comment by edgardmessias** [comment]
Tente utilizar o método getProfilePicFromServer, pois é mais confiável para isso
