### ISSUE TITLE
The first contact number cannot receive the first message

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#422]
The first contact number cannot receive the first message

![image](https://user-images.githubusercontent.com/1323545/129296978-383f8ad1-66b4-4a93-9e65-8287b8bd2e46.png)

log record
![image](https://user-images.githubusercontent.com/1323545/129296984-6518560b-3e60-4f2b-b595-7465c8020984.png)

**Comment by wduandy** [comment]
I'm having the same problem too for new numbers. 
On the webhook call, i got: 

'type': 'unknown', 'subtype': 'fanout'

**Comment by tadeubarbosa** [comment]
Sometimes I receive this same type of response.

**Comment by edgardmessias** [comment]
@Lucipher , could you check if it happens only when the first message is not a text?

**Comment by Lucipher** [comment]
> @Lucipher , could you check if it happens only when the first message is not a text?

it happens on text or image , it should be the first contact issue,   maybe receiver use the whatsapp business version App or the sender setting security option.

**Comment by ghsgabriel** [comment]
Aqui está ocorrendo o mesmo, vou tentar debugar

**Comment by ghsgabriel** [comment]
Tem ocorrido bastante no business multi device, só consegui reproduzir assim.

Esse foi o response:
```
{
  id: 'false_5541....3964@c.us_739EB7....F3141370896',
  type: 'unknown',
  subtype: 'fanout',
  t: 163...4289,
  notifyName: 'Gica - Nutrifica',
  from: '5541...3964@c.us',
  to: '5541....23737@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  recvFresh: true,
  isFromTemplate: false,
  broadcast: false,
  mentionedJidList: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  labels: [],
  productHeaderImageRejected: false,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  chatId: '554...63964@c.us',
  fromMe: false,
  sender: {
    id: '5541....964@c.us',
    name: 'Gica do Nutrifica',
    shortName: 'Gica do Nutrifica',
    type: 'in',
    verifiedName: 'Gica - Nutrifica',
    isBusiness: true,
    isEnterprise: false,
    verifiedLevel: 0,
    privacyMode: null,
    labels: [],
    isContactSyncCompleted: 0,
    formattedName: 'Gica do Nutrifica',
    isMe: false,
    isMyContact: true,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {},
    msgs: null
  },
  timestamp: 16...289,
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
  isPSA: false,
  mediaData: {}
}

```
Mas *parece* que não passa pelo _serializeMessageObj, pois em um console.log que coloquei la dentro, não apareceu nada parecido, todos os logs tinham type e body.

E as que passam por _serializeMessageObj, não são enviadas para o callback em client.onMessage((message) => {}

Por enquanto é isso que tenho.
