### ISSUE TITLE
timeout to connected many times and can not send or receive message

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#448]
timeout to connected many times and can not send or receive message later

![image](https://user-images.githubusercontent.com/1323545/130571956-a65d0f0b-7779-40b1-a931-cf891c0845a7.png)

**Comment by edgardmessias** [comment]
@Lucipher , I think this is not a bug or lib problema, but a "whatsapp server problem" with the connection.

Some times it happens to me
