### ISSUE TITLE
Problema ao encaminar mensagem de video.

### ISSUE THREAD

**Issue by casantos10** [wppconnect-team/wppconnect#449]
Quando faz o encaminhamento de mensagem de vídeo, a mensagem não é encaminhada. O atributo type da mensagem contém o valor 'video' mas o mediaData está assim :

mediaData: {
  type: "unknown",
  mediaStage: "INIT",
  animationDuration: 0,
  animatedAsNewMsg: false,
  isViewOnce: false,
  _swStreamingSupported: false,
  _listeningToSwSupport: false,
  isVcardOverMmsDocument: false,
}

Mensagens de áudio, imagem e texto funcionam perfeitamente.

Estou usando o Node.js e a versão do wppconnect é a 1.8.13

**Comment by edgardmessias** [comment]
Não consegui reproduzir o erro, caso persista, reabrir a issue com mais detalhes.
