### ISSUE TITLE
Add function clearChatsAll

### ISSUE THREAD

**Issue by wenioferraz** [wppconnect-team/wppconnect#459]
Possível criar uma função de deletar todas as mensagens que esteja no celular, não deletando o bate papo, apenas as mensagens internas que existe dentro dos chats

ex:
clearChatsAll()

e se possível também colocar uma timestamp onde um chat que teve uma mensagem após ts (timestamp passado como parâmetro) não será apagado.

clearChatsAll(ts?)

**Comment by edgardmessias** [comment]
Isso não será implementado nesse momento, mas você pode fazer a combinação de pegar todos os chats e um por um chamar a clearChat, assim atendendo sua necessidade.

Sobre as mensagens a partir de determinado tempo, você pode recuperar as mensagens usando o getMessages e fazer a exclusão de uma por uma.
