### ISSUE TITLE
message id build

### ISSUE THREAD

**Issue by jhow2892** [wppconnect-team/wppconnect#578]
Hello everyone, everything good?

great work with this repository ;-)

I'm using to test the sending of messages, and I couldn't generate a token for the message before sending, is this possible?

We currently use go-whatsapp and this allows me to create the message token even before sending it.

Can anyone help me with this?

**Comment by edgardmessias** [comment]
Hey @Lucipher @jhow2892,

I am finishing this in WA-JS, now I need create methods in WPPConnect to use them

To generate a ID: https://wppconnect-team.github.io/wa-js/classes/internal.chat.Chat.html#generateMessageID

For instance: pass a [messageId](https://wppconnect-team.github.io/wa-js/interfaces/internal.chat.SendMessageOptions.html#messageId) in [sendTextMessage](https://wppconnect-team.github.io/wa-js/classes/internal.chat.Chat.html#sendTextMessage)
