### ISSUE TITLE
Funcao getProfilePicFromServer não retorna link da imagem

### ISSUE THREAD

**Issue by daniloricalmeida** [wppconnect-team/wppconnect#580]
## Description

Retorno da chamada do funcao getProfilePicFromServer só retorna null no eurl.

## Environment

- **Wppconnect version(s):** 1.8.14 - 1.9.2
- **Browser:** Chrome ??
- **OS:** linux debian 10
- **Node version:**  Node 12]
- **WhatsApp version:** 2.2138.13
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. chamar o metodo

## Log Output

{
  eurl: null,
  id: {
    server: 'c.us',
    user: '554399625XXXX',
    _serialized: '554399625XXXX@c.us'
  },
  tag: null
}

## Your Code

let response = await client.getProfilePicFromServer(chatId);
console.log(response);

**Comment by edgardmessias** [comment]
Eu fiz vários testes e não consegui reproduzir o mesmo problema.

Me mande o número no meu discord para que eu possa fazer um teste.

Acredito que seja por causa do contato ter bloqueado.
