### ISSUE TITLE
Buttons is not working on beta in some scenarios

### ISSUE THREAD

**Issue by tadeubdev** [wppconnect-team/wppconnect#596]
## Description

I'm trying to send buttons, but it's just doesn't work!
It don't produce an response or an throw... nothing. Just don't work.

For example, locally it's sending the buttons perfectly, but the same code and same input data is not producing any result or error.

## Environment

- **Wppconnect version(s):** v1.9.4
- **Browser:** Chromium 93.0.4577.0 - r901912 (I don't know, I get this version when I was installing the project)
- **OS:** Ubuntu 18.04.6 LTS
- **Node version:** v12.18.3
- **WhatsApp version:** 2.2138.13
- **MultiDevice (BETA):** yes

## Steps to Reproduce

Just trying to run the code above.

## Log Output

There's no output.

## Your Code

```
const buttons = {
  title: 'Title',
  footer: 'Footer',
  isDynamicReplyButtonsMsg: true,
  dynamicReplyButtons: [
    {
		buttonId: '1',
        buttonText: {
          displayText: 'Lorem ipsum',
        },
        type: 1,
	}
  ],
};
await client.sendMessageOptions('55...@c.us', 'Test', buttons).then(...).catch(...)
```

**Comment by lepokoloko** [comment]
its work in beta?

**Comment by edgardmessias** [comment]
@lepokoloko , still the same: buttons not work in beta. The WhatsApp server don't accept that.
