### ISSUE TITLE
deleteMessage só retorna false chat privado

### ISSUE THREAD

**Issue by daniloricalmeida** [wppconnect-team/wppconnect#600]
deleteMessage só exclui mensagens de grupos, em chats privados só retorna false.

- **Wppconnect version(s):** 1.8.11 - 1.9.4
- **Browser:** latest
- **OS:** debian 10
- **Node version:** 12
- **WhatsApp version:** 2.2138.13
- **MultiDevice (BETA):** no

**Comment by edgardmessias** [comment]
Resolvido com 8974e8e1728aa728edaa7e1a85e6840d42ba043c
