### ISSUE TITLE
Aumentar tamanho da Thumbnail na função SendLinkPreview

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#601]
Quando eu envio um LINK pelo CHAT do WhatsApp a THUMBNAIL fica com tamanho grande.

Porém, quando uso a função sendLinkPreview a THUMBNAIL fica pequena. Gostaria que a THUMBNAIL na função ficasse no tamanho grande, fica muito bom pra nós que trabalhamos com disparos em massa, pois não precisariamos anexar uma imagem.

![image](https://user-images.githubusercontent.com/35501007/138568827-f9d254ee-dfab-4185-8229-d33b03b51f3b.png)

**Comment by edgardmessias** [comment]
Eu dei uma olhada e pesquisada aqui, na verdade essa opção de thumbnail maior só ocorre se o link tiver um vídeo para exibir, caso contrário, é tamanho normal.

**Comment by mvac1991** [comment]
> Eu dei uma olhada e pesquisada aqui, na verdade essa opção de thumbnail maior só ocorre se o link tiver um vídeo para exibir, caso contrário, é tamanho normal.

Mas teria como deixar imagens no formato grande também?

**Comment by edgardmessias** [comment]
Como eu falei, isso da imagem grande é para VÍDEO, e não imagem.

Se você mandar o link de um vídeo do youtube por exemplo, ele vai ter esse comportamento.

Não dá para fazer algumas coisas sem quebrar o whatsapp, e esse é uma delas

**Comment by mvac1991** [comment]
Entendi.

Vc disse que somente VÍDEO envia a thumbnail GRANDE.

Porém, no print que enviei, trata-se de uma IMAGEM de um post no INSTAGRAM

https://www.instagram.com/p/CVWXPAZssZv/

Eu fiz um teste enviando pela LIB usando a função sendLinkPreview com VÍDEO e mesmo assim fica pequeno.

**Comment by edgardmessias** [comment]
Certo, vamos por partes.

O print que você me mandou, para mim não serve, pois preciso dos dados da mensagem em si para fazer local.
Peguei o link que você passou, teste com a LIB, usando meu número pessoal, via web, via celular e etc, em NENHUM deles geral essa imagem grande, então a primeira grande questão é: Ter um meio de reproduzir isso, se não vamos ficar discutindo isso e ir para lugar nenhum.

Segundo ponto: você falou que vídeo ficou pequeno, isso é uma coisa que pode ser um problema, mas como mencionei acima, precisamos ter meio de reproduzir, quais links que você testou? Se é beta? Se somente um link está fazendo isso?

Não é querendo ser chato, mas falta muita informação, então me ajude a te ajudar, rsrsrs.
