### ISSUE TITLE
# Bot NLP nos tickets

### ISSUE THREAD

**Issue by paulorodrigues99** [wppconnect-team/wppconnect#628]
**Is your feature request related to a problem? Please describe.**
Não é um problema, é uma intenção de melhoria, quero adicionar scripts as filas de atendimento

**Describe the solution you'd like**
chatbot

**Describe alternatives you've considered**
um fluxo claro de como adicionar scripts aos chats.

**Additional context**
chatbot.

**Comment by paulorodrigues99** [comment]
Cara, ja utilizei a lib com meu processamento de linguagem natural, você pode ver um exemplo aqui.
https://github.com/helton-quintans/yan-bot/blob/main/src/app.ts

O que acontece é que quando faço a conexão do mesmo numero no whaticket
https://github.com/wppconnect-team/whaticket

A sessão do meu bot cai, não to conseguindo realizar múltiplas sessões do Mesmo Numero.

**Comment by ghsgabriel** [comment]
@paulorodrigues99  você está usando múlti device?

Se você está usando o Múlti Device (beta) , eu uso um mesmo número em diferentes instâncias de wppconnect lib sem problemas. Pode ser algo relacionado ao whaticket, então deveria abrir uma issue lá.

Se não está usando Múlti Device (beta), ai é o comportamento padrão do WhatsApp.

De qualquer forma, se achar que é um bug de wppconnect lib, abra uma bug issue, e descreva tudo que pede por favor, para podermos reproduzir o erro.

**Comment by edgardmessias** [comment]
Como não é um recurso a ser implementado diretamente dentro da LIB, estarei fechando esse ticket.

Atualmente no nosso discord há alguns canais específicos para falarem disso.
