### ISSUE TITLE
Group Id not being recognized anymore

### ISSUE THREAD

**Issue by Dropsmart** [wppconnect-team/wppconnect#632]
## Description

The issue happens when calling any group function with GroupId parameter. Such as promoteParticipant;
Seems like group.gid._serialized has changed pattern;
Before: 554888371410-1633091473@g.us
After: 120363022714781102@g.us

Curious about this issue, is that the even with the change, the getGroupInviteLink is working as expected.
```
const groupLink = await waClient.getGroupInviteLink(groupObj.gid._serialized);
```

## Environment

- **Wppconnect version(s):** 1.9.4
- **MultiDevice (BETA):** no

## Steps to Reproduce
```
const groupObj = await waClient.createGroup(group.name, contactsArray);
try {
       console.log('Promoting members');
       for (var i = 0; i < contactsArray.length; i++) {
          waClient.promoteParticipant(groupObj.gid._serialized, contactsArray[i]);
        }
      } catch(err) {
        console.log(err);
      }
```

## Log Output
```
Promoting members
Error: Chat 120363019707056422@g.us is not a group
at /app/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:213984
```

**Comment by edgardmessias** [comment]
@Dropsmart , já identifiquei parte do problema, mas você pode adiantar colocando um delay de dois segundos entre a criação de grupo e as operações do mesmo

**Comment by Dropsmart** [comment]
@edgardmessias O erro persiste em praticamente todas as funções de grupos, menos getGroupInviteLink.
Uso timeout de mais de 2 segundos entre todas as funções de grupos no processo de criação, e mesmo assim, o erro persiste.

Fiz uma pesquisa, porém, foi a primeira vez que abri o código para tentar entender como funciona, cheguei aos insights abaixo.
Pesquisando melhor a mensagem de erro, achei isso aqui:
```
const groupChat = assertGetChat(groupId);
if (!groupChat.isGroup) {
      throw new WPPError(
        'not_a_group',
        `Chat ${groupChat.id._serialized} is not a group`
      );
    }
```
https://github.com/wppconnect-team/wa-js/blob/6bc2260dfecbe434adf308e2261f9c7e05fecade/src/group/Group.ts

Fui pesquisar a função assertGetChat(groupId):
```
export function assertGetChat(id: string | Wid): ChatModel {
  const chat = Chat.get(id);

  if (!chat) {
    throw new InvalidChat(id);
  }

  return chat;
}
```
a função Chat.get(id):
```
get(chatId: string | Wid): ChatModel | undefined {
    const wid = assertWid(chatId);
    return ChatStore.get(wid);
  }
```
Nesse ponto o assertWid faz uma verificação de padrões do id.
```
if (/^\d+$/.test(id)) {
    return WidFactory.createUserWid(id, 'c.us');
  }
  if (/^\d+-\d+$/.test(id)) {
    return WidFactory.createUserWid(id, 'g.us');
  }
  if (/status$/.test(id)) {
    return WidFactory.createUserWid(id, 'broadcast');
  }
  ```
  
  Os novos Ids de grupo porém já não estão mais no padrão: /^\d+-\d+$/.test(id).
  
  Me questionei então, pq o método invite link continua funcionando.
  Não achei nenhuma pista concreta, a não ser essa, a função de invite é a única na qual não faz um throw de erro na validação de chat.isGroup.
  
  ```
  var chat = Store.Chat.get(chatId);
  if (!chat) {
    throw {
      error: true,
      code: 'group_not_found',
      message: 'Group not found',
    };
  }
  if (!chat.isGroup) {
    return '';
  }
  let inviteCode = '';
  ```
  
  Nada disso é concreto, mas o fato é que para grupos novos, os quais possuem o id em um padrão diferente, nada mais funciona. Os grupos antigos funcionam sem problema.

**Comment by Dropsmart** [comment]
Só uma referência, do que fizeram na Baileys
https://github.com/adiwajshing/Baileys/pull/804

**Comment by edgardmessias** [comment]
@Dropsmart , eu olhei tudo aqui, está todo fluxo certinho.

Como mencionei acima, tente colocar. Intervalo de tempo entre cada operação, para dar tempo da interface atualizar e entender o comando.
