### ISSUE TITLE
ERRO AO ENVIAR MENSAGEM COM BOTÃO NO PRIMEIRO CHAT 

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#633]
## Description

[Erro ao enviar sendMessageWithOptions (mensagens com botão) para números que ainda não possuem chat (ou seja, pessoas que nunca conversamos).]

## Environment

- **Wppconnect version(s):** [e.g. 1.9.2]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, LInux Centos 6]
- **Node version:** [e.g. Node 7.6.0]
- **WhatsApp version:** [e.g. 2.2138.14]
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. [sendMessageWithOptions]

## Log Output
 Erro no evento: 'send_1button > client.sendMessageOptions'. Erro ->  TypeError: Cannot read properties of undefined (reading 'id')
0|App  |     at Object.<anonymous> (/home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:46698)
0|App  |     at Generator.next (<anonymous>)
0|App  |     at gt (/home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:44889)
0|App  |     at a (/home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:45093)
0|App  |     at /home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:45154
0|App  |     at j (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:379576)
0|App  |     at new g (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:370471)
0|App  |     at Object.<anonymous> (/home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:45033)
0|App  |     at Object.window.WAPI.window.WAPI.sendMessageOptions (/home/zapmutacao/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:103174
```
If relevant, paste all of your Log Output
```

## Your Code
async function send_1button(client, to_whatsapp, content, timeWait) {

    const body = content[0].body;
    const title = content[0].title;
    const footer = content[0].footer;
    const id1 = content[0].id;
    const btn1 = content[0].btn1;

    try {
        await delay(timeWait)   
    } catch (error) {
        console.log("Erro no evento: 'send_1button > delay'. Erro -> ", error) 
    }
    try {
        await client.sendMessageOptions(to_whatsapp, body, {
            title: title,
            footer: footer,
            isDynamicReplyButtonsMsg: true,
            dynamicReplyButtons: [
                {
                    "buttonId": id1,
                    "buttonText": {
                        "displayText": btn1
                    },
                    "type": 1
                }
            ],
        })
    } catch (error) {
        console.log("Erro no evento: 'send_1button > client.sendMessageOptions'. Erro -> ", error) 
    }

}
```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/35501007/140825373-72bcc95f-a596-443f-bd70-d0fdbf5e9fd5.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lepokoloko** [comment]
alguem tem um exemplo que como consigo enviar os botoes de forma dinamica, vindo de um arquivo externo ou um banco de dados, ou seja, em alguns casos, podem haver 2 botoes, 3 botoes, 4botoes etc...

**Comment by edgardmessias** [comment]
@lepokoloko , primeiro não fique postando a mesma pergunta em cada issue que você achar no projeto, ou eu irei te bloquear.

Segundo: Sobre a sua pergunta, é javascript básico, então dê uma pesquisada sobre arrays e objetos em javascript, você pode usar variáveis e depois mandar

**Comment by lepokoloko** [comment]
desculpe, sou novo no github :)

**Comment by lepokoloko** [comment]
eu novamente aqui, o type no botao, se refere a que?
type : 1

{
         "buttonId":"idSim",
         "buttonText":{
            "displayText":"SIM"
         },
         "type":1
      }
