### ISSUE TITLE
ERRO NO SENDREPLY QUANDO A PESSOA CLICA EM UM BOTÃO DO SENDMESSAGEWITHOPTIONS

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#634]
## Description

[Quando eu envio uma mensagem de texto com botão usando sendMessageWithOptions e o contato CLICA, eu não consigo pegar o ID DA MENSAGEM, consecutivamente o sendReply não funciona]

## Environment

- **Wppconnect version(s):** [e.g. 1.9.2]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, LInux Centos 6]
- **Node version:** [e.g. Node 7.6.0]
- **WhatsApp version:** [e.g. 2.2138.14]
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. [Enviar uma mensagem com botão do WhatsApp 1 para o WhatsApp 2]
2. [Clicar no botão usando o WhatsApp 2]
3. [No onMessage, ao receber a mensagem do WhatsApp 2 com o TEXTO DO BOTÃO, chamar a função SENDREPLIE]

## Log Output
Não retorna nenhum log, simplesmente não envia
```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Fiz mais uns testes aqui, e infelizmente não tem nada que possamos fazer.

O que ocorre é que o próprio WhatsApp não implementou a opção de marcar mensagens de resposta de botões.
Isso é semelhante a enviar botões com business ou beta.

**Comment by lepokoloko** [comment]
alguem tem um exemplo que como consigo enviar os botoes de forma dinamica, vindo de um arquivo externo ou um banco de dados, ou seja, em alguns casos, podem haver 2 botoes, 3 botoes, 4botoes etc...
