### ISSUE TITLE
ÁUDIOS USANDO SENDPTT NÃO REPRODUZEM NO 2X PELO ANDROID

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#635]
## Description

ESTOU USANDO A LIB PARA ENVIAR ÁUDIO.

Quando eu envio um áudio usando a função CLIENT.SENDPTT, o RECEBEDOR não consegue reproduzir o ÁUDIO na velocidade 2X usando ANDROID ou IPHONE, ele só consegue reproduzir no WHATSAPP WEB.

## Environment

- **Wppconnect version(s):** [e.g. 1.9.2]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, LInux Centos 6]
- **Node version:** [e.g. Node 7.6.0]
- **WhatsApp version:** [e.g. 2.2138.14]
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Enviar áudio OGG ou MP3 usando a função client.sendPtt

## Log Output
Não retorna nenhum log de erro
```

## Your Code
async function record_audio(client, to_whatsapp, url_file, timeWait) {
    if (url_file!="" && url_file!="null" && url_file!="undefined") {
        try {
            await delay(timeWait)   
        } catch (error) {
            console.log("Erro no evento: 'record_audio > delay. Erro 43 -> ", error) 
        }
        try {
            await client.sendPtt (to_whatsapp, url_file, 'audio.ogg')    
        } catch (error) {
            console.log("Erro no evento: 'record_audio > client.sendPtt'. Erro 55 -> ", error) 
        }
    } else {
        console.log("Erro ao GRAVAR ÁUDIO -> " + url_file)
    }
}

**Comment by ghsgabriel** [comment]
@mvac1991 você está enviando via celular ou via lib? Se via lib, informe os detalhes solicitados na abertura da issue.

**Comment by mvac1991** [comment]
> @mvac1991 você está enviando via celular ou via lib? Se via lib, informe os detalhes solicitados na abertura da issue.

Atualizei as informações

**Comment by edgardmessias** [comment]
Eu tenho visto que isso não foi um problema da lib em si, mas alguma coisa dos aplicativos do whatsapp.

Caso o problema persista e esteja funcionamento corretamente em versões anteriores, reabrir essa issue

**Comment by lepokoloko** [comment]
Normalizou ai ? Pois aqui nao deixa reproduzir em 2x, estou enviando arquivo em .mp3

**Comment by edgardmessias** [comment]
@lepokoloko @mvac1991  , isso está ocorrendo se enviar áudio normal pelo celular? E envio normal pela WEB?

Poderia postar o resultado do comando: `ffprobe -i <arquivo>` para ter certeza que é MP3?

**Comment by lepokoloko** [comment]
Envio com php, ja convertido  porem estava usando versao beta

**Comment by lepokoloko** [comment]
Testei com versao sem ser beta, mesmo assim nao reproduz em 2x

**Comment by edgardmessias** [comment]
@lepokoloko , e o resultado do `ffprobe -i <arquivo>`?
90% das vezes que vejo alguém reclamando do tipo de arquivo que não envia corretamente ou só funciona em algum lugar é por que está "convertendo" falsamente. Muitas vezes já vi ser áudio do tipo WEBM, mas com extensão MP3, então não é MP3 de verdade, e muitos celulares não reproduzem WEBM

**Comment by lepokoloko** [comment]
Vou analisar isso ai, agradeco retorno
