### ISSUE TITLE
BETA, Método /logout não remove o diretório de sessão em /tokens/sessão

### ISSUE THREAD

**Issue by alanvictorjp** [wppconnect-team/wppconnect#648]
## Description
1. No BETA, quando removemos uma sessão, seja pelo aparelho ou seja pelo método /logout, o diretório com nome da sessão continua em /tokens/sessao_dir/, acredito que o correto seria a lib remover automaticamente como é no caso do whatsapp NÃO BETA com arquivos /tokens/sessao.data.json

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect version(s):** [1.10.1]
- **Browser:** [chromium]
- **OS:** [debian 10]
- **Node version:** [16.13.0]
- **WhatsApp version:** [2.2144.10]
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Na verdade isso não chega a ser um BUG, pois a pasta pertence ao Chrome e não a LIB, então pode acontecer de ter o chrome aberto e não estar conectado, mas mesmo assim a pasta precisa existir.
