### ISSUE TITLE
Basic example not work

### ISSUE THREAD

**Issue by IanosJunior** [wppconnect-team/wppconnect#658]
## Description

Basic example not work

## Environment

- **Wppconnect version(s):** [1.10.2]
- **Browser:** [Chrome 95]
- **OS:** [Windows 10]
- **Node version:** [Node 16.13]
- **WhatsApp version:** [2.2144.10]
- **MultiDevice (BETA):** no

## Steps to Reproduce

Run basic example

## Log Output

Error when sending:  TypeError: Store.MsgKey is not a constructor
    at Object.window.WAPI.window.WAPI.getNewMessageId (<anonymous>:1:101588)
    at Object.<anonymous> (<anonymous>:1:42629)
    at Generator.next (<anonymous>)
    at ct (<anonymous>:1:42234)
    at a (<anonymous>:1:42438)
    at V (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:390373)
    at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:389952)

## Your Code

const wppconnect = require('@wppconnect-team/wppconnect');

wppconnect
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

  function start(client) {
    client.onMessage((message) => {
      if (message.body === 'Hello') {
        client
          .sendText(message.from, 'Hello, how I may help you?')
          .then((result) => {
            console.log('Result: ', result); //return object success
          })
          .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
          });
      }
    });
  }

**Comment by ghsgabriel** [comment]
Hi @IanosJunior,

I just tested it and couldn't reproduce the error.

I followed exactly the same environment and its basic code.
I also tested it with Multi Device, in addition to "normal/legacy"

Anyone else with the same problem?

**Comment by IanosJunior** [comment]
Olá @ghsgabriel ,
não fiz nada de mais.
Estou na última versão do Node e era pra ser só uma coisa simples.
Pela mensagem de erro não dá pra imaginar onde posso ser?

**Comment by ghsgabriel** [comment]
Oi @IanosJunior , segundo o mestre Edgard: 
- "Parece ser problema de internet, na qual não carregou todos os módulos, daí da esse tipo de problema"

**Comment by ghsgabriel** [comment]
Normalmente esse erro é devido a problemas de conexão com a internet, mas parece que está ocorrendo com mais frequência nas últimas verões.

Informações que tenho até agora:
- Acontece apenas quando o client. create é chamado com await.
- Até a versão 1.10.0 funcionava mesmo com await.
- Nas últimas versões o await acarreta no erro apresentado, mas se removido o await tudo funciona normal.

Recebi o código para tentar reproduzir:
`const startChatBot = async (bot_uuid) => {
    try {
        const client = await wppconnect.create({
        session: bot_uuid,
        tokenStore: myTokenStore,`

Mas ainda não testei
