### ISSUE TITLE
Add função "sendTextCommentInStatusReceived"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#674]
A função "sendMessageInStatusReceived" envia mensagem de TEXTO para o STATUS.

**Comment by mvac1991** [comment]
Atualizei o nome da função incluindo o Comment.

Ou seja, o que envia é um COMENTÁRIO no status recebido

**Comment by mvac1991** [comment]
Centralizei nessa ISSUE https://github.com/wppconnect-team/wppconnect/issues/809

**Comment by edgardmessias** [comment]
Blz, vou estar fechando e referenciando as issues, para concentrar  todas em apenas uma.
