### ISSUE TITLE
Add função "sendPttCommentInStatusReceived"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#675]
A função "sendPttInStatusReceived" envia mensagem de ÁUDIO para o STATUS.

**Comment by edgardmessias** [comment]
@mvac1991, poderia descrever melhor esse recurso? Eu particularmente nunca ví alguém enviando PTT no status

**Comment by mvac1991** [comment]
Acho que o nome da função que melhor seria "sendPttCommentInStatusReceived"

Envia um comentário de áudio ptt no status que alguma pessoa postou.

**Comment by mvac1991** [comment]
Atualizei o nome da função incluindo o Comment.

Ou seja, o que envia é um COMENTÁRIO no status recebido

**Comment by mvac1991** [comment]
Centralizei nessa ISSUE https://github.com/wppconnect-team/wppconnect/issues/809

**Comment by edgardmessias** [comment]
Blz, vou estar fechando e referenciando as issues, para concentrar  todas em apenas uma.
