### ISSUE TITLE
Add função "sendStickerCommentInStatusReceived"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#676]
A função "sendStickerInStatusReceived" envia mensagem de STICKER para o STATUS.

**Comment by edgardmessias** [comment]
Acredito que não seja possível enviar no status além de texto, imagem e vídeo.

**Comment by mvac1991** [comment]
Acho que o nome da função que melhor seria "sendStickerCommentInStatusReceived"

Envia um comentário de STICKER no status que alguma pessoa postou.

**Comment by mvac1991** [comment]
Atualizei o nome da função incluindo o Comment.

Ou seja, o que envia é um COMENTÁRIO no status recebido

**Comment by edgardmessias** [comment]
Certo, então seria melhor concentrar tudo isso em apenas um TICKET, e renomea-lo para "Enviar mensagem de resposta de Status".

Tickets: #674, #675 e #676

**Comment by mvac1991** [comment]
> Certo, então seria melhor concentrar tudo isso em apenas um TICKET, e renomea-lo para "Enviar mensagem de resposta de Status".
> 
> Tickets: #674, #675 e #676

Centralizei nessa ISSUE https://github.com/wppconnect-team/wppconnect/issues/809

**Comment by edgardmessias** [comment]
Blz, vou estar fechando e referenciando as issues, para concentrar  todas em apenas uma.
