### ISSUE TITLE
Adicionar um evento StatusChat

### ISSUE THREAD

**Issue by IanosJunior** [wppconnect-team/wppconnect#682]
Tenho uma sugestão para adicionar um evento que será disparado quando um contato estiver digitando ou gravando um audio.
Assim podemos saber que ele está interagindo na conversa.

**Comment by edgardmessias** [comment]
Isso foi implementado algumas versões atrás.

Você pode utilizar o `onPresenceChanged`, que vai ter um atributo `state` com o estado atual de cada contato

https://wppconnect-team.github.io/wppconnect/classes/Whatsapp.html#onPresenceChanged
