### ISSUE TITLE
Error: Unexpected extraInfo events for request 718506.7

### ISSUE THREAD

**Issue by Lucipher** [wppconnect-team/wppconnect#694]
Error: Unexpected extraInfo events for request 718506.7
3|demo  | 2021-11-29 14:35:45:     at NetworkManager._emitResponseEvent (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:346:19)
3|demo  | 2021-11-29 14:35:45:     at NetworkManager._onResponseReceived (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:369:14)
3|demo  | 2021-11-29 14:35:45:     at /srv/wa/demo/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
3|demo  | 2021-11-29 14:35:45:     at Array.map (<anonymous>)
3|demo  | 2021-11-29 14:35:45:     at Object.emit (/srv/wa/demo/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
3|demo  | 2021-11-29 14:35:45:     at CDPSession.emit (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
3|demo  | 2021-11-29 14:35:45:     at CDPSession._onMessage (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:245:18)
3|demo  | 2021-11-29 14:35:45:     at Connection._onMessage (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:117:25)
3|demo  | 2021-11-29 14:35:45:     at WebSocket.<anonymous> (/srv/wa/demo/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
3|demo  | 2021-11-29 14:35:45:     at WebSocket.onMessage (/srv/wa/demo/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:

**Comment by edgardmessias** [comment]
@Lucipher , could you provide all required data before only pasting the error log?

**Comment by edgardmessias** [comment]
This is not a bug os WPPConnect, but the it is a puppeteer bug: See https://github.com/puppeteer/puppeteer/issues/7805

The temporary solution: downgrade puppetteer to v11

**Comment by Lucipher** [comment]
> This is not a bug os WPPConnect, but the it is a puppeteer bug: See [puppeteer/puppeteer#7805](https://github.com/puppeteer/puppeteer/issues/7805)
> 
> The temporary solution: downgrade puppetteer to v11

Well noted with thanks!
