### ISSUE TITLE
"setProfileName" não funciona

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#701]
## Description

Ao executar o trecho **"await client.setProfileName('Nome teste');"** o mesmo não retorna erro e também não altera o NOME no usuário conectado.

## Environment

- **Wppconnect version(s):** [1.10.3]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO

**Comment by edgardmessias** [comment]
@mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

**Comment by mvac1991** [comment]
> @mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

![image](https://user-images.githubusercontent.com/35501007/144526691-ad554f5f-b6a2-44a7-9f23-aa359cb124c2.png)

**Comment by edgardmessias** [comment]
@mvac1991, tem certeza? Essa versão do WPPConnect não existe, segundo que a versão do Chromium é muito antigo

**Comment by mvac1991** [comment]
> @mvac1991, tem certeza? Essa versão do WPPConnect não existe, segundo que a versão do Chromium é muito antigo e terceiro que `e.g` significa `por exemplo:`

Atualizei

**Comment by edgardmessias** [comment]
Obrigado, estou já verificando e testando conforme o ambiente que você reportou

**Comment by edgardmessias** [comment]
@mvac1991 , fiz vários testes aqui e está funcionando normalmente.

Espere a nova versão e faça testes novamente, caso persista o problema, reabra e tente prover mais detalhes.
