### ISSUE TITLE
"sendMentioned" não funciona

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#702]
## Description

Ao executar o trecho **"await client.sendMentioned(GROUP_ID, 'teste mencionando...', CONTACT_ID);"** não aparece para o destinatário o '@' (arroba), como sendo mencionado em um grupo. No log também não retornou nenhum erro.

## Environment

- **Wppconnect version(s):** [1.10.3]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO

**Comment by edgardmessias** [comment]
@mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

**Comment by mvac1991** [comment]
> @mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

![image](https://user-images.githubusercontent.com/35501007/144526740-f0f7aaa6-390b-42d2-9917-999a931db9ce.png)

**Comment by mvac1991** [comment]
> @mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

Atualizei

**Comment by edgardmessias** [comment]
@mvac1991 , conforme o código que você postou, você está fazendo a chamada dela de jeito ERRADO.

O primeiro ponto é que no texto você DEVE colocar o @<numero>, sem o final `@c.us`
O segundo ponto é que o terceiro argumento é um ARRAY e não uma STRING

**Comment by mvac1991** [comment]
> @mvac1991 , conforme o código que você postou, você está fazendo a chamada dela de jeito ERRADO.
> 
> O primeiro ponto é que no texto você DEVE colocar o @, sem o final `@c.us` O segundo ponto é que o terceiro argumento é um ARRAY e não uma STRING

Entendi, então realmente estou fazendo errado. Poderia postar um exemplo de chamada com os argumentos corretos?

**Comment by edgardmessias** [comment]
```
client.sendMentioned('<number>@c.us', 'Ola @123456, tudo bem?', ['123456@c.us'])
```

**Comment by mvac1991** [comment]
> ```js
> client.sendMentioned('<number>@c.us', 'Ola @123456, tudo bem?', ['123456@c.us'])
> ```

Me lembro que outro dia no grupo vc fez um teste mencionando todo mundo sem colocar o @ no texto da mensagem. Como ficaria os parâmetros nesse caso?

**Comment by edgardmessias** [comment]
Agora a função está com o WA-JS, então basta colocar no terceiro argumento apenas
