### ISSUE TITLE
"sendMessageWithThumb" não funciona

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#703]
## Description

Ao executar o trecho **"await client.sendMessageWithThumb('https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Creative-Tail-rocket.svg/768px-Creative-Tail-rocket.svg.png', 'https://www.instagram.com/p/CVWXPAZssZv/', 'testando title', 'description here...', CONTACT_ID);"** o mesmo não retorna erro e também não envia nenhuma mensagem, nada acontece.

## Environment

- **Wppconnect version(s):** [1.10.3]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO

**Comment by edgardmessias** [comment]
@mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

**Comment by mvac1991** [comment]
> @mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

![image](https://user-images.githubusercontent.com/35501007/144526750-c0fdd786-6b5c-455e-ad1e-d99419b6def0.png)

**Comment by mvac1991** [comment]
> @mvac1991 , poderia por gentileza atualizar o ticket e colocar as informações corretas do ambiente utilizado?

Atualizei

**Comment by edgardmessias** [comment]
@mvac1991 , para essa issue, a função `sendMessageWithThumb` esperava um base64 no primeiro argumento, que é a thumb.

Atualizei o código para aceitar URLs também.
