### ISSUE TITLE
Erro ao enviar mensagem com link preview utilizando a function sendLinkPreview() utilizando multi-device

### ISSUE THREAD

**Issue by murilomontalvao** [wppconnect-team/wppconnect#707]
## Description

Fiz o teste utilizando uma instância com wpp padrão (não utilizando multi-device) e deu certo.
Se tento utilizando a versão beta (multi-device) passando os mesmos parâmetros, é retornado um erro. 
O problema acontece com envio para grupos e para um único número.

## Environment

- **Wppconnect version(s):** 1.10.3
- **Browser:** Google Chrome 93.0.4577.63
- **OS:** Ubuntu 20.04
- **Node version:** v12.22.7
- **WhatsApp version:** 2.2144.11
- **MultiDevice (BETA):** yes

## Log Output
{
level: 'error',
  message: 'Unexpected null or undefined: BUNDLE',
  stack: 'Error: Unexpected null or undefined: BUNDLE\n' +
    '    at t.default (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:57:351914)\n' +
    '    at Object.t.get (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:57:380796)\n' +
    '    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.d600dc4f1c8c09c11723.js:5:6883)\n' +
    '    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.d600dc4f1c8c09c11723.js:2:96246)\n' +
    '    at t.default.write (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:2:394791)\n' +
    '    at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.d600dc4f1c8c09c11723.js:2:81433)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.fac97d8af22734ef1183.js:2:63784)\n' +
    '    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.fac97d8af22734ef1183.js:2:63995)\n' +
    '    at https://web.whatsapp.com/vendor1~bootstrap_qr.fac97d8af22734ef1183.js:2:64054',
  timestamp: '2021-12-02T02:09:10.806Z'
}

![log-wpp](https://user-images.githubusercontent.com/3306327/144411134-35ad6449-9800-414b-91ff-ad90eabbd959.png)

**Comment by edgardmessias** [comment]
Olhando a página FAQ do WhatsApp, o beta não possui suporte a preview de links.

Como alternativa, vou desativar o preview caso for beta
