### ISSUE TITLE
Não envia mais que 3 botoes 

### ISSUE THREAD

**Issue by lepokoloko** [wppconnect-team/wppconnect#708]
Ao tentar enviar 4 botoes, ele envia até o terceiro somente

"buttons":[
     
	 {
         "buttonId":"id1",
         "buttonText":{
            "displayText":"text 1"
         },
         "type":1
      },
      {
         "buttonId":"id2",
         "buttonText":{
            "displayText":"texto 2"
         },
         "type":1
      },
      {
         "buttonId":"id3",
         "buttonText":{
            "displayText":"texto 3."
         },
         "type":1
      },
      {
         "buttonId":"id4",
         "buttonText":{
            "displayText":"texto 4"
         },
         "type":1
      }
      
   ]
}',

faco o tratamento quando recebo o post 

e envio assim

const botao = buttons;
	
	console.log(botao);
	
	try {
		
		
		
		var resultsendMessageOptions = await session.client.then(async (client) => {
    return await client.sendMessageOptions(number + '@c.us', 'Estou aqui para te ajudar', {
          title: 'Titulo',
          footer: 'Escolha uma opção abaixo',
          isDynamicReplyButtonsMsg: true,
          dynamicReplyButtons: botao
        });
      
	  
	  });

E ele envia somente até o terceiro botão, isso é uma limitação? ou estou fazendo algo errado..

obrigado

**Comment by edgardmessias** [comment]
Isso é restrição do WhatsApp e não um problema. infelizmente não tem nada o que fazer.
