### ISSUE TITLE
Número Banido

### ISSUE THREAD

**Issue by loja5combr** [wppconnect-team/wppconnect#715]
Bom dia a todos, alguém que usa o projeto já teve o número banido? Usava já algum tempo para avisos de cobrança mas ontem meu número foi BAN, por sorte usei um número apenas para fins do Bot.

**Comment by devpremium** [comment]
Sim acontece, dependendo das suas açoes você pode tomar ban e isso não tem aver com o wppconnect

**Comment by Aramunii** [comment]
levei um ban hoje cedo, mas mandei mensagem e já desbaniram, isso tem a ver provavelmente com o que você anda mandando eu acho... vou verificar e validar mais

**Comment by loja5combr** [comment]
Pois é, o estranho é que nem solicitei o desbloqueio e agora a tarde o número já ativou normalmente (já ia ativar um número virtual), no caso envio apenas mensagens prontas, cerca de 20 a 30 diariamente, na mesma é um texto com o link de boleto.

**Comment by iamedusm** [comment]
> levei um ban hoje cedo, mas mandei mensagem e já desbaniram, isso tem a ver provavelmente com o que você anda mandando eu acho... vou verificar e validar mais

poderia falar o que vc informar na mensagem para conseguir ser desbanido ?

**Comment by AlanMartines** [comment]
Está sendo comum o banimento em criação de grupos quando o nome ultrapassa tamanho máximo de caracteres permitidos...
