### ISSUE TITLE
Send Sticker

### ISSUE THREAD

**Issue by Aramunii** [wppconnect-team/wppconnect#716]
I need send sticker, but always i get 
![image](https://user-images.githubusercontent.com/39601135/145055019-941b7977-d842-4e92-86d1-a8e8420bde03.png)

can someone help me ?

**Comment by guilhermelirio** [comment]
Same here!!

**Comment by edgardmessias** [comment]
@Aramunii @guilhermelirio , could you provide more information about that? A example of code? Example of sticker?

And please: fill this form:

- **WPPConnect version(s):** X.Y.Z
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **Node version:** Node XY
- **WhatsApp version:** X.YYYY.ZZ
- **MultiDevice (BETA):** yes/no
