### ISSUE TITLE
Função downloadMedia não funciona na versão 2.2147.14 do wpp

### ISSUE THREAD

**Issue by devpremium** [wppconnect-team/wppconnect#723]
Função downloadMedia não funciona (retorna um obj vazio) na versão 2.2147.14 porem na versão 2.2144.11 funciona normalmente

- **Wppconnect version(s):** 1.11.1
- **Browser:** Chrome 87
- **OS:** Debian 10
- **Node version:** Node 16
- **WhatsApp version:** 2.2147.14
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Resolvido na última versão
