### ISSUE TITLE
Função decryptFile não funciona com objeto Message no retorno de getAllUnreadMessages

### ISSUE THREAD

**Issue by daniloricalmeida** [wppconnect-team/wppconnect#724]
Ao chamar o metodo decryptFile e passar o objeto Message do retorno do metodo getAllUnreadMessages o wpp crasha a aplicação.
Obs: o payload do objeto Message vem diferente na chamada de getAllUnreadMessages

Ex:
{
  id: 'false_55439625xxxx@c.us_BE73A5D9ABBED577092131C5B883FCA8',
  from: '55439625xxxx@c.us',
  chatId: {
    server: 'c.us',
    user: '55439625xxxx',
    _serialized: '55439625xxxx@c.us'
  },
  to: '55433046xxxx@c.us',
  fromMe: false,
  sender: {
    id: {
      server: 'c.us',
      user: '55439625xxxx',
      _serialized: '55439625xxxx@c.us'
    },
    name: 'Meu Número',
    shortName: 'Meu Número',
    pushname: 'Danilo Almeida',
    type: 'in',
    isBusiness: false,
    isEnterprise: false,
    statusMute: false,
    labels: [],
    disappearingModeDuration: 0,
    disappearingModeSettingTimestamp: 0,
    formattedName: 'Meu Número',
    isMe: false,
    isMyContact: true,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {
      eurl: 'https://pps.whatsapp.net/v/t61.24694-24/95089372_367104007734858_8359602808d3&oe=61B8901D',
      id: [Object],
      img: 'https://web.whatsapp.com/pp?t=s&u=554396254359%40c.us&i=1605048215&n=BIgGSTnhcgZ5ftw58Ws5FFfrQs%3D',
      imgFull: 'https://web.whatsapp.com/pp?t=l&u=554396254359%40c.us&i=1605048215&n=BIgs5FFfrQs%3D',
      raw: null,
      tag: '1605048215'
    },
    msgs: null
  },
  timestamp: 1639157360,
  content: '...',
  type: 'image',
  mediaData: {
    type: 'image',
    mediaStage: 'INIT',
    size: 50970,
    filehash: 'WrMZ9tAmwYInY/PpEc2D/PPgyuBGp/OAowjps=',
    mimetype: 'image/jpeg',
    mediaBlob: null,
    fullHeight: 1044,
    fullWidth: 1054,
    aspectRatio: 1.0095785440613028,
    animationDuration: 0,
    animatedAsNewMsg: false,
    isViewOnce: false,
    staticUrl: '',
    preview: {
      _retainCount: 1,
      _inAutoreleasePool: false,
      released: false,
      _b64: '....',
      _mimetype: 'image/jpeg'
    },
    _swStreamingSupported: false,
    _listeningToSwSupport: false,
    isVcardOverMmsDocument: false
  }
}

- **Wppconnect version(s):** 1.11.1
- **Browser:** Chrome 96
- **OS:** debian 10
- **Node version:** Node 12
- **WhatsApp version:** 2.2144.11
- **MultiDevice (BETA):** no

## Log Output
UnhandledRejection: message is missing critical data needed to download the file.
    at Whatsapp.<anonymous> (/Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:344:35)
    at step (/Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:64:23)
    at Object.next (/Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:45:53)
    at /Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:39:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:35:12)
    at Whatsapp.decryptFile (/Users/daniloalmeida/www/api-venom-docker/node_modules/@wppconnect-team/wppconnect/dist/api/whatsapp.js:336:16)
    at Function.getMsgsUnread (/Users/daniloalmeida/www/api-venom-docker/modules/queues/services.js:41:64)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

## Your Code

let buffer = await client.decryptFile(message);

**Comment by edgardmessias** [comment]
@daniloricalmeida , faça um teste com o downloadMedia, passando apenas o ID da mensagem

**Comment by daniloricalmeida** [comment]
@edgardmessias, passei a usar esse metodo após identificar a falha no decryptFile. O Erro eu creio ser no objeto de retorno da mensagem no getAllUnreadMessages, nele nao vem todas as propriedades que vem no objeto que chega pelo onMessage.
