### ISSUE TITLE
Check number status esta retornando que o numero existe com o 9 digito.

### ISSUE THREAD

**Issue by lepokoloko** [wppconnect-team/wppconnect#725]
o telefone que tem whatsapp não possui o nono digito, porem o checknumberstatus esta retornando que o numero existe, estou usando a ultima versao.

{
0|index  |   id: {
0|index  |     server: 'c.us',
0|index  |     user: '557198633XXXX',
0|index  |     _serialized: '557198633XXXX@c.us'
0|index  |   },
0|index  |   isBusiness: false,
0|index  |   canReceiveMessage: true,
0|index  |   numberExists: true,
0|index  |   status: 200,
0|index  |   number: '557198633XXXX'
0|index  | }

porem o mesmo possui o whats sem o nono digito

**Comment by iamedusm** [comment]
Estou com o mesmo problema aqui, começou tem ums 3 dias.

**Comment by lepokoloko** [comment]
Voltei pra versao 

1.9.4 (2021-10-21) e resolveu esse bug, se alguem conseguir testar isso

**Comment by lepokoloko** [comment]
Me enganei, o problema continua, mesmo com essa versao, oque sera que pode ser, pessoal que tem mais experiencia, e conseguir debugar isso pra descobrir oque mudou

**Comment by Viittin1997** [comment]
Galera, em relação ao erro de 9 digito, cheguei a algumas conclusões:
Até a versão v1.9.4 funciona normal com 9 digito, qualquer número, exemplo: 55DD912345678@c.us
Após essa versão, fiz alguns testes, e envia pra um número que "não existe", alguns testes.

E também que, se o DDD for menor que 30 tem de colocar o 9 Dígito, e quando for maior, não precisa.

**Comment by edgardmessias** [comment]
Na próxima versão do WA-JS isso vai estar resolvido
