### ISSUE TITLE
getAllUnreadMessages retornando mensagens lidas.

### ISSUE THREAD

**Issue by alanvictorjp** [wppconnect-team/wppconnect#726]
## Description

getAllunreadMessages, bugando com whatsapp app.

Alguns dias atrás, se fosse enviado uma mensagem via lib para o contato X, se existisse mensagens não lidas no whatsapp app, se transformava em lida, pelo fato de ter chegado uma nova mensagem, mas agora não... se for enviado uma mensagem via lib para contato X, se contato X ainda não abriu a conversa no whatsapp app, tudo que for enviado pela lib continuará não lida.

Acontece tanto no BETA/MD como no whatsapp normal.

Sendo assim, bugando o método getAllUnreadMessages.

## Environment
- **Wppconnect version(s):** 1.11.1
- **Browser:** Chromium
- **OS:** debian 10
- **Node version:** 16.13.0
- **WhatsApp version:** 2.2144.11
- **MultiDevice (BETA):** yes / no

**Comment by alanvictorjp** [comment]
atualizei as informações do problema

**Comment by edgardmessias** [comment]
@alanvictorjp , tentei entender o que você reportou, fiz uns testes, e não encontrei problemas.

Caso puder, faça testes com a versão mais atualizada e reabra esse ticket com mais detalhes e como reproduzir.

**Comment by edgardmessias** [comment]
@alanvictorjp , tentei entender o que você reportou, fiz uns testes, e não encontrei problemas.

Caso puder, faça testes com a versão mais atualizada e reabra esse ticket com mais detalhes e como reproduzir.
