### ISSUE TITLE
Add "Botão Ligue Agora" e "Botão Acessar Link Externo"

### ISSUE THREAD

**Issue by suh1989** [wppconnect-team/wppconnect#730]
Eu gostaria que tivesse os **2 BOTÕES**:

**#1 - Ligar agora**, onde a pessoa clica e abre o aplicativo de chamadas do celular, já com o número configurado.

**#2 - Acessar Link**, onde a pessoa clica e é redirecionada para um link fora do WhatsApp.

![image](https://user-images.githubusercontent.com/96077194/145863516-6d02048a-b4a6-430c-b0ac-7b03beda22f6.png)

**Comment by edgardmessias** [comment]
Atualmente não existe nenhum código dentro do WhatsApp WEB para enviar esse tipo de mensagem, mas existe no protocolo (protobuf).

Para implementar esse recurso, será necessário "criar" o recurso de envio desses botões primeiro, para aí em seguida, permitir esse tipo de envio.

**Comment by edgardmessias** [comment]
Resolvido em algumas versões atrás do WPPConnect
