### ISSUE TITLE
ERRO:  Chat not found for

### ISSUE THREAD

**Issue by JandersonFB** [wppconnect-team/wppconnect#751]
Alguém mais com esse erro ?

![image](https://user-images.githubusercontent.com/11274709/147036939-3edd8635-48de-4a4b-8a1c-61ab9933017a.png)

**Comment by edgardmessias** [comment]
Chat não encontrado, em algum momento do seu script está fazendo ação para um chat não existente.

Caso você esteja deletando ou algo do tipo, tem que colocar um delay
