### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#761]
## Description

It's again. @edgardmessias I remember that you add additional timer for fix it. Or no? 

## Environment

- **Wppconnect version(s):** [1.11.1]
- **Browser:** [Chrome 87]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2138.13]
- **MultiDevice (BETA):** no

## Log Output

```
 Status Session:  isLogged
 Session name:  whatsappsession
 Status Session:  inChat
 Session name:  whatsappsession
 error on create ReferenceError: WAPI is not defined
     at __puppeteer_evaluation_script__:56:47
     at __puppeteer_evaluation_script__:56:78
     at j (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:379576)
     at new g (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:370471)
     at anonymous (__puppeteer_evaluation_script__:54:14)
 .[32minfo.[39m:     [whatsappsession:client] WhatsApp WEB version: 2.2138.13

```

**Comment by edgardmessias** [comment]
Hello @antirek , this error was caused probably by a timeout page load.

It's keep ocurring every time or randonly?

**Comment by antirek** [comment]
Hi @edgardmessias  
It was randomly (I thought), but when I decrease memory for wppconnect instance and chrome loading slowly - all right )))

**Comment by wenioferraz** [comment]
Boa tarde, acontece comigo sempre que foi solicitar funções como isConnected, restart, getHost e por ai vai...

**Comment by wenioferraz** [comment]
NOTA: RESOLVI ATUALIZANDO O NODE PARA v14.18.2

**Comment by dudanogueira** [comment]
Guys I have faced this issue. Seems that when this happens, **you also cannot login from whatsapp web from browser**, it get's stucked on loading the chats.

https://www.reddit.com/r/whatsapp/comments/k4ezk4/whatsapp_web_stuck_on_loading_screen_after/

Still investigating, but looks like the message on mobile gets corrupt, and doesn't load properly anywhere. Solutions points to loosing all messages from mobile, clearing the cache, etc.
