### ISSUE TITLE
strange: don't sendMessage to same numbers

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#776]
## Description

change to 1.12.0 and try send to my number 7913529292926 -> chatStatus 404 Not Found
return to 1.11.0 -> send successfully 

## Environment

- **Wppconnect version(s):** [1.12.0]
- **Browser:** [Chrome 87]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2138.13]
- **MultiDevice (BETA):** no

**Comment by edgardmessias** [comment]
Could you make more tests?

Because this method is the same between these versions

**Comment by antirek** [comment]
I don't know how catch this anomaly. Send message, receive 404 - all ok but not send.
Also try on wppconnect@1.11.1 - all work normal - send to my whatsapp normal.

**Comment by leobevi** [comment]
I updated to 1.12.0, I have some customers started having this problem too, I went back to version 1.11.1 and it didn't solve the problem, the messages are not sent and the checkNumber all return as non-existent. The solution I found for these customers was to update to the Beta version of whatsapp, it worked normally again.

**Comment by edgardmessias** [comment]
Coud you try with 1.12.2?

I made update to throw errors from whatsapp servers

**Comment by antirek** [comment]
@edgardmessias

can't get status 79135292926@c.us

`````
Server5xxDrop
     at new i (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:414484)
     at new p (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:41:28118)
     at Object.on5xx (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:55:588481)
     at Object.onMessage (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:55:589362)
     at Object._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:60:18006)
     at Object._onMessage (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:60:17612)
`````
also I test from other accounts from my colleagues
and from one whatsapp message was sent successful
but from other whatsapp not was sent 

difference which I found - in sender field  'isBusiness: true'

sender: {
     id: '7995XXXXXXX@c.us',
     type: 'in',
     isBusiness: true,
     forcedBusinessUpdateFromServer: true,
     formattedName: '�.�.',
     isMe: true,
     isMyContact: false,
     isPSA: false,
     isUser: true,
     isWAContact: true,
     profilePicThumbObj: null,
     msgs: null
   },
