### ISSUE TITLE
sendText não está enviando todas as mensagens!

### ISSUE THREAD

**Issue by alanvictorjp** [wppconnect-team/wppconnect#783]
## Description

A função sendText não está enviando todas as mensagens na versão 1.12.0, mas na versão 1.11.1 sim!

Na versão 1.12.0, testando em loop com tempo de 3 segundos entre msgs, de 10 msgs são enviados 8 a 9 msgs, as que não são enviadas, dá um delay na lib, não envia e não gera erro.

Na versão 1.11.1 está funcionando normalmente.

## Environment

- **Wppconnect version(s):** 1.12.0
- **Browser:** testado com Chrome  e Chromium
- **OS:** debian 10
- **Node version:** node 16.13.1
- **WhatsApp version:**  2.2144.11
- **MultiDevice (BETA):** no

**Comment by edgardmessias** [comment]
Obrigado @alanvictorjp , vou tentar reproduzir aqui, caso você descubra algo, não esqueça de nós informar

**Comment by alanvictorjp** [comment]
Então, uma coisa que eu percebi nos testes.
sempre faço backup do dir node_modules aqui.

Quanto atualizei para 1.12.0, deu esse problema acima, dai removi o dir node_modules/@wppconnect-team e instalei a versão 1.11.1, mas não resolveu, posso está enganado, mas eu acho que não é o wppconnect em si e sim alguma dependência de nova versão.

**Comment by edgardmessias** [comment]
Tente novamente com a versão 1.12.2, os servidores do whatsapp tem retornado mais erros, e agora forcei a exibição desses erros

**Comment by alanvictorjp** [comment]
fiz alguns testes na versão 1.12.2, até agora, 100% os envios

**Comment by edgardmessias** [comment]
Que bom @alanvictorjp, é como disse, está tendo um problema pelo lado do whatsapp, agora estou forçando esses erros para ficarem mais claros
