### ISSUE TITLE
Random LogOut

### ISSUE THREAD

**Issue by ferhacks** [wppconnect-team/wppconnect#784]
## Description

[Description of the bug, When Issue Happens]
The library connects correctly to WhatsApp web and works normally, however, there are rare occasions (After 3 crashes approximately) The session is deleted and I have to rescan the Code
## Environment

- **Wppconnect version(s):** [1.12.0  ]
- **Browser:** [Chrome idk version]
- **OS:** [Ubuntu 21.10 Server]
- **Node version:** [Node 15]
- **WhatsApp version:** [ 2.2144.11 ]
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

1 Start bot

2 Waiting for Random crashing

## Log Output

```
If relevant, paste all of your Log Output
```
None

## Your Code

```
wppconnect
  .create({
    // ...
    session: 'mySessionName',
    headless: true,                                                                                   useChrome : true,
    autoClose : 0,                                                                                    puppeteerOptions: {
      userDataDir: './tokens/mySessionName', // or your custom directory                              },
    // ...                                                                                          })                                                                                                .then((client) => { console.log("AEA")
  client.setTheme("dark")
  client.waPage.setViewport({                                                                         width: 1366,                                                                                      height: 768                                                                                     })                                                                                              
client.onParticipantsChanged(async (participants) => {                                                console.log(participants)                                                                         console.log(await client.getContact(participants.who[0]))
})
global.secondbot = client})
  .catch((error) => console.log(error));                                                          }

```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

when this disconnection occurs, the WhatsApp web version changes to: 2.2147.11 for some reason

is all I managed to grasp

Sorry for bad English

**Comment by AlexandreDev06** [comment]
I'm also stuck with the exact same error as you @ferhacks , were you able to find something of what could be the problem?

**Comment by edgardmessias** [comment]
@ferhacks @AlexandreDev06 , Do you know some function or event that are crashing and doint this?

**Comment by ferhacks** [comment]
> @ferhacks @AlexandreDev06 , Do you know some function or event that are crashing and doint this?

using Eval process.exit() gets logout, i get this

http:     [mySessionName:client] Current state: SYNCING (CONNECTING)
http:     [mySessionName:client] Current state: QR (CONNECTING)
http:     [mySessionName:client] Current state: QR (CONNECTING)
http:     [mySessionName:client] Current state: QR (CONNECTING)
info:     [mySessionName:client] WhatsApp WEB version: 2.2144.11
http:     [mySessionName:client] Current state: QR (CONNECTING)
http:     [mySessionName:client] Checking is logged...
http:     [mySessionName:client] Waiting for QRCode Scan...
info:     [mySessionName:client] Waiting for QRCode Scan (Attempt 1)...:
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄ █  ▄██ █▀██▄▀▀▄▀ ▀▀▄▀▄ █▀▄█ ▄▄▄▄▄ █
█ █   █ █▀  ▄▀▀▄█ ▀▀█▄ ▀▄█▄▀▄█  ▀█▄█ ▀█ █   █ █
█ █▄▄▄█ █▀▄▀█▄▀▄▀▀█ ▄ ▄▄▄ ▄█▀▀▄▄█▀▀▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█▄▀ ▀ ▀▄█▄▀ █▄█ ▀▄▀ █▄▀ ▀ █▄█▄▄▄▄▄▄▄█
█  ▄▄▄█▄▄ █▄▄ ▄▀▄▄▄ ▄▄▄▄ ▄ ▄▀█  ██▄█   █ ▀ █ ██
█▄ ▀▄▀▄▄▄█▄ ▀▄▄██  ▀▀▄██▀▄▀█ ▄▀▀▄▀▄▄  ▀█▄▄▄  ▀█
█▄█▀ ▀▄▄▀ ▀ █ ▄█▄▄  ▄▄▄▀▄  █▀█  ▄██▄▀▀▀▄█▀▄▀ ▀█
██▄█▄█▄▄▄ ▀▀    ▀▄  ▀█ █  ██▄▀▄▄▄ ▄▀███ ▀█▀ ▀██
██▀▀█ ▀▄█▀██▄█▄▀ ▄ ▄ █▄▄▀▄▀▄▄▀▀▀▄██▄   █▀▀▀▄▀▀█
██▀ █  ▄▀▄▄▀▄█▀▀  █ ▀▄██▄   ▄▀█▄▄ ▄▀▀▀ ▀▄▄▄ ███
█ ▀▀▀ ▄▄▄ ▀▀▀ ▀▀▄██▄▀ ▄▄▄  ▄█▀▀ ▄▀███ ▄▄▄ ▀████
█▀▄▄▀ █▄█ ▄█ ▀█ ▄▀▀▄▀ █▄█ █▄▄  █▄█▄▀▄ █▄█   ▄██
█▀▀ █  ▄▄▄  ▄  ██▄ ▄▄   ▄▄ █▀█▀ ▄▀█▄▄ ▄ ▄▄▀█▄██
█▀▀ ▀  ▄ ▄▀ ▄  ▀█▄ ██▄█  ▀▄▄ ▄▄▀  ▀▀▀▄▄█▄█▀  ██
█▀█▄▀▀█▄▄▀ ▄▀▀ ▀▄▄  ▄ ██ ▀ █▀▀▄▀ █▀███ ▀▄▄█▄▀▀█
█▀ ▄▄ ▀▄  ▀▀█ ▀█▄█▀▄██▄ ▀▀ ▄ ▀▄▀███▄▀▄ ▀█▄▀ █▀█
█▀▄█  ▀▄██▀▀▀▄▀▀█▄    ▀██▄▄███  ▄▀█▄█▀▀▀▀▄▀▄▀ █
██▀▀▀ █▄  ▀▀▀██▄▀▀  ▀▄▀▀▀▀ ▄▄█ ▀▀▀ ▄ █▄█▄▄█▀███
█▄██▄▄█▄█ ▀▄  ▀▀▀▄▄ ▀ ▄▄▄  █▀█ ▀▄██▄█ ▄▄▄ ▄▀▀ █
█ ▄▄▄▄▄ █▄▀▄▄▀ ▄█▄ ▄  █▄█ ▄▄▄▄█       █▄█ ▄▀▄██
█ █   █ █ ▄██ ▀▀██  ▀▄ ▄ ▄▄██▀▄▀█▀▄▄ ▄ ▄▄  ▀▀▄█
█ █▄▄▄█ █ ▀▀ ▄ ▀▄▄▀█▀▀█ ▀▄▄  ▀▄▀█ ▄▄▄▄▀███▀ █▄█
█▄▄▄▄▄▄▄█▄▄▄▄█████▄▄████▄▄▄███▄█▄██████████▄▄██
 {"code":"1@7PMhC5wjJIWtNufUXoOWjj2NLd69jLqs3Qhs8hgBqu13gqKeEkM3yUCNMP/UKW4lCbvdC7x73Phz4A==,N4F4WVnCJyaJhgMI3elqvlhEeXs7ChRKpIFEOauyxhw=,/V1xZci2EssWVYwz/mwojQ=="}
info:     [mySessionName:session] Session Unpaired
verbose:  [mySessionName:token] Token removed

**Comment by ferhacks** [comment]
and Updates Whatsapp Version

info:     [mySessionName:client] WhatsApp WEB version: 2.2149.4
info:     [mySessionName:client] Waiting for QRCode Scan (Attempt 3)...:
