### ISSUE TITLE
Error Sending Document

### ISSUE THREAD

**Issue by LucasSPanaro** [wppconnect-team/wppconnect#788]
## Description

Sending file using sendFileFromBase64 is broken, always having the following error:

## Log Output
TypeError: Cannot read property 'attributes' of undefined
    at Object.Jt [as scope] (/home/appuser/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:51518)
    at Object.<anonymous> (/home/appuser/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:34630)
    at Generator.next (<anonymous>)
    at Ue (/home/appuser/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:33534)
    at a (/home/appuser/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:33738)
    at j (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:2:418374)
    at MutationObserver.B (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:2:417953)

**Comment by LucasSPanaro** [comment]
Already made changes on the code to use WA-JS, but I don't have permission to create a branch/pull request

**Comment by edgardmessias** [comment]
> Already made changes on the code to use WA-JS, but I don't have permission to create a branch/pull request

Hi, to do that, you must create a fork of main repository before

**Comment by edgardmessias** [comment]
@LucasSPanaro , could you provide more information to reproduce?

I tried here, but still ok

**Comment by LucasSPanaro** [comment]
The file is sent, but a error is returned.
I'm using:
- Chrome Version 97.0.4692.71, but also can reproduce on Chromium version
- whatsappVersion: "2.2147.16", but also able to reproduce with "2, 2149, 4"
- Wppconnect version 1.12.0
- OS/Node version node:16.13-alpine3.13
- MultiDevice (BETA): yes, Whatsapp Business
- npm version 8.1.4

I get the error with the following payload:

await client.sendFile(
    JID
    'https://fase.org.br/wp-content/uploads/2014/05/exemplo-de-pdf.pdf',
    'exemplo-de-pdf.pdf',
    '' )



![Screenshot from 2022-01-13 22-03-03](https://user-images.githubusercontent.com/60262614/149433379-25ba3647-8763-4e5c-855c-7d9169047111.png)

**Comment by LucasSPanaro** [comment]
The file is sent, but a error is returned.
I'm using:

Chrome Version 97.0.4692.71, but also can reproduce on Chromium version
whatsappVersion: "2.2147.16", but also able to reproduce with "2, 2149, 4"
Wppconnect version 1.12.0
OS/Node version node:16.13-alpine3.13
MultiDevice (BETA): yes, Whatsapp Business
npm version 8.1.4
I get the error with the following payload:

await client.sendFile(
JID
'https://fase.org.br/wp-content/uploads/2014/05/exemplo-de-pdf.pdf',
'exemplo-de-pdf.pdf',
'' )

![Screenshot from 2022-01-13 22-03-03](https://user-images.githubusercontent.com/60262614/149434735-162ade96-63a4-4673-bf30-df51de978a46.png)

**Comment by edgardmessias** [comment]
Wait next version.

Note: I am Brazilian too, join in our discord
