### ISSUE TITLE
checkNumberStatus está bugada (não funciona sempre)

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#792]
## Description

A função "checkNumberStatus" está bugada, ou seja, uma hora funciona e outra hora não. Eu fiz um teste usando o meu número 554498764492 COM e SEM nono digito, direto pelo puppeteer (headless:false), e mesmo assim retornou o erro 404.

![image](https://user-images.githubusercontent.com/35501007/149609947-72fee943-8e17-4e15-a4dd-0b99f95d41c1.png)

## Environment

- **Wppconnect version(s):** [1.12.1]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO

**Comment by edgardmessias** [comment]
Eu vi que essa função não está disparando erro correto, marcando tudo como não existente.

Vou corrigir para disparar o erro correto para esses casos.

Note: O erro que você está tendo é causado pelo próprio whatsapp ou pela conexão do seu celular.
