### ISSUE TITLE
Função "getNumberProfile" está bugada (não funciona sempre)

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#793]
## Description

A função "getNumberProfile" também está bugada, ou seja, uma hora funciona e outra hora não. Eu fiz um teste usando o meu número 554498764492 COM e SEM nono digito, direto pelo puppeteer (headless:false), e mesmo assim retornou o erro 404.

![image](https://user-images.githubusercontent.com/35501007/149610207-cc93d641-3586-4ae9-ab94-3c9343422d97.png)

## Environment

- **Wppconnect version(s):** [1.12.1]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO

**Comment by edgardmessias** [comment]
Primeiramente essa função está depreciada.

Segundo é que eu vi que essa função não está disparando erro correto, marcando tudo como não existente.

Vou corrigir para disparar o erro correto para esses casos.

Note: O erro que você está tendo é causado pelo próprio whatsapp ou pela conexão do seu celular.
