### ISSUE TITLE
Erro "Server5xxDrop" ao chamar "getGroupInfoFromInviteLink"

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#794]
## Description

Está retornando este erro quando eu chamo o trecho de código abaixo:

let info = await client.getGroupInfoFromInviteLink(invite);

Já tentei passar na variável invite o URL completo e somente o código do convite sem "https://chat.whatsapp.com" e mesmo assim uma hora retorna as informações corretas e outra hora não.

Eu faço 4 tentativas, em uma delas eu chamo o getBatteryLevel pra tentar forçar a conexão, as vezes dá certo, nem sempre.

Observação importante: Ao abrir o browser do puppeteer com headless:false eu percebi que está bem bugado as funções, parece que até pra enviar mensagens está lento, mesmo mantendo a tela do celular ligada no Whatsapp.

![image](https://user-images.githubusercontent.com/35501007/149627400-dc492739-3da0-4ce9-8892-87f4875d960b.png)

## Environment

- **Wppconnect version(s):** [1.12.1]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** NO
## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
error  Server5xxDrop
    at new i (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:2:452434)
    at new f (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:61:24219)
    at y.on5xx (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:56:576420)
    at y.onMessage (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:56:577302)
    at y._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:61:18040)
    at y._onMessage (https://web.whatsapp.com/bootstrap_qr.37dacf21ec9d2c474b8e.js:61:17646)
```

## Your Code

```
send_to = send_to.replace(/ /g, '');

                if ((send_to).includes("chat.whatsapp")) {

                    type = "group";

                    inviteLink = send_to;

                    inviteCode = send_to.replace('chat.whatsapp.com/', '');
                    inviteCode = inviteCode.replace('invite/', '');
                    inviteCode = inviteCode.replace('https://', '');
                    inviteCode = inviteCode.replace('http://', '');

                    let erros = 0;
                    let invite = inviteLink;
                    let tentativa = 0;

                    for (let i=0; i<2; i++) {

                        tentativa++;

                        for (j=0; j<2; j++) {

                            try {
                            
                                profile = (await new Promise(
                                    (s, f) => {
                                        client.getGroupInfoFromInviteLink(invite)
                                        .then(result => {
                                            s(result);
                                        })
                                        .catch(async err => {
    
                                            try {
                                                await client.getBatteryLevel();
                                            } catch (error) {
                                                console.log('getBatteryLevel error ', error);
                                            }
                                            
                                            invite = inviteCode;
                                            erros++;
                                            f(err);
    
                                        })
                                    })
                                );
                                
                            } catch (error) {
                                console.log('error ', error);
                            }
    
                            if (erros==0) {
                                break;
                            }

                        } 

                        if (erros==0) {
                            break;
                        } else {

                            try {
                                await client.getConnectionState();
                            } catch (error) {
                                console.log('getConnectionState error ', error);
                            }

                        }
                        
                    }

                }

(...)
```

**Comment by edgardmessias** [comment]
Fiz vários testes aqui e não tive problemas.

Acredito que todos os problemas que você está tendo pode ser relacionado ao próprio servidor do WhatsApp, ou sua conexão com a internet, ou até mesmo link inválido

**Comment by mvac1991** [comment]
Tudo estava funcionando normalmente, ai de repente começa esses BUGS.

Não, não é problemas com internet, nem link inválido.

Vc testou usando o mesmo ambiente que o meu? (descrito na issue)

Testou usando um Android?

**Comment by mvac1991** [comment]
Dá uma olhada nisso Edgar, por gentileza, tudo está bugado, até quando eu coloco headless:false pra tentar usar como um whatsapp web mesmo, a maioria das funções está bugada, só não dá bug quando eu uso o celular

![image](https://user-images.githubusercontent.com/35501007/149645824-95309622-5949-45a9-929c-9e3d7ed3bb27.png)

**Comment by mvac1991** [comment]
Não sei se é relevante, o concole do browser mostra isso:

![image](https://user-images.githubusercontent.com/35501007/149645837-567003c9-8ee5-43a6-b74a-793f3a199749.png)

**Comment by edgardmessias** [comment]
> 

Sim, fiz todos os teste, inclusive com outras versões, existe algo de muito esquisito com o seu ambiente, pois não conseguimos reproduzir esses erros em outros lugares

**Comment by edgardmessias** [comment]
> Não sei se é relevante, o console do browser mostra isso:
> 
> ![image](https://user-images.githubusercontent.com/35501007/149645837-567003c9-8ee5-43a6-b74a-793f3a199749.png)

Esses info no console.log é normal, pois é bloqueado a URL que verifica atualização.

O restante dos erros é por causa de estar tentando ler sourceMap que não existe me ambiente de produção do whatsapp

**Comment by mvac1991** [comment]
> > 
> 
> Sim, fiz todos os teste, inclusive com outras versões, existe algo de muito esquisito com o seu ambiente, pois não conseguimos reproduzir esses erros em outros lugares

Eu acho que pode ser alguma coisa referente ao aparelho, fiz os mesmo testes com outro aparelho e funcionou normalmente, tanto a lib + node quanto as funções invocadas diretamente no browser.

Eu vi que na LIB puxa os dados no HostDevice, será que haveria a possibilidade de alterar manualmente por exemplo o MAC ou IMEI? Creio que isso deva resolver

**Comment by edgardmessias** [comment]
Sinta se livre para testar localmente com essa alteração que você sugeriu e informe agente como que foi

**Comment by mvac1991** [comment]
Como eu faço para interceptar o retorno das informações geradas no getHostDevice?

> Sinta se livre para testar localmente com essa alteração que você sugeriu e informe agente como que foi

**Comment by mvac1991** [comment]
> Sinta se livre para testar localmente com essa alteração que você sugeriu e informe agente como que foi

Descobri aqui Edgar, e me parece que deu certo, melhorou bastante viu, vou fazer mais testes kkk

![image](https://user-images.githubusercontent.com/35501007/149676605-f38b19f8-3dba-40f0-bb5d-9be252e0270b.png)
