### ISSUE TITLE
Version 2 Project

### ISSUE THREAD

**Issue by edgardmessias** [wppconnect-team/wppconnect#808]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2470%20Funded-%2300A156.svg" />](https://issuehunt.io/r/wppconnect-team/wppconnect/issues/808)

In order to organize the ideia os new version of WPPConnect, this issue will be used to centralize all main features.

- [ ] Allow to create session without start
- [ ] Allow to attach events before session start
- [x] Loading percentage while is sincronizing
- [ ] Migrate to Playwright
- [x] Pass message ID before send message
- [x] Send MP4 videos using Chromium (#104)
- [ ] Support to use with Electron

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $70.00)

- [<img src='https://avatars.githubusercontent.com/u/17491023?v=4' alt='hafidzaini' width=24 height=24> hafidzaini](https://issuehunt.io/u/hafidzaini) ($20.00)
- $50.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/wppconnect-team/wppconnect/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by antirek** [comment]
playwright - interesting idea 👍

**Comment by ghsgabriel** [comment]
I believe that saving incoming conversation and message tokens in a database, decreases resource consumption and helps with horizontal scalability. But it would definitely add a lot to the complexity.
Anyway, here's the idea for us to analyze the possibility. (If you give me a guide on how to do it, I'm willing to at least try)

**Comment by ghsgabriel** [comment]
> I believe that saving incoming conversation and message tokens in a database, decreases resource consumption and helps with fallback servers. But it would definitely add a lot to the complexity. Anyway, here's the idea for us to analyze the possibility. (If you give me a guide on how to do it, I'm willing to at least try)

If we implement this we can an option to delete all incoming/sent messages right after being saved in database

**Comment by ghsgabriel** [comment]
Maybe use Deno

**Comment by edupoli** [comment]
Allow to create session without start ......... goood

**Comment by igorgazoni** [comment]
No carregamento do Whatsapp Web, ser possível saber quando está fase "Carregando mensagens", para exibir por exemplo para o usuário que está carregando, e está em X por cento.

Ser exibido nos logs de carregamento da lib esses estados....pq quando está em headless false, no log exibe somente "inicializando" e ai não da pra saber se deu algum erro de versionamento ou se é porque está nessa fase de carregamento (que as vezes pode demorar dependendo do tempo que não abre o whatsapp web e/ou qtd de novas msg que chegaram no celular

![WhatsApp Image 2022-03-10 at 08 27 21](https://user-images.githubusercontent.com/40158562/157667242-9e24eb4d-c01f-492e-b95b-a152ce8cefc7.jpeg)
)
![image](https://user-images.githubusercontent.com/40158562/157667417-37584ba3-03c5-42d1-a0bf-652de983a9e4.png)
