### ISSUE TITLE
Can not Open UI chat function (openChat) for empty Chat.

### ISSUE THREAD

**Issue by nasir101** [wppconnect-team/wppconnect#826]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WPPConnect version(s):** 1.12.2
- **WA-JS version(s):**1.1.9
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows 10 / OSX X.Y.Z
- **Node version:** Node 16.13.2
- **WhatsApp version:** 2.2144.11
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code
function start(client) {
    client.openChat('xxxxxxxxxxxx@c.us');
}

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot
![image](https://user-images.githubusercontent.com/87616977/150653287-8c2dabb5-3294-4e15-bc44-77e8a48d5e03.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
Fixed in f218c3bf198e0886423cb0de984e10eee193d29e and [v1.12.5](https://github.com/wppconnect-team/wppconnect/releases/tag/v1.12.5)
