### ISSUE TITLE
Fetching profile picts in long running session

### ISSUE THREAD

**Issue by Guhaaa** [wppconnect-team/wppconnect#852]
Hi!

I'm fetching profile picts (ProfilePicThumbObj) using getProfilePicFromServer which contains eurl. Right after session start all goes smooth, but after a few days the url signature become expired, you can try it yourself using this url https://pps.whatsapp.net/v/t61.24694-24/181426978_386363619092662_2042030740554882485_n.jpg?ccb=11-4&oh=c5a47a537466613428fef086d3390692&oe=61FA1D1B

How I can fetch fresh url?

**Comment by antirek** [comment]
use getProfilePicFromServer again! 

or cache this pic: you fetch profile pic using getProfilePicFromServer then you must save received image to your disk and use so long time what you want

for example, I use filebump with download method (https://github.com/antirek/filebump/blob/main/routes/download.js) - I pass eurl to download, receive cached url in filebump service and use new link forever ))

**Comment by edgardmessias** [comment]
Thanks @antirek
