### ISSUE TITLE
Erro na função restartService

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#862]
Error: Cannot read properties of undefined (reading 'default')

- **WPPConnect version(s):** 1.12.4
- **WA-JS version(s):** 1.1.16
- **Browser:** Chrome 
- **OS:** CentOs 7
- **Node version:** Node 16
- **WhatsApp version:** 2.2202.12
- **MultiDevice (BETA):** yes

**Comment by antirek** [comment]
more logs?

**Comment by jtapeg** [comment]
![image](https://user-images.githubusercontent.com/52453013/153058402-b9603059-1560-4591-ae2b-22592df957a1.png)

**Comment by edgardmessias** [comment]
It is an unused function, probally I will remove it.
