### ISSUE TITLE
Erro na função setGroupProperty

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#863]
Log do catch:
![image](https://user-images.githubusercontent.com/52453013/153059166-7fe8db5e-91c5-4542-bb2d-8b9a8a939d0f.png)

- **WPPConnect version(s):** 1.12.5
- **WA-JS version(s):** 1.1.16
- **Browser:** Chrome 100
- **OS:** CentOs 7
- **Node version:** Node 16
- **WhatsApp version:** 2.2202.12
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Fixed in WA-JS v1.1.17 - https://github.com/wppconnect-team/wa-js/releases/tag/v1.1.17
