### ISSUE TITLE
Função onParticipantsChanged não esta funcionando

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#864]
Notei que a função onParticipantsChanged não esta funcionando com nenhum evento mais
Exemplo do codigo usado nos testes:
```javascript
client.onParticipantsChanged(async (event) => {
    console.log("onParticipantsChanged\n", event);
});
```

- **WPPConnect version(s):** 1.12.5
- **WA-JS version(s):** 1.1.16
- **Browser:** Chrome 97
- **OS:** CentOs 7
- **Node version:** Node 16
- **WhatsApp version:** 2.2202.12
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Poderia verificar se no onMessage ou onAnyMessage está chegando eventos do tipo 'gp2'?

**Comment by jtapeg** [comment]
Não esta mas, essa função voltou a funcionar em uma versão mais antiga do whatsapp!

**Comment by edgardmessias** [comment]
Certo, esses eventos dependem diretamente das mensagens, pois existem outros tipos de mensagem (type e subtype), e a partir deles que é feito esses eventos do grupo.

**Comment by megustalol** [comment]
Nessa mesma onParticipantsChanged, não estou recebendo os eventos de entrada/saida de membros do grupo, simplesmente não acontece nada

client.onParticipantsChanged(async (participants) => {
    console.log(participants)
    if(participants.action == 'remove' || participants.action == 'leave') return;
  })
