### ISSUE TITLE
Multidevice don't keep auth

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#866]
## Description

I auth instance by reading qr-code, all ok - I send messages, receive messages
after 20-30 minutes for example I restart instance 
and receive in console log:   [whatsappsession:session] Session Unpaired

## Environment

- **WPPConnect version(s):** 1.12.5
- **WA-JS version(s):** 1.1.16
- **Browser:** Chrome 98
- **OS:** Ubuntu 20.04
- **Node version:** Node 16
- **WhatsApp version:** 2.2204.9
- **MultiDevice (BETA):** yes

and I use createClient as https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/creating-client.html#multidevice-beta

**Comment by jtapeg** [comment]
Comigo esta acontecendo tambem

**Comment by taknamecom** [comment]
Same Problem.

**Comment by h4775346** [comment]
Same Here

**Comment by edgardmessias** [comment]
The hardest part of this problem is about "reproduce". I will try here

**Comment by nonna2010** [comment]
same here
