### ISSUE TITLE
Evento "onAck" gera SELF incorreto

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#886]
## Description

Ao ENVIAR mensagens do CELULAR o evento "**onAck**" vem com **SELF = 'IN'**, o ID da mensagem vem correto, só o SELF que está errado, deveria ser **'OUT'**.

![image](https://user-images.githubusercontent.com/35501007/154077124-b3cfd049-ce31-4425-b508-137b1f1c6485.png)

## Environment

- **Wppconnect version(s):** [1.12.5]
- **Browser:** [Google Chrome 96.0.4664.45]
- **OS:** [WINDOWS 10]
- **Node version:** [Node 14]
- **WhatsApp version:** [2.2149.4]
- **MultiDevice (BETA):** NO
- **WhatsApp APP (BETA, Business ou Comum):** Comum
## Steps to Reproduce

1. "Ligue" o evento "onAck"
2. Coloque o console.log no resultado do "onAck"
3. Envie uma mensagem pelo CELULAR

## Your Code

```
client.onAck(async (ack) => {

            console.log('ack', ack);

            (...)

```

## Solution (in my code)

```
ack.self = message.id.includes('true_') ? 'out' : 'in';

```

**Comment by edgardmessias** [comment]
Isso não é um BUG, na verdade isso representa a direção da mensagem dentro do WhatsApp Web, ou seja, como você descreveu, a mensagem foi enviada pelo celular, mas no WhatsApp WEB, essa mensagem foi "recebida" na interface.

Fez correto em usar o ID da mensagem para saber quem fez o envio, existe, esse atributo representa o "fromMe" no código, ou seja, ele de fato indica quem enviou a mensagem.
