### ISSUE TITLE
Quando o celular é desconectado da internet não gera nenhum log de aviso

### ISSUE THREAD

**Issue by devpremium** [wppconnect-team/wppconnect#89]
Uma opção que pensei é ele identificar a desconexão de alguma maneira e gerar um log no statusFind que o celular esta desconectado da internet

**Comment by edgardmessias** [comment]
Boa tarde.

Na versão nightly coloquei uma opção para permitir ativar phoneWatchdog, na qual força a verificação de conexão do celular com o WhatsApp.

Para usar basta seguir o código: 
```js
// Para iniciar
client.startPhoneWatchdog(15000); // onde tempo é em milissegundo, logo, 15000 é igual a 15 segundos.

// Para parar
client.stopPhoneWatchdog();
```

Lembrando que o WhatsApp internamente tem um mecanismo que retarda a notificação de desconexão, sendo em média de até 25 segundos após a última verificação.

Para instalar a versão nightly: https://wppconnect-team.github.io/wppconnect/pages/Getting%20Started/installation.html

**Comment by edgardmessias** [comment]
Você pode agora verificar melhor o status do telefone utilizando o [onStateChange](https://wppconnect-team.github.io/wppconnect/classes/whatsapp.html#onstatechange) sendo igual a `TIMEOUT`.
Juntamente com o [startPhoneWatchdog](https://wppconnect-team.github.io/wppconnect/classes/whatsapp.html#startphonewatchdog), você pode forçar uma periodicidade melhor, pois o WhatsApp apenas verifica apenas quando é realizado alguma ação.
