### ISSUE TITLE
Atualizar a pagina 2 vezes desconecta do whatsapp

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#891]
Atualizar a pagina 2 vezes desconecta do whatsapp, usei a função client.page.reload() e tambem atualizando direto na pagina, esta acontecendo apenas no wppconnect

## Environment

- **WPPConnect version(s):** 1.12.5
- **WA-JS version(s):** 1.1.18
- **Browser:** Chrome 97
- **OS:** CentOs 7 e Windows 11
- **Node version:** Node 16
- **WhatsApp version:** 2.2204.13
- **MultiDevice (BETA):** yes

**Comment by JandersonFB** [comment]
também estou com esse problema;

**Comment by nonna2010** [comment]
same problem

**Comment by edgardmessias** [comment]
Duplicate of #866
