### ISSUE TITLE
SendText e SendImage

### ISSUE THREAD

**Issue by VitorHugoS** [wppconnect-team/wppconnect#915]
Ao enviar mensagens, ele esta colocando sozinho no status, tanto o texto quanto as imagens tbm

**Comment by JoyG42** [comment]
I'm also facing the same problem
If someone has solution please post it immediately

**Comment by edgardmessias** [comment]
Não foi informado nada que possa ajudar a resolver essa issue e também mais ninguém reportou esse tipo de problema
