### ISSUE TITLE
Error: Chat not found for status@broadcast

### ISSUE THREAD

**Issue by JandersonFB** [wppconnect-team/wppconnect#942]
Olá pessoal, mais alguém com esse problema?

![image](https://user-images.githubusercontent.com/11274709/157713013-0b13bc3a-3048-40c5-af95-41927f659aca.png)

![image](https://user-images.githubusercontent.com/11274709/157716876-17165ff7-3d83-4efe-88fb-7a75f5560940.png)

**Comment by antirek** [comment]
what do you do? show code

status@broadcast isn't chat. Do you try send message to status@broadcast?

**Comment by dudanogueira** [comment]
I have had this.  Some of our users too, while using
https://github.com/dudanogueira/rocket.connect

probably related to https://github.com/wppconnect-team/wppconnect/issues/463

One of our users was able to workaround deleting all the contacts on whatsapp. But this is not possible for some.
