### ISSUE TITLE
Console.log no codigo

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#971]
![image](https://user-images.githubusercontent.com/52453013/159731385-520030a7-abf2-4436-9fc8-dcfe3998a9ab.png)

**Comment by edgardmessias** [comment]
Isso já foi resolvido na v1.12.8

https://github.com/wppconnect-team/wppconnect/commit/f865d48791f11c2d27f41ccda8a8a1493e90be19#diff-9a3ea0ac793d3ef40605dff91244f07ccfa47167aa6db01c4c4c21a3813d20a2L359
