### ISSUE TITLE
Problema com a Função SendButtons

### ISSUE THREAD

**Issue by WesleyMarinho** [wppconnect-team/wppconnect#984]
Estou com probema nessa parte... "dynamic_reply" : true,
Com isso ao clicar no botão ele envia msg pra mim como uma resposta e nesse jeito os apk não estao conseguindo capturar o comando para fazer o auto responder.

Tentei mudar para false, mas ai ele nao manda os botoes. O opcional seria que ao clicar no botão viesse como uma mensagem normal porque do contrario esta dando esse problema.

**Comment by edgardmessias** [comment]
Tente agora com a nova release. Teste com a opção useTemplateButtons: true ou false. Os botões é para estar funcionando no beta do business.

https://github.com/wppconnect-team/wppconnect/releases/tag/v1.13.0
