### ISSUE TITLE
setProfileStatus is not working as expected.

### ISSUE THREAD

**Issue by hardik323** [wppconnect-team/wppconnect#990]
Here is the code example I tried:
```
wppconnect
  .create()
  .then((client) => start(client))
  .catch((error) => console.log(error));

function start(client){
    client.setProfileStatus("</dev>")
  .then(e=>console.log(e))
  .catch(e=>console.log(e))
}
```

The issue here is, it is not updating profile status (media or text) but it updates profile's "About" section, which is I think not expected.
![image](https://user-images.githubusercontent.com/56799528/161259050-1557bbc5-2627-4ab4-9af5-809dae1eb082.png)

**Comment by antirek** [comment]
what is your proposal? I use setProfileStatus for update profile's "About" section.

**Comment by edgardmessias** [comment]
The porpose of setProfileStatus is for update profile's "About" section.
